const TEAMS = [
  { id: 'bahia1959', club: 'Bahia', year: 1959, label: 'Bahia 1959 (1o Campeonato Nacional)', coach: 'Otacilio Goncalves',
    colors: { p: '#003399', s: '#ffffff' },
    players: [
      { name: 'Paulo', pos: ['GOL'], ovr: 79 },
      { name: 'Antonio', pos: ['LD'], ovr: 76 },
      { name: 'Raimundo', pos: ['ZAG'], ovr: 78 },
      { name: 'Bino', pos: ['ZAG'], ovr: 77 },
      { name: 'Dema', pos: ['LE'], ovr: 76 },
      { name: 'Nilton', pos: ['VOL'], ovr: 77 },
      { name: 'Ze', pos: ['VOL'], ovr: 76 },
      { name: 'Magalhaes', pos: ['MEI'], ovr: 79 },
      { name: 'Mario', pos: ['PD'], ovr: 78 },
      { name: 'Doval', pos: ['ATA'], ovr: 82 },
      { name: 'Orlando', pos: ['PE'], ovr: 78 },
      { name: 'Elinaldo', pos: ['GOL'], ovr: 71 },
      { name: 'Batista', pos: ['LD'], ovr: 73 },
      { name: 'Airton', pos: ['ZAG'], ovr: 72 },
      { name: 'Juarez', pos: ['VOL'], ovr: 73 },
      { name: 'Ezio', pos: ['MEI'], ovr: 74 },
      { name: 'Hilton', pos: ['MEI'], ovr: 73 },
      { name: 'Carlinhos', pos: ['ATA'], ovr: 75 },
      { name: 'Nelson', pos: ['ATA'], ovr: 72 },
      { name: 'Adao', pos: ['PE'], ovr: 71 },
    ]},
  { id: 'santos1961', club: 'Santos', year: 1961, label: 'Santos 1961 (Taca Brasil)', coach: 'Lula',
    colors: { p: '#000000', s: '#ffffff' },
    players: [
      { name: 'Gylmar', pos: ['GOL'], ovr: 86 },
      { name: 'Lima', pos: ['LD'], ovr: 78 },
      { name: 'Mauro', pos: ['ZAG'], ovr: 82 },
      { name: 'Calvet', pos: ['ZAG'], ovr: 76 },
      { name: 'Dalmo', pos: ['LE'], ovr: 77 },
      { name: 'Zito', pos: ['VOL','MEI'], ovr: 87 },
      { name: 'Mengalvio', pos: ['VOL','MEI'], ovr: 83 },
      { name: 'Dorval', pos: ['PD','ATA'], ovr: 80 },
      { name: 'Coutinho', pos: ['MEI','ATA'], ovr: 88 },
      { name: 'Pele', pos: ['ATA','MEI'], ovr: 99 },
      { name: 'Pepe', pos: ['PE','ATA'], ovr: 89 },
      { name: 'Laercio', pos: ['GOL'], ovr: 72 },
      { name: 'Carlos Alberto Torres', pos: ['LD'], ovr: 75 },
      { name: 'Clodoaldo', pos: ['VOL','MEI'], ovr: 74 },
      { name: 'Toninho Guerreiro', pos: ['ATA'], ovr: 76 },
      { name: 'Edu', pos: ['PE','ATA'], ovr: 74 },
      { name: 'Olavo', pos: ['ZAG'], ovr: 73 },
      { name: 'Tite', pos: ['PE'], ovr: 73 },
      { name: 'Formiga', pos: ['VOL'], ovr: 72 },
      { name: 'Apolinario', pos: ['ZAG'], ovr: 70 },
    ]},
  { id: 'santos1962', club: 'Santos', year: 1962, label: 'Santos 1962 (Libertadores + Mundial + Taca Brasil)', coach: 'Lula',
    colors: { p: '#000000', s: '#ffffff' },
    players: [
      { name: 'Gylmar', pos: ['GOL'], ovr: 90 },
      { name: 'Lima', pos: ['LD'], ovr: 80 },
      { name: 'Mauro', pos: ['ZAG'], ovr: 86 },
      { name: 'Calvet', pos: ['ZAG'], ovr: 78 },
      { name: 'Dalmo', pos: ['LE'], ovr: 79 },
      { name: 'Zito', pos: ['VOL','MEI'], ovr: 90 },
      { name: 'Mengalvio', pos: ['VOL','MEI'], ovr: 86 },
      { name: 'Dorval', pos: ['PD','ATA'], ovr: 84 },
      { name: 'Coutinho', pos: ['MEI','ATA'], ovr: 92 },
      { name: 'Pele', pos: ['ATA','MEI'], ovr: 99 },
      { name: 'Pepe', pos: ['PE','ATA'], ovr: 91 },
      { name: 'Carlos Alberto Torres', pos: ['LD'], ovr: 76 },
      { name: 'Clodoaldo', pos: ['VOL','MEI'], ovr: 78 },
      { name: 'Toninho Guerreiro', pos: ['ATA'], ovr: 76 },
      { name: 'Edu', pos: ['PE','ATA'], ovr: 74 },
      { name: 'Joel', pos: ['ZAG'], ovr: 72 },
      { name: 'Laercio', pos: ['GOL'], ovr: 73 },
      { name: 'Rodrigues Neto', pos: ['ZAG'], ovr: 71 },
      { name: 'Orlando', pos: ['ATA'], ovr: 70 },
      { name: 'Pagao', pos: ['LD'], ovr: 70 },
    ]},
  { id: 'botafogo1968', club: 'Botafogo', year: 1968, label: 'Botafogo 1968', coach: 'Zagallo',
    colors: { p: '#000000', s: '#ffffff' },
    players: [
      { name: 'Cao', pos: ['GOL'], ovr: 79 },
      { name: 'Moreira', pos: ['LD'], ovr: 77 },
      { name: 'Ze Carlos', pos: ['ZAG'], ovr: 78 },
      { name: 'Leonidas', pos: ['ZAG'], ovr: 77 },
      { name: 'Waltencir', pos: ['LE'], ovr: 78 },
      { name: 'Carlos Roberto', pos: ['VOL'], ovr: 81 },
      { name: 'Gerson', pos: ['MEI','VOL'], ovr: 92 },
      { name: 'Rogerio', pos: ['PD'], ovr: 80 },
      { name: 'Roberto', pos: ['ATA'], ovr: 81 },
      { name: 'Jairzinho', pos: ['ATA','PD'], ovr: 93 },
      { name: 'Paulo Cezar Caju', pos: ['PE','MEI'], ovr: 86 },
      { name: 'Ubirajara Motta', pos: ['GOL'], ovr: 71 },
      { name: 'Chiquinho Pastor', pos: ['ZAG'], ovr: 73 },
      { name: 'Moises', pos: ['ZAG'], ovr: 72 },
      { name: 'Nei Conceicao', pos: ['VOL'], ovr: 75 },
      { name: 'Zequinha', pos: ['PD'], ovr: 74 },
      { name: 'Ferretti', pos: ['ATA'], ovr: 78 },
      { name: 'Humberto', pos: ['ATA'], ovr: 74 },
      { name: 'Afonsinho', pos: ['MEI'], ovr: 76 },
      { name: 'Torino', pos: ['ATA'], ovr: 72 },
    ]},
  { id: 'fluminense1970', club: 'Fluminense', year: 1970, label: 'Fluminense 1970 (1o titulo nacional)', coach: 'Yustrich',
    colors: { p: '#7a1e3c', s: '#006437' },
    players: [
      { name: 'Edinho', pos: ['GOL'], ovr: 79 },
      { name: 'Marco Antonio', pos: ['LD'], ovr: 76 },
      { name: 'Lucio', pos: ['ZAG'], ovr: 78 },
      { name: 'Renato', pos: ['ZAG'], ovr: 77 },
      { name: 'Brito', pos: ['LE'], ovr: 79 },
      { name: 'Piazza', pos: ['VOL'], ovr: 79 },
      { name: 'Rocha', pos: ['VOL'], ovr: 77 },
      { name: 'Tele Santana', pos: ['MEI'], ovr: 82 },
      { name: 'Dario', pos: ['PD'], ovr: 78 },
      { name: 'Dada Maravilha', pos: ['ATA'], ovr: 83 },
      { name: 'Paulo Cesar Caju', pos: ['PE','MEI'], ovr: 81 },
      { name: 'Paulo Victor', pos: ['GOL'], ovr: 72 },
      { name: 'Rildo', pos: ['ZAG','LE'], ovr: 80 },
      { name: 'Tostao', pos: ['ATA','MEI'], ovr: 88 },
      { name: 'Rivellino', pos: ['MEI'], ovr: 87 },
      { name: 'Clodoaldo', pos: ['VOL'], ovr: 80 },
      { name: 'Paulo Cesar Lula', pos: ['PE','MEI'], ovr: 78 },
      { name: 'Leomir', pos: ['PE'], ovr: 77 },
      { name: 'Fernando', pos: ['LD'], ovr: 73 },
      { name: 'Wilson Piazza', pos: ['VOL'], ovr: 79 },
    ]},
  { id: 'atletico-mg1971', club: 'Atletico-MG', year: 1971, label: 'Atletico-MG 1971 (1o titulo)', coach: 'Vantuil de Oliveira',
    colors: { p: '#000000', s: '#ffffff' },
    players: [
      { name: 'Laerte', pos: ['GOL'], ovr: 78 },
      { name: 'Licio', pos: ['LD'], ovr: 76 },
      { name: 'Raimundo', pos: ['ZAG'], ovr: 78 },
      { name: 'Vantuil', pos: ['ZAG'], ovr: 77 },
      { name: 'Maneco', pos: ['LE'], ovr: 76 },
      { name: 'Rogerio', pos: ['VOL'], ovr: 78 },
      { name: 'Dario', pos: ['VOL'], ovr: 77 },
      { name: 'Reinaldo', pos: ['MEI'], ovr: 83 },
      { name: 'Ezio', pos: ['PD'], ovr: 79 },
      { name: 'Dada Maravilha', pos: ['ATA'], ovr: 84 },
      { name: 'Angelo', pos: ['PE'], ovr: 78 },
      { name: 'Marinho', pos: ['GOL'], ovr: 71 },
      { name: 'Sergio', pos: ['LD'], ovr: 73 },
      { name: 'Carlos', pos: ['ZAG'], ovr: 72 },
      { name: 'Gil', pos: ['VOL'], ovr: 73 },
      { name: 'Tiao', pos: ['MEI'], ovr: 74 },
      { name: 'Edu', pos: ['ATA'], ovr: 75 },
      { name: 'Ze Maria', pos: ['LE'], ovr: 72 },
      { name: 'Wilson', pos: ['ATA'], ovr: 72 },
      { name: 'Jonas', pos: ['PD'], ovr: 71 },
    ]},
  { id: 'palmeiras1972', club: 'Palmeiras', year: 1972, label: 'Palmeiras 1972 (Academia)', coach: 'Osvaldo Brandao',
    colors: { p: '#006437', s: '#ffffff' },
    players: [
      { name: 'Leao', pos: ['GOL'], ovr: 85 },
      { name: 'Eurico', pos: ['LD'], ovr: 78 },
      { name: 'Luis Pereira', pos: ['ZAG'], ovr: 86 },
      { name: 'Alfredo', pos: ['ZAG'], ovr: 77 },
      { name: 'Zeca', pos: ['LE'], ovr: 78 },
      { name: 'Dudu', pos: ['VOL'], ovr: 84 },
      { name: 'Ademir da Guia', pos: ['MEI','PD'], ovr: 91 },
      { name: 'Edu Bala', pos: ['PD','MEI'], ovr: 81 },
      { name: 'Madurga', pos: ['ATA'], ovr: 78 },
      { name: 'Leivinha', pos: ['ATA','PE'], ovr: 87 },
      { name: 'Nei', pos: ['PE'], ovr: 80 },
      { name: 'Ze Carlos', pos: ['MEI'], ovr: 73 },
      { name: 'Ronaldo', pos: ['ATA'], ovr: 74 },
      { name: 'Cesar', pos: ['ATA'], ovr: 73 },
      { name: 'Marco Antonio', pos: ['VOL'], ovr: 74 },
      { name: 'Ostrovski', pos: ['LD'], ovr: 71 },
      { name: 'Baldochi', pos: ['ZAG'], ovr: 72 },
      { name: 'Flavio', pos: ['MEI'], ovr: 75 },
      { name: 'Alfredo Jr', pos: ['ZAG'], ovr: 70 },
      { name: 'Rinaldo', pos: ['PE'], ovr: 70 },
    ]},
  { id: 'palmeiras1973', club: 'Palmeiras', year: 1973, label: 'Palmeiras 1973 (Bicampeonato Academia)', coach: 'Osvaldo Brandao',
    colors: { p: '#006437', s: '#ffffff' },
    players: [
      { name: 'Leao', pos: ['GOL'], ovr: 85 },
      { name: 'Eurico', pos: ['LD'], ovr: 78 },
      { name: 'Luis Pereira', pos: ['ZAG'], ovr: 87 },
      { name: 'Alfredo', pos: ['ZAG'], ovr: 77 },
      { name: 'Zeca', pos: ['LE'], ovr: 78 },
      { name: 'Dudu', pos: ['VOL'], ovr: 85 },
      { name: 'Ademir da Guia', pos: ['MEI','PD'], ovr: 92 },
      { name: 'Edu Bala', pos: ['PD','MEI'], ovr: 82 },
      { name: 'Cesar', pos: ['ATA'], ovr: 79 },
      { name: 'Leivinha', pos: ['ATA','PE'], ovr: 88 },
      { name: 'Nei', pos: ['PE'], ovr: 80 },
      { name: 'Ze Carlos', pos: ['MEI'], ovr: 74 },
      { name: 'Ronaldo', pos: ['ATA'], ovr: 75 },
      { name: 'Marco Antonio', pos: ['VOL'], ovr: 75 },
      { name: 'Luis Carlos', pos: ['LD'], ovr: 73 },
      { name: 'Gilberto', pos: ['ZAG'], ovr: 72 },
      { name: 'Flavio', pos: ['MEI'], ovr: 76 },
      { name: 'Edilson', pos: ['ATA'], ovr: 74 },
      { name: 'Amaral', pos: ['PE'], ovr: 71 },
      { name: 'Cica', pos: ['MEI'], ovr: 70 },
    ]},
  { id: 'vasco1974', club: 'Vasco', year: 1974, label: 'Vasco 1974 (1o Brasileiro moderno)', coach: 'Mario Travaglini',
    colors: { p: '#000000', s: '#ffffff' },
    players: [
      { name: 'Andrada', pos: ['GOL'], ovr: 80 },
      { name: 'Fidelis', pos: ['LD'], ovr: 76 },
      { name: 'Miguel', pos: ['ZAG'], ovr: 78 },
      { name: 'Moises', pos: ['ZAG'], ovr: 79 },
      { name: 'Alfinete', pos: ['LE'], ovr: 77 },
      { name: 'Alcir', pos: ['VOL'], ovr: 78 },
      { name: 'Zanata', pos: ['VOL','MEI'], ovr: 79 },
      { name: 'Ademir', pos: ['MEI'], ovr: 79 },
      { name: 'Jorginho Carvoeiro', pos: ['PD','MEI'], ovr: 82 },
      { name: 'Roberto Dinamite', pos: ['ATA'], ovr: 88 },
      { name: 'Luiz Carlos', pos: ['PE'], ovr: 78 },
      { name: 'Carlos Henrique', pos: ['GOL'], ovr: 72 },
      { name: 'Paulo Cesar', pos: ['LD'], ovr: 74 },
      { name: 'Joel', pos: ['ZAG'], ovr: 74 },
      { name: 'Gaucho', pos: ['VOL'], ovr: 76 },
      { name: 'Jair Pereira', pos: ['PD'], ovr: 74 },
      { name: 'Amarildo', pos: ['ATA'], ovr: 76 },
      { name: 'Bill', pos: ['ATA'], ovr: 72 },
      { name: 'Galdino', pos: ['PE'], ovr: 73 },
      { name: 'Marcelo', pos: ['ZAG'], ovr: 72 },
    ]},
  { id: 'internacional1975', club: 'Internacional', year: 1975, label: 'Internacional 1975', coach: 'Rubens Minelli',
    colors: { p: '#d2122e', s: '#ffffff' },
    players: [
      { name: 'Manga', pos: ['GOL'], ovr: 83 },
      { name: 'Valdir', pos: ['LD'], ovr: 76 },
      { name: 'Figueroa', pos: ['ZAG'], ovr: 92 },
      { name: 'Herminio', pos: ['ZAG'], ovr: 77 },
      { name: 'Chico Fraga', pos: ['LE'], ovr: 76 },
      { name: 'Cacapava', pos: ['VOL'], ovr: 79 },
      { name: 'Falcao', pos: ['MEI','VOL'], ovr: 90 },
      { name: 'Carpegiani', pos: ['MEI','VOL'], ovr: 83 },
      { name: 'Valdomiro', pos: ['PD','ATA'], ovr: 80 },
      { name: 'Flavio Minuano', pos: ['ATA'], ovr: 85 },
      { name: 'Lula', pos: ['PE'], ovr: 79 },
      { name: 'Tony', pos: ['LD'], ovr: 71 },
      { name: 'Belini', pos: ['ZAG'], ovr: 72 },
      { name: 'Jair', pos: ['PD','ATA'], ovr: 75 },
      { name: 'Escurinho', pos: ['ATA'], ovr: 73 },
      { name: 'Dario', pos: ['ATA'], ovr: 72 },
      { name: 'Batista', pos: ['VOL'], ovr: 77 },
      { name: 'Romano', pos: ['MEI'], ovr: 73 },
      { name: 'Duilio', pos: ['ATA'], ovr: 70 },
      { name: 'Darcy', pos: ['PE'], ovr: 70 },
    ]},
  { id: 'corinthians1977', club: 'Corinthians', year: 1977, label: 'Corinthians 1977', coach: 'Oswaldo Brandao',
    colors: { p: '#000000', s: '#ffffff' },
    players: [
      { name: 'Emerson', pos: ['GOL'], ovr: 78 },
      { name: 'Ze Maria', pos: ['LD'], ovr: 79 },
      { name: 'Geraldo', pos: ['ZAG'], ovr: 77 },
      { name: 'Macaranduba', pos: ['ZAG'], ovr: 76 },
      { name: 'Wladimir', pos: ['LE','MEI'], ovr: 81 },
      { name: 'Palinha', pos: ['VOL'], ovr: 80 },
      { name: 'Rivellino', pos: ['MEI'], ovr: 84 },
      { name: 'Zizinho Jr', pos: ['MEI'], ovr: 77 },
      { name: 'Casagrande', pos: ['ATA'], ovr: 79 },
      { name: 'Basilio', pos: ['ATA','MEI'], ovr: 82 },
      { name: 'Sylvinho', pos: ['PE'], ovr: 76 },
      { name: 'Renato', pos: ['GOL'], ovr: 71 },
      { name: 'Rodrigo', pos: ['LD'], ovr: 73 },
      { name: 'Eurico', pos: ['ZAG'], ovr: 72 },
      { name: 'Marco', pos: ['VOL'], ovr: 74 },
      { name: 'Lula', pos: ['MEI'], ovr: 75 },
      { name: 'Nene', pos: ['ATA'], ovr: 76 },
      { name: 'Sofocles', pos: ['PE'], ovr: 72 },
      { name: 'Cleber', pos: ['ATA'], ovr: 72 },
      { name: 'Toninho', pos: ['LD'], ovr: 71 },
    ]},
  { id: 'guarani1978', club: 'Guarani', year: 1978, label: 'Guarani 1978 (Unico titulo)', coach: 'Jair Pereira',
    colors: { p: '#006437', s: '#ffffff' },
    players: [
      { name: 'Manga', pos: ['GOL'], ovr: 80 },
      { name: 'Valber', pos: ['LD'], ovr: 76 },
      { name: 'Pedrinho', pos: ['ZAG'], ovr: 78 },
      { name: 'Macaranduba', pos: ['ZAG'], ovr: 77 },
      { name: 'Moraes', pos: ['LE'], ovr: 76 },
      { name: 'Djalma', pos: ['VOL'], ovr: 78 },
      { name: 'Juari', pos: ['VOL','MEI'], ovr: 80 },
      { name: 'Ronaldo', pos: ['MEI'], ovr: 78 },
      { name: 'Careca', pos: ['ATA'], ovr: 85 },
      { name: 'Paulo Cesar', pos: ['ATA','MEI'], ovr: 82 },
      { name: 'Leandro', pos: ['PE'], ovr: 78 },
      { name: 'Toninho', pos: ['GOL'], ovr: 71 },
      { name: 'Sergio', pos: ['LD'], ovr: 73 },
      { name: 'Leandro Jr', pos: ['ZAG'], ovr: 72 },
      { name: 'Mauro', pos: ['VOL'], ovr: 73 },
      { name: 'Ze Luis', pos: ['MEI'], ovr: 74 },
      { name: 'Roque', pos: ['ATA'], ovr: 75 },
      { name: 'Adriano', pos: ['PE'], ovr: 72 },
      { name: 'Alves', pos: ['ATA'], ovr: 72 },
      { name: 'Henrique', pos: ['LD'], ovr: 71 },
    ]},
  { id: 'internacional1979', club: 'Internacional', year: 1979, label: 'Internacional 1979 (Invicto)', coach: 'Enio Andrade',
    colors: { p: '#d2122e', s: '#ffffff' },
    players: [
      { name: 'Benitez', pos: ['GOL'], ovr: 82 },
      { name: 'Joao Carlos', pos: ['LD'], ovr: 76 },
      { name: 'Mauro Pastor', pos: ['ZAG'], ovr: 77 },
      { name: 'Mauro Galvao', pos: ['ZAG'], ovr: 84 },
      { name: 'Claudio Mineiro', pos: ['LE'], ovr: 76 },
      { name: 'Batista', pos: ['VOL'], ovr: 80 },
      { name: 'Falcao', pos: ['MEI','VOL'], ovr: 93 },
      { name: 'Jair', pos: ['MEI','VOL'], ovr: 82 },
      { name: 'Valdomiro', pos: ['PD'], ovr: 79 },
      { name: 'Bira', pos: ['ATA'], ovr: 78 },
      { name: 'Mario Sergio', pos: ['PE','ATA'], ovr: 80 },
      { name: 'Chico Spina', pos: ['ATA'], ovr: 76 },
      { name: 'Beliato', pos: ['ZAG'], ovr: 72 },
      { name: 'Larry', pos: ['ZAG'], ovr: 71 },
      { name: 'Toninho', pos: ['VOL'], ovr: 72 },
      { name: 'Claudiomir', pos: ['LD'], ovr: 71 },
      { name: 'Gilberto', pos: ['PE'], ovr: 70 },
      { name: 'Lula', pos: ['PE','ATA'], ovr: 74 },
      { name: 'Marcos', pos: ['MEI'], ovr: 71 },
      { name: 'Renato', pos: ['ATA'], ovr: 70 },
    ]},
  { id: 'flamengo1980', club: 'Flamengo', year: 1980, label: 'Flamengo 1980', coach: 'Claudio Coutinho',
    colors: { p: '#c8102e', s: '#000000' },
    players: [
      { name: 'Raul', pos: ['GOL'], ovr: 84 },
      { name: 'Toninho', pos: ['LD'], ovr: 78 },
      { name: 'Rondinelli', pos: ['ZAG'], ovr: 79 },
      { name: 'Marinho', pos: ['ZAG'], ovr: 82 },
      { name: 'Junior', pos: ['LE','PE'], ovr: 91 },
      { name: 'Andrade', pos: ['VOL'], ovr: 86 },
      { name: 'Carpegiani', pos: ['MEI'], ovr: 81 },
      { name: 'Zico', pos: ['MEI'], ovr: 97 },
      { name: 'Tita', pos: ['PD'], ovr: 83 },
      { name: 'Nunes', pos: ['ATA'], ovr: 85 },
      { name: 'Julio Cesar', pos: ['PE'], ovr: 78 },
      { name: 'Cantarelli', pos: ['GOL'], ovr: 70 },
      { name: 'Nei Dias', pos: ['LD'], ovr: 72 },
      { name: 'Figueiredo', pos: ['ZAG'], ovr: 78 },
      { name: 'Vitor', pos: ['VOL'], ovr: 74 },
      { name: 'Lico', pos: ['PD','ATA'], ovr: 79 },
      { name: 'Peu', pos: ['ATA'], ovr: 75 },
      { name: 'Anselmo', pos: ['ATA'], ovr: 71 },
      { name: 'Carlos Henrique', pos: ['ATA'], ovr: 76 },
      { name: 'Barao', pos: ['MEI'], ovr: 73 },
    ]},
  { id: 'flamengo1981', club: 'Flamengo', year: 1981, label: 'Flamengo 1981 (Libertadores + Mundial)', coach: 'Paulo Cesar Carpegiani',
    colors: { p: '#c8102e', s: '#000000' },
    players: [
      { name: 'Raul', pos: ['GOL'], ovr: 85 },
      { name: 'Leandro', pos: ['LD','PD'], ovr: 88 },
      { name: 'Marinho', pos: ['ZAG'], ovr: 82 },
      { name: 'Mozer', pos: ['ZAG'], ovr: 85 },
      { name: 'Junior', pos: ['LE','PE'], ovr: 92 },
      { name: 'Andrade', pos: ['VOL'], ovr: 87 },
      { name: 'Adilio', pos: ['MEI'], ovr: 84 },
      { name: 'Zico', pos: ['MEI'], ovr: 98 },
      { name: 'Lico', pos: ['PD','ATA'], ovr: 80 },
      { name: 'Tita', pos: ['ATA','PD'], ovr: 84 },
      { name: 'Nunes', pos: ['PE','ATA'], ovr: 87 },
      { name: 'Cantarelli', pos: ['GOL'], ovr: 70 },
      { name: 'Nei Dias', pos: ['LD'], ovr: 72 },
      { name: 'Figueiredo', pos: ['ZAG'], ovr: 78 },
      { name: 'Vitor', pos: ['VOL'], ovr: 74 },
      { name: 'Baroninho', pos: ['MEI'], ovr: 73 },
      { name: 'Carlos Henrique', pos: ['ATA'], ovr: 76 },
      { name: 'Paulo Cesar', pos: ['ATA'], ovr: 73 },
      { name: 'Pirilo', pos: ['ZAG'], ovr: 71 },
      { name: 'Eduardo', pos: ['PE'], ovr: 71 },
    ]},
  { id: 'flamengo1982', club: 'Flamengo', year: 1982, label: 'Flamengo 1982 (Tricampeonato)', coach: 'Paulo Cesar Carpegiani',
    colors: { p: '#c8102e', s: '#000000' },
    players: [
      { name: 'Raul', pos: ['GOL'], ovr: 84 },
      { name: 'Leandro', pos: ['LD','PD'], ovr: 87 },
      { name: 'Marinho', pos: ['ZAG'], ovr: 81 },
      { name: 'Figueiredo', pos: ['ZAG'], ovr: 78 },
      { name: 'Junior', pos: ['LE','PE'], ovr: 91 },
      { name: 'Andrade', pos: ['VOL'], ovr: 86 },
      { name: 'Adilio', pos: ['MEI'], ovr: 84 },
      { name: 'Zico', pos: ['MEI'], ovr: 97 },
      { name: 'Tita', pos: ['PD','ATA'], ovr: 82 },
      { name: 'Lico', pos: ['ATA','PD'], ovr: 79 },
      { name: 'Nunes', pos: ['PE','ATA'], ovr: 87 },
      { name: 'Cantarelli', pos: ['GOL'], ovr: 70 },
      { name: 'Mozer', pos: ['ZAG'], ovr: 83 },
      { name: 'Vitor', pos: ['VOL'], ovr: 74 },
      { name: 'Chiquinho Carioca', pos: ['ATA'], ovr: 75 },
      { name: 'Anselmo', pos: ['ATA'], ovr: 71 },
      { name: 'Carlos Henrique', pos: ['ATA'], ovr: 76 },
      { name: 'Nei Dias', pos: ['LD'], ovr: 72 },
      { name: 'Jose Carlos', pos: ['LD'], ovr: 71 },
      { name: 'Eduardo', pos: ['PE'], ovr: 71 },
    ]},
  { id: 'fluminense1984', club: 'Fluminense', year: 1984, label: 'Fluminense 1984 (Maquina Tricolor)', coach: 'Carlos Alberto Parreira',
    colors: { p: '#7a1e3c', s: '#006437' },
    players: [
      { name: 'Paulo Vitor', pos: ['GOL'], ovr: 81 },
      { name: 'Aldo', pos: ['LD'], ovr: 77 },
      { name: 'Duilio', pos: ['ZAG'], ovr: 80 },
      { name: 'Ricardo Gomes', pos: ['ZAG'], ovr: 88 },
      { name: 'Branco', pos: ['LE','PE'], ovr: 87 },
      { name: 'Jandir', pos: ['VOL'], ovr: 78 },
      { name: 'Delei', pos: ['MEI'], ovr: 79 },
      { name: 'Romerito', pos: ['MEI','VOL'], ovr: 86 },
      { name: 'Assis', pos: ['PD'], ovr: 83 },
      { name: 'Washington', pos: ['ATA'], ovr: 82 },
      { name: 'Tato', pos: ['PE'], ovr: 80 },
      { name: 'Ricardo Lopes', pos: ['LD'], ovr: 73 },
      { name: 'Renato Martins', pos: ['LE'], ovr: 74 },
      { name: 'Vica', pos: ['MEI'], ovr: 73 },
      { name: 'Leomir', pos: ['MEI'], ovr: 75 },
      { name: 'Wilsinho', pos: ['PD'], ovr: 74 },
      { name: 'Paulinho', pos: ['ATA'], ovr: 73 },
      { name: 'Getulio', pos: ['LD'], ovr: 72 },
      { name: 'Fernando', pos: ['ZAG'], ovr: 71 },
      { name: 'Ivan', pos: ['VOL'], ovr: 70 },
    ]},
  { id: 'coritiba1985', club: 'Coritiba', year: 1985, label: 'Coritiba 1985 (Unico titulo)', coach: 'Enio Andrade',
    colors: { p: '#006437', s: '#ffffff' },
    players: [
      { name: 'Rafael', pos: ['GOL'], ovr: 83 },
      { name: 'Andre', pos: ['LD'], ovr: 76 },
      { name: 'Gomes', pos: ['ZAG'], ovr: 79 },
      { name: 'Heraldo', pos: ['ZAG'], ovr: 78 },
      { name: 'Dida', pos: ['LE'], ovr: 76 },
      { name: 'Almir', pos: ['VOL'], ovr: 78 },
      { name: 'Marildo', pos: ['MEI'], ovr: 76 },
      { name: 'Tobi', pos: ['MEI'], ovr: 79 },
      { name: 'Lela', pos: ['PD'], ovr: 80 },
      { name: 'Indio', pos: ['ATA'], ovr: 81 },
      { name: 'Edson', pos: ['PE'], ovr: 78 },
      { name: 'Vava', pos: ['ZAG'], ovr: 72 },
      { name: 'Marco Aurelio', pos: ['VOL'], ovr: 73 },
      { name: 'Eliseu', pos: ['LD'], ovr: 71 },
      { name: 'Heldo', pos: ['MEI'], ovr: 72 },
      { name: 'Jardel', pos: ['ATA'], ovr: 74 },
      { name: 'Delmo', pos: ['ZAG'], ovr: 71 },
      { name: 'Rene', pos: ['VOL'], ovr: 70 },
      { name: 'Albuquerque', pos: ['PE'], ovr: 71 },
      { name: 'Neto Cida', pos: ['GOL'], ovr: 70 },
    ]},
  { id: 'sao-paulo1986', club: 'Sao Paulo', year: 1986, label: 'Sao Paulo 1986', coach: 'Pepe',
    colors: { p: '#c8102e', s: '#000000' },
    players: [
      { name: 'Gilmar', pos: ['GOL'], ovr: 82 },
      { name: 'Fonseca', pos: ['LD'], ovr: 77 },
      { name: 'Wagner Basilio', pos: ['ZAG'], ovr: 78 },
      { name: 'Dario Pereyra', pos: ['ZAG'], ovr: 83 },
      { name: 'Nelsinho', pos: ['LE'], ovr: 78 },
      { name: 'Bernardo', pos: ['VOL'], ovr: 79 },
      { name: 'Silas', pos: ['MEI'], ovr: 82 },
      { name: 'Pita', pos: ['MEI'], ovr: 84 },
      { name: 'Muller', pos: ['PD'], ovr: 88 },
      { name: 'Careca', pos: ['ATA'], ovr: 92 },
      { name: 'Sidney', pos: ['PE','ATA'], ovr: 81 },
      { name: 'Oscar', pos: ['ZAG'], ovr: 80 },
      { name: 'Falcao', pos: ['MEI'], ovr: 82 },
      { name: 'Marcio Araujo', pos: ['MEI'], ovr: 74 },
      { name: 'Ze Teodoro', pos: ['LD'], ovr: 74 },
      { name: 'Romulo', pos: ['ATA'], ovr: 73 },
      { name: 'Pianelli', pos: ['ATA'], ovr: 72 },
      { name: 'Roberto', pos: ['LE'], ovr: 71 },
      { name: 'Mauro', pos: ['VOL'], ovr: 71 },
      { name: 'Helio', pos: ['PD'], ovr: 70 },
    ]},
  { id: 'sport1987', club: 'Sport', year: 1987, label: 'Sport 1987 (Unico titulo)', coach: 'Emerson Leao',
    colors: { p: '#c8102e', s: '#000000' },
    players: [
      { name: 'Flavio', pos: ['GOL'], ovr: 78 },
      { name: 'Betao', pos: ['LD'], ovr: 75 },
      { name: 'Estevam', pos: ['ZAG'], ovr: 77 },
      { name: 'Marco Antonio', pos: ['ZAG'], ovr: 78 },
      { name: 'Ze Carlos Macae', pos: ['LE'], ovr: 76 },
      { name: 'Rogerio', pos: ['VOL'], ovr: 76 },
      { name: 'Ribamar', pos: ['MEI'], ovr: 76 },
      { name: 'Zico Sport', pos: ['MEI'], ovr: 77 },
      { name: 'Robertinho', pos: ['PD'], ovr: 77 },
      { name: 'Nando', pos: ['ATA'], ovr: 78 },
      { name: 'Neco', pos: ['PE'], ovr: 78 },
      { name: 'Sidmar', pos: ['GOL'], ovr: 72 },
      { name: 'Augusto', pos: ['VOL'], ovr: 72 },
      { name: 'Saulo', pos: ['ZAG'], ovr: 71 },
      { name: 'Paulo Roberto', pos: ['LD'], ovr: 71 },
      { name: 'Leandro', pos: ['MEI'], ovr: 73 },
      { name: 'Chiquinho', pos: ['VOL'], ovr: 70 },
      { name: 'Claudio', pos: ['ATA'], ovr: 73 },
      { name: 'Ze Carlos Jr', pos: ['LE'], ovr: 70 },
      { name: 'Marcos', pos: ['PD'], ovr: 71 },
    ]},
  { id: 'bahia1988', club: 'Bahia', year: 1988, label: 'Bahia 1988 (Unico titulo)', coach: 'Evaristo de Macedo',
    colors: { p: '#1c3f94', s: '#c8102e' },
    players: [
      { name: 'Ronaldo', pos: ['GOL'], ovr: 80 },
      { name: 'Tarantini', pos: ['LD'], ovr: 77 },
      { name: 'Joao Marcelo', pos: ['ZAG'], ovr: 78 },
      { name: 'Claudir', pos: ['ZAG'], ovr: 76 },
      { name: 'Edinho', pos: ['LE'], ovr: 76 },
      { name: 'Paulo Rodrigues', pos: ['VOL'], ovr: 81 },
      { name: 'Ze Carlos', pos: ['MEI'], ovr: 80 },
      { name: 'Bobo', pos: ['MEI'], ovr: 86 },
      { name: 'Osmar', pos: ['PD'], ovr: 77 },
      { name: 'Charles', pos: ['ATA'], ovr: 84 },
      { name: 'Marquinhos', pos: ['PE'], ovr: 79 },
      { name: 'Sidmar', pos: ['GOL'], ovr: 73 },
      { name: 'Zanata', pos: ['LD'], ovr: 74 },
      { name: 'Pereira', pos: ['ZAG'], ovr: 76 },
      { name: 'Paulo Robson', pos: ['LE'], ovr: 73 },
      { name: 'Gil Sergipano', pos: ['MEI'], ovr: 74 },
      { name: 'Renato', pos: ['ATA'], ovr: 75 },
      { name: 'Sandro', pos: ['ATA'], ovr: 72 },
      { name: 'Newmar', pos: ['ZAG'], ovr: 71 },
      { name: 'Dico', pos: ['ATA'], ovr: 70 },
    ]},
  { id: 'vasco1989', club: 'Vasco', year: 1989, label: 'Vasco 1989 (SeleVasco)', coach: 'Nelsinho Rosa',
    colors: { p: '#000000', s: '#ffffff' },
    players: [
      { name: 'Acacio', pos: ['GOL'], ovr: 81 },
      { name: 'Luis Carlos Winck', pos: ['LD'], ovr: 79 },
      { name: 'Marco Aurelio', pos: ['ZAG'], ovr: 79 },
      { name: 'Quinonez', pos: ['ZAG'], ovr: 80 },
      { name: 'Mazinho', pos: ['LE','VOL'], ovr: 84 },
      { name: 'Ze do Carmo', pos: ['VOL','MEI'], ovr: 78 },
      { name: 'Boiadeiro', pos: ['MEI'], ovr: 79 },
      { name: 'Bismarck', pos: ['MEI','PD'], ovr: 80 },
      { name: 'Bebeto', pos: ['PD','ATA'], ovr: 90 },
      { name: 'Sorato', pos: ['ATA'], ovr: 80 },
      { name: 'William', pos: ['PE'], ovr: 78 },
      { name: 'Celio Silva', pos: ['ZAG'], ovr: 73 },
      { name: 'Cassio', pos: ['LE'], ovr: 71 },
      { name: 'Andrade', pos: ['VOL'], ovr: 79 },
      { name: 'Tita', pos: ['MEI','ATA'], ovr: 78 },
      { name: 'Vivinho', pos: ['ATA'], ovr: 73 },
      { name: 'Tato', pos: ['PE'], ovr: 76 },
      { name: 'Paulinho', pos: ['LD'], ovr: 71 },
      { name: 'Rene', pos: ['ZAG'], ovr: 70 },
      { name: 'Alex', pos: ['MEI'], ovr: 70 },
    ]},
  { id: 'corinthians1990', club: 'Corinthians', year: 1990, label: 'Corinthians 1990', coach: 'Nelsinho Baptista',
    colors: { p: '#000000', s: '#ffffff' },
    players: [
      { name: 'Ronaldo', pos: ['GOL'], ovr: 80 },
      { name: 'Giba', pos: ['LD'], ovr: 77 },
      { name: 'Marcelo Djian', pos: ['ZAG'], ovr: 79 },
      { name: 'Guinei', pos: ['ZAG'], ovr: 76 },
      { name: 'Jacenir', pos: ['LE'], ovr: 76 },
      { name: 'Marcio', pos: ['VOL'], ovr: 78 },
      { name: 'Wilson Mano', pos: ['MEI','VOL'], ovr: 80 },
      { name: 'Neto', pos: ['MEI'], ovr: 89 },
      { name: 'Tupazinho', pos: ['PD','ATA'], ovr: 81 },
      { name: 'Fabinho', pos: ['ATA'], ovr: 77 },
      { name: 'Mauro', pos: ['PE'], ovr: 77 },
      { name: 'Ezequiel', pos: ['MEI'], ovr: 73 },
      { name: 'Paulo Sergio', pos: ['ATA'], ovr: 75 },
      { name: 'Dinei', pos: ['ATA'], ovr: 78 },
      { name: 'Sergio', pos: ['GOL'], ovr: 71 },
      { name: 'Antonio Carlos', pos: ['ZAG'], ovr: 73 },
      { name: 'Luisinho', pos: ['LD'], ovr: 71 },
      { name: 'Flavio', pos: ['MEI'], ovr: 72 },
      { name: 'Silvinho', pos: ['LE'], ovr: 73 },
      { name: 'Josemil', pos: ['ATA'], ovr: 70 },
    ]},
  { id: 'sao-paulo1991', club: 'Sao Paulo', year: 1991, label: 'Sao Paulo 1991 (Brasileiro)', coach: 'Tele Santana',
    colors: { p: '#c8102e', s: '#000000' },
    players: [
      { name: 'Zetti', pos: ['GOL'], ovr: 83 },
      { name: 'Cafu', pos: ['LD','PD'], ovr: 87 },
      { name: 'Antonio Carlos', pos: ['ZAG'], ovr: 84 },
      { name: 'Ricardo Rocha', pos: ['ZAG'], ovr: 85 },
      { name: 'Leonardo', pos: ['LE'], ovr: 86 },
      { name: 'Ronaldao', pos: ['VOL'], ovr: 78 },
      { name: 'Bernardo', pos: ['MEI'], ovr: 80 },
      { name: 'Rai', pos: ['MEI','PD'], ovr: 93 },
      { name: 'Muller', pos: ['PD','ATA'], ovr: 87 },
      { name: 'Macedo', pos: ['ATA'], ovr: 78 },
      { name: 'Elvelton', pos: ['PE'], ovr: 77 },
      { name: 'Ze Teodoro', pos: ['LD'], ovr: 73 },
      { name: 'Sidnei', pos: ['VOL'], ovr: 73 },
      { name: 'Suelio', pos: ['VOL'], ovr: 72 },
      { name: 'Mario Tilico', pos: ['ATA'], ovr: 75 },
      { name: 'Flavio', pos: ['ATA'], ovr: 73 },
      { name: 'Guga', pos: ['ZAG'], ovr: 71 },
      { name: 'Celso', pos: ['MEI'], ovr: 72 },
      { name: 'Paulo Sergio', pos: ['PE'], ovr: 72 },
      { name: 'Helio', pos: ['LD'], ovr: 70 },
    ]},
  { id: 'flamengo1992', club: 'Flamengo', year: 1992, label: 'Flamengo 1992', coach: 'Nelsinho Baptista',
    colors: { p: '#c8102e', s: '#000000' },
    players: [
      { name: 'Ze Carlos', pos: ['GOL'], ovr: 80 },
      { name: 'Leandro', pos: ['LD','PD'], ovr: 82 },
      { name: 'Carlos', pos: ['ZAG'], ovr: 76 },
      { name: 'Chico Anysio', pos: ['ZAG'], ovr: 75 },
      { name: 'Junior', pos: ['LE','PE'], ovr: 80 },
      { name: 'Marquinhos', pos: ['VOL'], ovr: 78 },
      { name: 'Djalminha', pos: ['MEI'], ovr: 84 },
      { name: 'Fabio Baiano', pos: ['MEI'], ovr: 80 },
      { name: 'Savio', pos: ['PD','ATA'], ovr: 82 },
      { name: 'Paulo Nunes', pos: ['ATA'], ovr: 80 },
      { name: 'Marcelinho Carioca', pos: ['MEI'], ovr: 82 },
      { name: 'Nelio', pos: ['MEI'], ovr: 77 },
      { name: 'Luis Antonio', pos: ['MEI'], ovr: 76 },
      { name: 'Tita', pos: ['ATA','MEI'], ovr: 75 },
      { name: 'William', pos: ['ATA'], ovr: 73 },
      { name: 'Pia', pos: ['LE'], ovr: 73 },
      { name: 'Sele', pos: ['LE'], ovr: 71 },
      { name: 'Edinho', pos: ['PE'], ovr: 72 },
      { name: 'Celso', pos: ['VOL'], ovr: 70 },
      { name: 'Reginaldo Araujo', pos: ['ATA'], ovr: 72 },
    ]},
  { id: 'palmeiras1993', club: 'Palmeiras', year: 1993, label: 'Palmeiras 1993 (Parmalat)', coach: 'Vanderlei Luxemburgo',
    colors: { p: '#006437', s: '#ffffff' },
    players: [
      { name: 'Sergio', pos: ['GOL'], ovr: 81 },
      { name: 'Claudio', pos: ['LD'], ovr: 77 },
      { name: 'Antonio Carlos', pos: ['ZAG'], ovr: 85 },
      { name: 'Cleber', pos: ['ZAG'], ovr: 78 },
      { name: 'Roberto Carlos', pos: ['LE','PE'], ovr: 89 },
      { name: 'Cesar Sampaio', pos: ['VOL'], ovr: 84 },
      { name: 'Mazinho', pos: ['VOL','LE'], ovr: 80 },
      { name: 'Zinho', pos: ['MEI','PD'], ovr: 85 },
      { name: 'Edilson', pos: ['PD','ATA'], ovr: 81 },
      { name: 'Edmundo', pos: ['ATA'], ovr: 90 },
      { name: 'Evair', pos: ['PE','ATA'], ovr: 86 },
      { name: 'Velloso', pos: ['GOL'], ovr: 74 },
      { name: 'Tonhao', pos: ['ZAG'], ovr: 73 },
      { name: 'Daniel Frasson', pos: ['VOL'], ovr: 74 },
      { name: 'Amaral', pos: ['VOL'], ovr: 72 },
      { name: 'Maurilio', pos: ['ATA'], ovr: 73 },
      { name: 'Jean Carlo', pos: ['MEI'], ovr: 73 },
      { name: 'Soares', pos: ['ATA'], ovr: 72 },
      { name: 'Dario', pos: ['LD'], ovr: 71 },
      { name: 'Paulo Victor', pos: ['ZAG'], ovr: 70 },
    ]},
  { id: 'palmeiras1994', club: 'Palmeiras', year: 1994, label: 'Palmeiras 1994 (Parmalat)', coach: 'Vanderlei Luxemburgo',
    colors: { p: '#006437', s: '#ffffff' },
    players: [
      { name: 'Sergio', pos: ['GOL'], ovr: 81 },
      { name: 'Claudio', pos: ['LD'], ovr: 77 },
      { name: 'Antonio Carlos', pos: ['ZAG'], ovr: 85 },
      { name: 'Cleber', pos: ['ZAG'], ovr: 78 },
      { name: 'Roberto Carlos', pos: ['LE','PE'], ovr: 90 },
      { name: 'Cesar Sampaio', pos: ['VOL'], ovr: 85 },
      { name: 'Mazinho', pos: ['VOL','LE'], ovr: 80 },
      { name: 'Zinho', pos: ['MEI','PD'], ovr: 85 },
      { name: 'Rivaldo', pos: ['PD','MEI'], ovr: 89 },
      { name: 'Edmundo', pos: ['ATA'], ovr: 91 },
      { name: 'Evair', pos: ['PE','ATA'], ovr: 86 },
      { name: 'Velloso', pos: ['GOL'], ovr: 74 },
      { name: 'Tonhao', pos: ['ZAG'], ovr: 73 },
      { name: 'Daniel Frasson', pos: ['VOL'], ovr: 74 },
      { name: 'Flavio Conceicao', pos: ['VOL'], ovr: 77 },
      { name: 'Edilson', pos: ['PD','ATA'], ovr: 81 },
      { name: 'Soares', pos: ['ATA'], ovr: 72 },
      { name: 'Jean Carlo', pos: ['MEI'], ovr: 73 },
      { name: 'Nali', pos: ['LD'], ovr: 70 },
      { name: 'Ciro', pos: ['ZAG'], ovr: 70 },
    ]},
  { id: 'botafogo1995', club: 'Botafogo', year: 1995, label: 'Botafogo 1995', coach: 'Paulo Autuori',
    colors: { p: '#000000', s: '#ffffff' },
    players: [
      { name: 'Wagner', pos: ['GOL'], ovr: 81 },
      { name: 'Wilson Goiano', pos: ['LD'], ovr: 77 },
      { name: 'Wilson Gottardo', pos: ['ZAG'], ovr: 80 },
      { name: 'Goncalves', pos: ['ZAG'], ovr: 79 },
      { name: 'Andre Silva', pos: ['LE'], ovr: 76 },
      { name: 'Leandro Avila', pos: ['VOL'], ovr: 78 },
      { name: 'Jamir', pos: ['VOL','MEI'], ovr: 78 },
      { name: 'Beto', pos: ['MEI','VOL'], ovr: 77 },
      { name: 'Sergio Manoel', pos: ['MEI','PD'], ovr: 80 },
      { name: 'Donizete', pos: ['ATA'], ovr: 81 },
      { name: 'Tulio Maravilha', pos: ['ATA'], ovr: 89 },
      { name: 'Moises', pos: ['LE'], ovr: 72 },
      { name: 'Iranildo', pos: ['MEI'], ovr: 75 },
      { name: 'Marcelo Alves', pos: ['MEI'], ovr: 72 },
      { name: 'Narcizio', pos: ['ATA'], ovr: 71 },
      { name: 'Rui', pos: ['ATA'], ovr: 71 },
      { name: 'Marcio', pos: ['LD'], ovr: 71 },
      { name: 'Claudinho', pos: ['ZAG'], ovr: 70 },
      { name: 'Jorginho', pos: ['MEI'], ovr: 71 },
      { name: 'Alan', pos: ['PE'], ovr: 70 },
    ]},
  { id: 'gremio1996', club: 'Gremio', year: 1996, label: 'Gremio 1996', coach: 'Luiz Felipe Scolari',
    colors: { p: '#1c3f94', s: '#000000' },
    players: [
      { name: 'Danrlei', pos: ['GOL'], ovr: 82 },
      { name: 'Arce', pos: ['LD','PD'], ovr: 81 },
      { name: 'Rivarola', pos: ['ZAG'], ovr: 79 },
      { name: 'Mauro Galvao', pos: ['ZAG'], ovr: 82 },
      { name: 'Roger', pos: ['LE'], ovr: 79 },
      { name: 'Dinho', pos: ['VOL','MEI'], ovr: 79 },
      { name: 'Luis Carlos Goiano', pos: ['VOL'], ovr: 78 },
      { name: 'Emerson', pos: ['MEI','VOL'], ovr: 82 },
      { name: 'Carlos Miguel', pos: ['MEI'], ovr: 79 },
      { name: 'Paulo Nunes', pos: ['ATA'], ovr: 87 },
      { name: 'Ze Alcino', pos: ['PE'], ovr: 78 },
      { name: 'Adilson', pos: ['ZAG'], ovr: 75 },
      { name: 'Luciano', pos: ['ZAG'], ovr: 73 },
      { name: 'Ailton', pos: ['ATA'], ovr: 76 },
      { name: 'Ze Afonso', pos: ['ATA'], ovr: 72 },
      { name: 'Arilson', pos: ['MEI'], ovr: 73 },
      { name: 'Helio', pos: ['LD'], ovr: 71 },
      { name: 'Marcelo', pos: ['PE'], ovr: 71 },
      { name: 'Marcio', pos: ['GOL'], ovr: 70 },
      { name: 'Jose Wilson', pos: ['ATA'], ovr: 70 },
    ]},
  { id: 'vasco1997', club: 'Vasco', year: 1997, label: 'Vasco 1997 (Brasileiro)', coach: 'Antonio Lopes',
    colors: { p: '#000000', s: '#ffffff' },
    players: [
      { name: 'Carlos Germano', pos: ['GOL'], ovr: 82 },
      { name: 'Valber', pos: ['LD'], ovr: 78 },
      { name: 'Odvan', pos: ['ZAG'], ovr: 79 },
      { name: 'Mauro Galvao', pos: ['ZAG'], ovr: 81 },
      { name: 'Felipe', pos: ['LE'], ovr: 80 },
      { name: 'Luisinho', pos: ['VOL','MEI'], ovr: 79 },
      { name: 'Nasa', pos: ['VOL','MEI'], ovr: 78 },
      { name: 'Juninho Pernambucano', pos: ['MEI','PD'], ovr: 85 },
      { name: 'Ramon', pos: ['MEI','PD'], ovr: 81 },
      { name: 'Edmundo', pos: ['ATA'], ovr: 95 },
      { name: 'Evair', pos: ['PE','ATA'], ovr: 85 },
      { name: 'Marica', pos: ['LD'], ovr: 73 },
      { name: 'Alex Pinho', pos: ['ZAG'], ovr: 72 },
      { name: 'Pedrinho', pos: ['MEI'], ovr: 77 },
      { name: 'Mauricinho', pos: ['MEI'], ovr: 72 },
      { name: 'Donizete', pos: ['ATA'], ovr: 79 },
      { name: 'Brener', pos: ['ATA'], ovr: 73 },
      { name: 'Luizao', pos: ['ATA'], ovr: 80 },
      { name: 'Gil', pos: ['ZAG'], ovr: 71 },
      { name: 'Sandro', pos: ['MEI'], ovr: 70 },
    ]},
  { id: 'vasco1998', club: 'Vasco', year: 1998, label: 'Vasco 1998 (Libertadores)', coach: 'Antonio Lopes',
    colors: { p: '#000000', s: '#ffffff' },
    players: [
      { name: 'Carlos Germano', pos: ['GOL'], ovr: 83 },
      { name: 'Vagner', pos: ['LD'], ovr: 79 },
      { name: 'Mauro Galvao', pos: ['ZAG'], ovr: 82 },
      { name: 'Odvan', pos: ['ZAG'], ovr: 80 },
      { name: 'Felipe', pos: ['LE'], ovr: 81 },
      { name: 'Luisinho', pos: ['VOL','MEI'], ovr: 80 },
      { name: 'Nasa', pos: ['VOL','MEI'], ovr: 79 },
      { name: 'Juninho Pernambucano', pos: ['MEI','PD'], ovr: 87 },
      { name: 'Pedrinho', pos: ['MEI'], ovr: 80 },
      { name: 'Edmundo', pos: ['ATA'], ovr: 91 },
      { name: 'Luizao', pos: ['ATA'], ovr: 87 },
      { name: 'Donizete', pos: ['ATA'], ovr: 84 },
      { name: 'Evair', pos: ['PE','ATA'], ovr: 83 },
      { name: 'Ramon', pos: ['MEI','PD'], ovr: 82 },
      { name: 'Cesar Prates', pos: ['LD'], ovr: 77 },
      { name: 'Alex Pinho', pos: ['ZAG'], ovr: 73 },
      { name: 'Paulo', pos: ['VOL'], ovr: 72 },
      { name: 'Valdir', pos: ['LD'], ovr: 71 },
      { name: 'Lima', pos: ['MEI'], ovr: 71 },
      { name: 'Clayton', pos: ['ATA'], ovr: 72 },
    ]},
  { id: 'corinthians1998', club: 'Corinthians', year: 1998, label: 'Corinthians 1998 (Bicampeao)', coach: 'Vanderlei Luxemburgo',
    colors: { p: '#000000', s: '#ffffff' },
    players: [
      { name: 'Nei', pos: ['GOL'], ovr: 77 },
      { name: 'Dida', pos: ['GOL'], ovr: 86 },
      { name: 'Indio', pos: ['LD'], ovr: 80 },
      { name: 'Batata', pos: ['ZAG'], ovr: 79 },
      { name: 'Marcio Costa', pos: ['ZAG'], ovr: 78 },
      { name: 'Gamarra', pos: ['ZAG'], ovr: 92 },
      { name: 'Sylvinho', pos: ['LE','PE'], ovr: 85 },
      { name: 'Vampeta', pos: ['VOL'], ovr: 88 },
      { name: 'Rincon', pos: ['MEI'], ovr: 87 },
      { name: 'Ricardinho', pos: ['MEI'], ovr: 88 },
      { name: 'Marcelinho Carioca', pos: ['MEI'], ovr: 91 },
      { name: 'Edilson', pos: ['ATA','MEI'], ovr: 90 },
      { name: 'Dinei', pos: ['ATA'], ovr: 78 },
      { name: 'Didi', pos: ['ATA'], ovr: 75 },
      { name: 'Amaral', pos: ['VOL'], ovr: 76 },
      { name: 'Cris', pos: ['ZAG','LE'], ovr: 74 },
      { name: 'Adilson', pos: ['ZAG'], ovr: 73 },
      { name: 'Kleber', pos: ['LE'], ovr: 78 },
      { name: 'Mirandinha', pos: ['ATA'], ovr: 74 },
      { name: 'Gilmar Fuba', pos: ['VOL'], ovr: 76 },
    ]},
  { id: 'corinthians1999', club: 'Corinthians', year: 1999, label: 'Corinthians 1999 (Tricampeao)', coach: 'Oswaldo de Oliveira',
    colors: { p: '#000000', s: '#ffffff' },
    players: [
      { name: 'Dida', pos: ['GOL'], ovr: 88 },
      { name: 'Indio', pos: ['LD'], ovr: 80 },
      { name: 'Joao Carlos', pos: ['ZAG'], ovr: 79 },
      { name: 'Marcio Costa', pos: ['ZAG'], ovr: 79 },
      { name: 'Kleber', pos: ['LE'], ovr: 79 },
      { name: 'Vampeta', pos: ['VOL'], ovr: 89 },
      { name: 'Rincon', pos: ['MEI'], ovr: 87 },
      { name: 'Ricardinho', pos: ['MEI'], ovr: 88 },
      { name: 'Marcelinho Carioca', pos: ['MEI'], ovr: 92 },
      { name: 'Edilson', pos: ['ATA','MEI'], ovr: 89 },
      { name: 'Luizao', pos: ['ATA'], ovr: 87 },
      { name: 'Dinei', pos: ['ATA'], ovr: 79 },
      { name: 'Marcos Senna', pos: ['VOL'], ovr: 81 },
      { name: 'Sylvinho', pos: ['LE','PE'], ovr: 86 },
      { name: 'Adilson', pos: ['ZAG'], ovr: 74 },
      { name: 'Gilmar', pos: ['VOL'], ovr: 75 },
      { name: 'Edu', pos: ['MEI'], ovr: 75 },
      { name: 'Fabinho', pos: ['ZAG'], ovr: 73 },
      { name: 'Luis Carlos', pos: ['PD'], ovr: 72 },
      { name: 'Anderson', pos: ['ATA'], ovr: 71 },
    ]},
  { id: 'vasco2000', club: 'Vasco', year: 2000, label: 'Vasco 2000 (Brasileiro + Mercosul)', coach: 'Oswaldo de Oliveira',
    colors: { p: '#000000', s: '#ffffff' },
    players: [
      { name: 'Carlos Germano', pos: ['GOL'], ovr: 82 },
      { name: 'Valber', pos: ['LD'], ovr: 77 },
      { name: 'Anderson Polga', pos: ['ZAG'], ovr: 80 },
      { name: 'Odvan', pos: ['ZAG'], ovr: 78 },
      { name: 'Felipe', pos: ['LE'], ovr: 79 },
      { name: 'Ramon', pos: ['MEI','PD'], ovr: 82 },
      { name: 'Juninho Paulista', pos: ['MEI'], ovr: 84 },
      { name: 'Pedrinho', pos: ['MEI'], ovr: 80 },
      { name: 'Luizao', pos: ['ATA'], ovr: 86 },
      { name: 'Donizete', pos: ['ATA'], ovr: 84 },
      { name: 'Romario', pos: ['ATA'], ovr: 91 },
      { name: 'Sandro', pos: ['GOL'], ovr: 71 },
      { name: 'Valdir', pos: ['LD'], ovr: 73 },
      { name: 'Mauro Galvao', pos: ['ZAG'], ovr: 79 },
      { name: 'Everton', pos: ['ATA'], ovr: 73 },
      { name: 'Nasa', pos: ['VOL'], ovr: 77 },
      { name: 'Nilton', pos: ['VOL'], ovr: 76 },
      { name: 'Paulo Victor', pos: ['MEI'], ovr: 74 },
      { name: 'Alexandre Pires', pos: ['ATA'], ovr: 75 },
      { name: 'Fabio Augusto', pos: ['LD'], ovr: 72 },
    ]},
  { id: 'athletico-pr2001', club: 'Athletico-PR', year: 2001, label: 'Athletico-PR 2001', coach: 'Geninho',
    colors: { p: '#c8102e', s: '#000000' },
    players: [
      { name: 'Flavio', pos: ['GOL'], ovr: 80 },
      { name: 'Alessandro', pos: ['LD'], ovr: 78 },
      { name: 'Rogerio Correa', pos: ['ZAG'], ovr: 78 },
      { name: 'Nem', pos: ['ZAG'], ovr: 79 },
      { name: 'Gustavo', pos: ['ZAG'], ovr: 80 },
      { name: 'Fabiano', pos: ['LE'], ovr: 77 },
      { name: 'Cocito', pos: ['VOL'], ovr: 78 },
      { name: 'Kleberson', pos: ['VOL','MEI'], ovr: 86 },
      { name: 'Adriano', pos: ['MEI'], ovr: 79 },
      { name: 'Kleber', pos: ['ATA'], ovr: 84 },
      { name: 'Alex Mineiro', pos: ['ATA'], ovr: 85 },
      { name: 'Igor', pos: ['LD'], ovr: 73 },
      { name: 'Pires', pos: ['MEI'], ovr: 72 },
      { name: 'Rodriguinho', pos: ['MEI'], ovr: 71 },
      { name: 'Souza', pos: ['ATA'], ovr: 74 },
      { name: 'Ilan', pos: ['ATA'], ovr: 73 },
      { name: 'Adauto', pos: ['ATA'], ovr: 72 },
      { name: 'Marcos', pos: ['ZAG'], ovr: 71 },
      { name: 'Ederson', pos: ['MEI'], ovr: 72 },
      { name: 'Chico', pos: ['LD'], ovr: 71 },
    ]},
  { id: 'santos2002', club: 'Santos', year: 2002, label: 'Santos 2002 (Meninos da Vila)', coach: 'Emerson Leao',
    colors: { p: '#000000', s: '#ffffff' },
    players: [
      { name: 'Fabio Costa', pos: ['GOL'], ovr: 81 },
      { name: 'Maurinho', pos: ['LD'], ovr: 78 },
      { name: 'Andre Luis', pos: ['ZAG'], ovr: 77 },
      { name: 'Alex', pos: ['ZAG'], ovr: 78 },
      { name: 'Leo', pos: ['LE'], ovr: 79 },
      { name: 'Paulo Almeida', pos: ['VOL'], ovr: 77 },
      { name: 'Renato', pos: ['VOL','MEI'], ovr: 78 },
      { name: 'Elano', pos: ['MEI'], ovr: 84 },
      { name: 'Diego', pos: ['MEI','PD'], ovr: 85 },
      { name: 'Robinho', pos: ['ATA','PE'], ovr: 92 },
      { name: 'William', pos: ['PE'], ovr: 76 },
      { name: 'Julio Cesar', pos: ['GOL'], ovr: 73 },
      { name: 'Wellington', pos: ['MEI'], ovr: 72 },
      { name: 'Alexandre', pos: ['ATA'], ovr: 73 },
      { name: 'Robert', pos: ['ATA'], ovr: 74 },
      { name: 'Michel', pos: ['ATA'], ovr: 71 },
      { name: 'Adriano', pos: ['ZAG'], ovr: 73 },
      { name: 'Felipe', pos: ['LD'], ovr: 72 },
      { name: 'Marcos', pos: ['VOL'], ovr: 71 },
      { name: 'Junior', pos: ['MEI'], ovr: 70 },
    ]},
  { id: 'cruzeiro2003', club: 'Cruzeiro', year: 2003, label: 'Cruzeiro 2003 (Triplice Coroa)', coach: 'Vanderlei Luxemburgo',
    colors: { p: '#1c3f94', s: '#ffffff' },
    players: [
      { name: 'Gomes', pos: ['GOL'], ovr: 80 },
      { name: 'Maurinho', pos: ['LD'], ovr: 78 },
      { name: 'Cris', pos: ['ZAG'], ovr: 79 },
      { name: 'Edu Dracena', pos: ['ZAG'], ovr: 82 },
      { name: 'Leandro', pos: ['LE'], ovr: 78 },
      { name: 'Maldonado', pos: ['VOL'], ovr: 79 },
      { name: 'Augusto Recife', pos: ['VOL'], ovr: 77 },
      { name: 'Wendell', pos: ['MEI'], ovr: 78 },
      { name: 'Alex', pos: ['MEI'], ovr: 90 },
      { name: 'Aristizabal', pos: ['ATA'], ovr: 82 },
      { name: 'Mota', pos: ['ATA'], ovr: 79 },
      { name: 'Maicon', pos: ['LD'], ovr: 76 },
      { name: 'Luisao', pos: ['ZAG'], ovr: 79 },
      { name: 'Felipe Melo', pos: ['VOL'], ovr: 78 },
      { name: 'Zinho', pos: ['MEI'], ovr: 73 },
      { name: 'Marcio Nobre', pos: ['ATA'], ovr: 75 },
      { name: 'Deivid', pos: ['ATA'], ovr: 78 },
      { name: 'Alex Alves', pos: ['ATA'], ovr: 74 },
      { name: 'Martinez', pos: ['MEI'], ovr: 73 },
      { name: 'Thiago', pos: ['ZAG'], ovr: 75 },
    ]},
  { id: 'santos2004', club: 'Santos', year: 2004, label: 'Santos 2004 (Bicampeonato + 103 gols)', coach: 'Vanderlei Luxemburgo',
    colors: { p: '#000000', s: '#ffffff' },
    players: [
      { name: 'Mauro', pos: ['GOL'], ovr: 78 },
      { name: 'Flavio', pos: ['LD'], ovr: 75 },
      { name: 'Avaulos', pos: ['ZAG'], ovr: 77 },
      { name: 'Leonardo', pos: ['ZAG'], ovr: 77 },
      { name: 'Leo', pos: ['LE'], ovr: 79 },
      { name: 'Fabinho', pos: ['VOL'], ovr: 77 },
      { name: 'Preto Casagrande', pos: ['VOL','MEI'], ovr: 76 },
      { name: 'Ricardinho', pos: ['MEI'], ovr: 84 },
      { name: 'Elano', pos: ['MEI'], ovr: 85 },
      { name: 'Robinho', pos: ['ATA','PE'], ovr: 91 },
      { name: 'Deivid', pos: ['ATA'], ovr: 84 },
      { name: 'Paulo Cesar', pos: ['LD'], ovr: 73 },
      { name: 'Marcinho', pos: ['MEI'], ovr: 72 },
      { name: 'Basilio', pos: ['ATA'], ovr: 71 },
      { name: 'William', pos: ['ATA','PE'], ovr: 73 },
      { name: 'Adriano', pos: ['ZAG'], ovr: 73 },
      { name: 'Rodrigo', pos: ['LD'], ovr: 71 },
      { name: 'Gabriel', pos: ['ZAG'], ovr: 72 },
      { name: 'Marquinhos', pos: ['VOL'], ovr: 71 },
      { name: 'Adriano Jr', pos: ['ATA'], ovr: 70 },
    ]},
  { id: 'corinthians2005', club: 'Corinthians', year: 2005, label: 'Corinthians 2005', coach: 'Antonio Lopes',
    colors: { p: '#000000', s: '#ffffff' },
    players: [
      { name: 'Fabio Costa', pos: ['GOL'], ovr: 80 },
      { name: 'Marinho', pos: ['LD'], ovr: 76 },
      { name: 'Wendel', pos: ['ZAG'], ovr: 77 },
      { name: 'Betao', pos: ['ZAG'], ovr: 73 },
      { name: 'Gustavo Nery', pos: ['LE'], ovr: 80 },
      { name: 'Coelho', pos: ['ZAG'], ovr: 76 },
      { name: 'Marcelo Mattos', pos: ['VOL'], ovr: 79 },
      { name: 'Bruno Octavio', pos: ['VOL','MEI'], ovr: 76 },
      { name: 'Carlos Alberto', pos: ['MEI'], ovr: 81 },
      { name: 'Tevez', pos: ['ATA'], ovr: 93 },
      { name: 'Nilmar', pos: ['ATA'], ovr: 80 },
      { name: 'Julio Cesar', pos: ['GOL'], ovr: 74 },
      { name: 'Sebastian Dominguez', pos: ['ZAG'], ovr: 76 },
      { name: 'Mascherano', pos: ['VOL'], ovr: 86 },
      { name: 'Roger', pos: ['MEI'], ovr: 78 },
      { name: 'Jo', pos: ['ATA'], ovr: 76 },
      { name: 'Wescley', pos: ['MEI'], ovr: 72 },
      { name: 'Eduardo Ratinho', pos: ['MEI'], ovr: 71 },
      { name: 'Rodrigo', pos: ['LD'], ovr: 71 },
      { name: 'Rosinei', pos: ['MEI'], ovr: 77 },
    ]},
  { id: 'sao-paulo2006', club: 'Sao Paulo', year: 2006, label: 'Sao Paulo 2006', coach: 'Muricy Ramalho',
    colors: { p: '#c8102e', s: '#000000' },
    players: [
      { name: 'Rogerio Ceni', pos: ['GOL'], ovr: 89 },
      { name: 'Ilsinho', pos: ['LD','PD'], ovr: 78 },
      { name: 'Fabao', pos: ['ZAG'], ovr: 81 },
      { name: 'Miranda', pos: ['ZAG'], ovr: 82 },
      { name: 'Junior', pos: ['LE'], ovr: 77 },
      { name: 'Mineiro', pos: ['VOL'], ovr: 81 },
      { name: 'Josue', pos: ['VOL','MEI'], ovr: 80 },
      { name: 'Souza', pos: ['MEI'], ovr: 78 },
      { name: 'Danilo', pos: ['MEI'], ovr: 80 },
      { name: 'Leandro', pos: ['PD','PE'], ovr: 77 },
      { name: 'Aloisio', pos: ['ATA'], ovr: 81 },
      { name: 'Lugano', pos: ['ZAG'], ovr: 82 },
      { name: 'Alex Silva', pos: ['ZAG'], ovr: 73 },
      { name: 'Cicinho', pos: ['LD','PD'], ovr: 79 },
      { name: 'Thiago Ribeiro', pos: ['MEI'], ovr: 75 },
      { name: 'Richarlyson', pos: ['MEI'], ovr: 74 },
      { name: 'Lenilson', pos: ['ATA'], ovr: 73 },
      { name: 'Anderson', pos: ['ATA'], ovr: 72 },
      { name: 'Rodrigo', pos: ['LD'], ovr: 71 },
      { name: 'Edcarlos', pos: ['ZAG'], ovr: 76 },
    ]},
  { id: 'sao-paulo2007', club: 'Sao Paulo', year: 2007, label: 'Sao Paulo 2007 (Bicampeonato)', coach: 'Muricy Ramalho',
    colors: { p: '#c8102e', s: '#000000' },
    players: [
      { name: 'Rogerio Ceni', pos: ['GOL'], ovr: 89 },
      { name: 'Ilsinho', pos: ['LD','PD'], ovr: 78 },
      { name: 'Fabao', pos: ['ZAG'], ovr: 80 },
      { name: 'Miranda', pos: ['ZAG'], ovr: 84 },
      { name: 'Lugano', pos: ['ZAG'], ovr: 84 },
      { name: 'Junior', pos: ['LE'], ovr: 77 },
      { name: 'Mineiro', pos: ['VOL'], ovr: 82 },
      { name: 'Josue', pos: ['VOL','MEI'], ovr: 81 },
      { name: 'Danilo', pos: ['MEI'], ovr: 81 },
      { name: 'Hernanes', pos: ['MEI'], ovr: 86 },
      { name: 'Grafite', pos: ['ATA'], ovr: 85 },
      { name: 'Aloisio', pos: ['ATA'], ovr: 80 },
      { name: 'Borges', pos: ['ATA'], ovr: 79 },
      { name: 'Cicinho', pos: ['LD','PD'], ovr: 79 },
      { name: 'Diego Tardelli', pos: ['ATA'], ovr: 80 },
      { name: 'Alex Silva', pos: ['ZAG'], ovr: 74 },
      { name: 'Souza', pos: ['MEI'], ovr: 79 },
      { name: 'Lucas', pos: ['PD'], ovr: 75 },
      { name: 'Pablo', pos: ['ZAG'], ovr: 73 },
      { name: 'Rodrigo', pos: ['LD'], ovr: 70 },
    ]},
  { id: 'sao-paulo2008', club: 'Sao Paulo', year: 2008, label: 'Sao Paulo 2008 (Tricampeonato)', coach: 'Muricy Ramalho',
    colors: { p: '#c8102e', s: '#000000' },
    players: [
      { name: 'Rogerio Ceni', pos: ['GOL'], ovr: 88 },
      { name: 'Ilsinho', pos: ['LD','PD'], ovr: 77 },
      { name: 'Fabao', pos: ['ZAG'], ovr: 80 },
      { name: 'Miranda', pos: ['ZAG'], ovr: 85 },
      { name: 'Lugano', pos: ['ZAG'], ovr: 84 },
      { name: 'Junior', pos: ['LE'], ovr: 76 },
      { name: 'Mineiro', pos: ['VOL'], ovr: 82 },
      { name: 'Josue', pos: ['VOL','MEI'], ovr: 80 },
      { name: 'Danilo', pos: ['MEI'], ovr: 80 },
      { name: 'Hernanes', pos: ['MEI'], ovr: 88 },
      { name: 'Borges', pos: ['ATA'], ovr: 80 },
      { name: 'Aloisio', pos: ['ATA'], ovr: 79 },
      { name: 'Diego Tardelli', pos: ['ATA'], ovr: 81 },
      { name: 'Grafite', pos: ['ATA'], ovr: 82 },
      { name: 'Alex Silva', pos: ['ZAG'], ovr: 74 },
      { name: 'Eder Luis', pos: ['ATA'], ovr: 74 },
      { name: 'Rafael', pos: ['ZAG'], ovr: 73 },
      { name: 'Jadson', pos: ['MEI'], ovr: 77 },
      { name: 'Junior Cesar', pos: ['LE'], ovr: 72 },
      { name: 'Souza', pos: ['MEI'], ovr: 79 },
    ]},
  { id: 'flamengo2009', club: 'Flamengo', year: 2009, label: 'Flamengo 2009 (Hexacampeonato)', coach: 'Andrade',
    colors: { p: '#c8102e', s: '#000000' },
    players: [
      { name: 'Bruno', pos: ['GOL'], ovr: 87 },
      { name: 'Leo Moura', pos: ['LD','PD'], ovr: 86 },
      { name: 'David Braz', pos: ['ZAG'], ovr: 80 },
      { name: 'Ronaldo Angelim', pos: ['ZAG'], ovr: 82 },
      { name: 'Juan', pos: ['ZAG'], ovr: 84 },
      { name: 'Gonzalez', pos: ['LE'], ovr: 79 },
      { name: 'Airton', pos: ['VOL'], ovr: 79 },
      { name: 'Willians', pos: ['VOL'], ovr: 80 },
      { name: 'Petkovic', pos: ['MEI'], ovr: 85 },
      { name: 'Adriano', pos: ['ATA'], ovr: 91 },
      { name: 'Obina', pos: ['ATA'], ovr: 80 },
      { name: 'Ze Roberto', pos: ['MEI','ATA'], ovr: 80 },
      { name: 'Kleberson', pos: ['VOL','MEI'], ovr: 81 },
      { name: 'Josiel', pos: ['PD'], ovr: 76 },
      { name: 'Everton', pos: ['ATA'], ovr: 78 },
      { name: 'Alvaro', pos: ['ZAG'], ovr: 78 },
      { name: 'Fierro', pos: ['MEI'], ovr: 75 },
      { name: 'Camacho', pos: ['ATA'], ovr: 72 },
      { name: 'Denis Marques', pos: ['ATA'], ovr: 72 },
      { name: 'Bruno Mezenga', pos: ['ATA'], ovr: 73 },
    ]},
  { id: 'santos2010', club: 'Santos', year: 2010, label: 'Santos 2010 (Copa do Brasil)', coach: 'Dorival Junior',
    colors: { p: '#000000', s: '#ffffff' },
    players: [
      { name: 'Rafael', pos: ['GOL'], ovr: 80 },
      { name: 'Danilo', pos: ['LD','PD'], ovr: 83 },
      { name: 'Edu Dracena', pos: ['ZAG'], ovr: 83 },
      { name: 'Durval', pos: ['ZAG'], ovr: 80 },
      { name: 'Leo', pos: ['LE'], ovr: 81 },
      { name: 'Adriano', pos: ['VOL'], ovr: 79 },
      { name: 'Arouca', pos: ['VOL','MEI'], ovr: 83 },
      { name: 'Elano', pos: ['MEI'], ovr: 87 },
      { name: 'Paulo Henrique Ganso', pos: ['MEI'], ovr: 88 },
      { name: 'Robinho', pos: ['PE','ATA'], ovr: 89 },
      { name: 'Neymar', pos: ['ATA','PE'], ovr: 93 },
      { name: 'Andre', pos: ['ATA'], ovr: 82 },
      { name: 'Ze Eduardo', pos: ['ATA'], ovr: 79 },
      { name: 'Alan Kardec', pos: ['ATA'], ovr: 78 },
      { name: 'Alan Patrick', pos: ['MEI'], ovr: 78 },
      { name: 'Alex Sandro', pos: ['LE'], ovr: 78 },
      { name: 'Wesley', pos: ['VOL'], ovr: 79 },
      { name: 'Bruno Rodrigo', pos: ['ZAG'], ovr: 79 },
      { name: 'Felipe', pos: ['GOL'], ovr: 75 },
      { name: 'Para', pos: ['LD'], ovr: 78 },
    ]},
  { id: 'fluminense2010', club: 'Fluminense', year: 2010, label: 'Fluminense 2010 (Tricampeonato)', coach: 'Muricy Ramalho',
    colors: { p: '#7a1e3c', s: '#006437' },
    players: [
      { name: 'Ricardo Berna', pos: ['GOL'], ovr: 82 },
      { name: 'Mariano', pos: ['LD'], ovr: 79 },
      { name: 'Gum', pos: ['ZAG'], ovr: 84 },
      { name: 'Leandro Euzebio', pos: ['ZAG'], ovr: 81 },
      { name: 'Carlinhos', pos: ['LE'], ovr: 82 },
      { name: 'Valencia', pos: ['VOL'], ovr: 80 },
      { name: 'Diguinho', pos: ['VOL'], ovr: 78 },
      { name: 'Conca', pos: ['MEI'], ovr: 91 },
      { name: 'Julio Cesar', pos: ['MEI','ATA'], ovr: 79 },
      { name: 'Emerson Sheik', pos: ['ATA','MEI'], ovr: 83 },
      { name: 'Fred', pos: ['ATA'], ovr: 87 },
      { name: 'Washington', pos: ['MEI'], ovr: 77 },
      { name: 'Rodriguinho', pos: ['ATA'], ovr: 74 },
      { name: 'Fernando Bob', pos: ['ATA'], ovr: 77 },
      { name: 'Edinho', pos: ['VOL','MEI'], ovr: 75 },
      { name: 'Diego Cavalieri', pos: ['GOL'], ovr: 78 },
      { name: 'Wagner', pos: ['MEI'], ovr: 75 },
      { name: 'Leandro', pos: ['LD'], ovr: 73 },
      { name: 'Rafael Sobis', pos: ['ATA'], ovr: 80 },
      { name: 'Samuel', pos: ['ATA'], ovr: 73 },
    ]},
  { id: 'santos2011', club: 'Santos', year: 2011, label: 'Santos 2011 (Libertadores)', coach: 'Adilson Batista',
    colors: { p: '#000000', s: '#ffffff' },
    players: [
      { name: 'Rafael', pos: ['GOL'], ovr: 82 },
      { name: 'Danilo', pos: ['LD','PD'], ovr: 85 },
      { name: 'Edu Dracena', pos: ['ZAG'], ovr: 84 },
      { name: 'Durval', pos: ['ZAG'], ovr: 78 },
      { name: 'Leo', pos: ['LE'], ovr: 82 },
      { name: 'Adriano', pos: ['VOL'], ovr: 79 },
      { name: 'Arouca', pos: ['VOL','MEI'], ovr: 84 },
      { name: 'Elano', pos: ['MEI'], ovr: 87 },
      { name: 'Paulo Henrique Ganso', pos: ['MEI'], ovr: 89 },
      { name: 'Neymar', pos: ['ATA','PE'], ovr: 95 },
      { name: 'Ze Eduardo', pos: ['ATA'], ovr: 80 },
      { name: 'Andre', pos: ['ATA'], ovr: 83 },
      { name: 'Robinho', pos: ['PE','ATA'], ovr: 87 },
      { name: 'Alex Sandro', pos: ['LE'], ovr: 80 },
      { name: 'Bruno Rodrigo', pos: ['ZAG'], ovr: 79 },
      { name: 'Jonathan', pos: ['LD'], ovr: 76 },
      { name: 'Alan Kardec', pos: ['ATA'], ovr: 78 },
      { name: 'Maikon Leite', pos: ['ATA','PD'], ovr: 78 },
      { name: 'Felipe', pos: ['GOL'], ovr: 77 },
      { name: 'Marquinhos', pos: ['VOL'], ovr: 78 },
    ]},
  { id: 'corinthians2011', club: 'Corinthians', year: 2011, label: 'Corinthians 2011 (Pentacampeonato)', coach: 'Tite',
    colors: { p: '#000000', s: '#ffffff' },
    players: [
      { name: 'Cassio', pos: ['GOL'], ovr: 87 },
      { name: 'Alessandro', pos: ['LD'], ovr: 80 },
      { name: 'Chicao', pos: ['ZAG'], ovr: 84 },
      { name: 'Leandro Castan', pos: ['ZAG'], ovr: 84 },
      { name: 'Fabio Santos', pos: ['LE'], ovr: 82 },
      { name: 'Ralf', pos: ['VOL'], ovr: 85 },
      { name: 'Paulinho', pos: ['VOL','MEI'], ovr: 88 },
      { name: 'Danilo', pos: ['MEI','PD'], ovr: 85 },
      { name: 'Alex', pos: ['MEI'], ovr: 85 },
      { name: 'Paolo Guerrero', pos: ['ATA'], ovr: 88 },
      { name: 'Emerson Sheik', pos: ['ATA','MEI'], ovr: 85 },
      { name: 'Jorge Henrique', pos: ['PD','ATA'], ovr: 80 },
      { name: 'Liedson', pos: ['ATA'], ovr: 82 },
      { name: 'Willian', pos: ['PD','MEI'], ovr: 84 },
      { name: 'Adriano', pos: ['ATA'], ovr: 80 },
      { name: 'Romarinho', pos: ['ATA'], ovr: 78 },
      { name: 'Paulo Andre', pos: ['ZAG'], ovr: 80 },
      { name: 'Julio Cesar', pos: ['GOL'], ovr: 80 },
      { name: 'Douglas', pos: ['MEI'], ovr: 74 },
      { name: 'Guilherme', pos: ['ATA'], ovr: 73 },
    ]},
  { id: 'fluminense2012', club: 'Fluminense', year: 2012, label: 'Fluminense 2012 (Tetracampeonato)', coach: 'Abel Braga',
    colors: { p: '#7a1e3c', s: '#006437' },
    players: [
      { name: 'Diego Cavalieri', pos: ['GOL'], ovr: 84 },
      { name: 'Bruno', pos: ['LD'], ovr: 81 },
      { name: 'Gum', pos: ['ZAG'], ovr: 85 },
      { name: 'Leandro Euzebio', pos: ['ZAG'], ovr: 82 },
      { name: 'Carlinhos', pos: ['LE'], ovr: 82 },
      { name: 'Edinho', pos: ['VOL','MEI'], ovr: 78 },
      { name: 'Jean', pos: ['VOL'], ovr: 79 },
      { name: 'Deco', pos: ['MEI'], ovr: 87 },
      { name: 'Thiago Neves', pos: ['MEI'], ovr: 88 },
      { name: 'Wellington Nem', pos: ['PD','MEI'], ovr: 83 },
      { name: 'Fred', pos: ['ATA'], ovr: 90 },
      { name: 'Rafael Sobis', pos: ['ATA'], ovr: 82 },
      { name: 'Rafael Moura', pos: ['ATA'], ovr: 79 },
      { name: 'Wagner', pos: ['MEI'], ovr: 76 },
      { name: 'Lanzini', pos: ['MEI'], ovr: 80 },
      { name: 'Michael', pos: ['MEI'], ovr: 74 },
      { name: 'Rodrigo Lindoso', pos: ['VOL'], ovr: 78 },
      { name: 'Samuel', pos: ['ATA'], ovr: 73 },
      { name: 'Martinuccio', pos: ['MEI'], ovr: 74 },
      { name: 'Anderson', pos: ['ZAG'], ovr: 78 },
    ]},
  { id: 'atletico-mg2013', club: 'Atletico-MG', year: 2013, label: 'Atletico-MG 2013 (Libertadores)', coach: 'Cuca',
    colors: { p: '#000000', s: '#ffffff' },
    players: [
      { name: 'Victor', pos: ['GOL'], ovr: 93 },
      { name: 'Marcos Rocha', pos: ['LD'], ovr: 83 },
      { name: 'Rever', pos: ['ZAG'], ovr: 84 },
      { name: 'Leonardo Silva', pos: ['ZAG'], ovr: 83 },
      { name: 'Junior Cesar', pos: ['LE'], ovr: 80 },
      { name: 'Richarlyson', pos: ['LE','VOL'], ovr: 82 },
      { name: 'Pierre', pos: ['VOL'], ovr: 85 },
      { name: 'Josue', pos: ['VOL','MEI'], ovr: 82 },
      { name: 'Ronaldinho Gaucho', pos: ['MEI'], ovr: 91 },
      { name: 'Diego Tardelli', pos: ['MEI','ATA'], ovr: 89 },
      { name: 'Bernard', pos: ['PD','MEI'], ovr: 88 },
      { name: 'Jo', pos: ['ATA'], ovr: 86 },
      { name: 'Guilherme', pos: ['ATA'], ovr: 81 },
      { name: 'Luan', pos: ['ATA','PE'], ovr: 82 },
      { name: 'Alecsandro', pos: ['ATA'], ovr: 79 },
      { name: 'Michel', pos: ['LD'], ovr: 80 },
      { name: 'Jemerson', pos: ['ZAG'], ovr: 80 },
      { name: 'Rafael Carioca', pos: ['VOL'], ovr: 79 },
      { name: 'Leandro Donizete', pos: ['MEI','VOL'], ovr: 83 },
      { name: 'Douglas Santos', pos: ['LE'], ovr: 77 },
    ]},
  { id: 'cruzeiro2013', club: 'Cruzeiro', year: 2013, label: 'Cruzeiro 2013 (Brasileiro)', coach: 'Marcelo Oliveira',
    colors: { p: '#1c3f94', s: '#ffffff' },
    players: [
      { name: 'Fabio', pos: ['GOL'], ovr: 87 },
      { name: 'Ceara', pos: ['LD'], ovr: 82 },
      { name: 'Bruno Rodrigo', pos: ['ZAG'], ovr: 81 },
      { name: 'Dede', pos: ['ZAG'], ovr: 88 },
      { name: 'Egidio', pos: ['LE'], ovr: 80 },
      { name: 'Lucas Silva', pos: ['VOL'], ovr: 83 },
      { name: 'Nilton', pos: ['VOL'], ovr: 84 },
      { name: 'Everton Ribeiro', pos: ['MEI','PD'], ovr: 91 },
      { name: 'Ricardo Goulart', pos: ['MEI','ATA'], ovr: 88 },
      { name: 'Borges', pos: ['ATA'], ovr: 81 },
      { name: 'Marcelo Moreno', pos: ['ATA'], ovr: 83 },
      { name: 'Mayke', pos: ['LD'], ovr: 78 },
      { name: 'Leo', pos: ['ZAG'], ovr: 79 },
      { name: 'Willian', pos: ['ATA','PE'], ovr: 84 },
      { name: 'Julio Baptista', pos: ['MEI'], ovr: 79 },
      { name: 'Diego Souza', pos: ['MEI'], ovr: 80 },
      { name: 'Dagoberto', pos: ['ATA'], ovr: 75 },
      { name: 'Rafael', pos: ['GOL'], ovr: 75 },
      { name: 'Cris', pos: ['ZAG'], ovr: 78 },
      { name: 'Samudio', pos: ['LE'], ovr: 73 },
    ]},
  { id: 'cruzeiro2014', club: 'Cruzeiro', year: 2014, label: 'Cruzeiro 2014 (Tetracampeonato)', coach: 'Marcelo Oliveira',
    colors: { p: '#1c3f94', s: '#ffffff' },
    players: [
      { name: 'Fabio', pos: ['GOL'], ovr: 87 },
      { name: 'Ceara', pos: ['LD'], ovr: 82 },
      { name: 'Dede', pos: ['ZAG'], ovr: 90 },
      { name: 'Bruno Rodrigo', pos: ['ZAG'], ovr: 81 },
      { name: 'Egidio', pos: ['LE'], ovr: 81 },
      { name: 'Lucas Silva', pos: ['VOL'], ovr: 84 },
      { name: 'Henrique', pos: ['VOL'], ovr: 81 },
      { name: 'Nilton', pos: ['VOL'], ovr: 83 },
      { name: 'Everton Ribeiro', pos: ['MEI','PD'], ovr: 90 },
      { name: 'Ricardo Goulart', pos: ['MEI','ATA'], ovr: 89 },
      { name: 'Marcelo Moreno', pos: ['ATA'], ovr: 85 },
      { name: 'Willian', pos: ['ATA','PE'], ovr: 83 },
      { name: 'Borges', pos: ['ATA'], ovr: 79 },
      { name: 'Dagoberto', pos: ['ATA'], ovr: 74 },
      { name: 'Luan', pos: ['ATA'], ovr: 76 },
      { name: 'Mayke', pos: ['LD'], ovr: 80 },
      { name: 'Leo', pos: ['ZAG'], ovr: 80 },
      { name: 'Elisson', pos: ['GOL'], ovr: 73 },
      { name: 'Manoel', pos: ['ZAG'], ovr: 78 },
      { name: 'Bruno Ramires', pos: ['VOL'], ovr: 79 },
    ]},
  { id: 'corinthians2015', club: 'Corinthians', year: 2015, label: 'Corinthians 2015 (Hexacampeonato)', coach: 'Tite',
    colors: { p: '#000000', s: '#ffffff' },
    players: [
      { name: 'Cassio', pos: ['GOL'], ovr: 89 },
      { name: 'Fagner', pos: ['LD'], ovr: 82 },
      { name: 'Gil Baiano', pos: ['ZAG'], ovr: 87 },
      { name: 'Edu Dracena', pos: ['ZAG'], ovr: 84 },
      { name: 'Guilherme Arana', pos: ['LE'], ovr: 83 },
      { name: 'Ralf', pos: ['VOL'], ovr: 85 },
      { name: 'Elias', pos: ['VOL','MEI'], ovr: 84 },
      { name: 'Renato Augusto', pos: ['MEI'], ovr: 86 },
      { name: 'Jadson', pos: ['MEI'], ovr: 88 },
      { name: 'Roberto Firmino', pos: ['ATA','MEI'], ovr: 85 },
      { name: 'Malcom', pos: ['PD','ATA'], ovr: 82 },
      { name: 'Alessandro', pos: ['LD'], ovr: 78 },
      { name: 'Chicao', pos: ['ZAG'], ovr: 82 },
      { name: 'Rodriguinho', pos: ['MEI'], ovr: 83 },
      { name: 'Willian Arao', pos: ['VOL'], ovr: 80 },
      { name: 'Petros', pos: ['VOL'], ovr: 77 },
      { name: 'Lucca', pos: ['ATA'], ovr: 73 },
      { name: 'Luciano', pos: ['ATA'], ovr: 79 },
      { name: 'Danilo Avelar', pos: ['LE'], ovr: 77 },
      { name: 'Uendel', pos: ['LE'], ovr: 78 },
    ]},
  { id: 'palmeiras2016', club: 'Palmeiras', year: 2016, label: 'Palmeiras 2016', coach: 'Cuca',
    colors: { p: '#006437', s: '#ffffff' },
    players: [
      { name: 'Fernando Prass', pos: ['GOL'], ovr: 84 },
      { name: 'Marcos Rocha', pos: ['LD'], ovr: 82 },
      { name: 'Edu Dracena', pos: ['ZAG'], ovr: 83 },
      { name: 'Mina', pos: ['ZAG'], ovr: 84 },
      { name: 'Egidio', pos: ['LE'], ovr: 81 },
      { name: 'Arouca', pos: ['VOL'], ovr: 83 },
      { name: 'Felipe Melo', pos: ['VOL'], ovr: 87 },
      { name: 'Thiago Santos', pos: ['VOL'], ovr: 79 },
      { name: 'Allione', pos: ['MEI','PD'], ovr: 82 },
      { name: 'Dudu', pos: ['PD','ATA'], ovr: 88 },
      { name: 'Gabriel Jesus', pos: ['ATA'], ovr: 91 },
      { name: 'Cleiton Xavier', pos: ['MEI'], ovr: 79 },
      { name: 'Tche Tche', pos: ['MEI','VOL'], ovr: 80 },
      { name: 'Rafael Marques', pos: ['ATA'], ovr: 77 },
      { name: 'Willian', pos: ['ATA','PE'], ovr: 78 },
      { name: 'Mauricio Ramos', pos: ['ZAG'], ovr: 76 },
      { name: 'Jean', pos: ['LD'], ovr: 78 },
      { name: 'Thiago Martins', pos: ['ZAG'], ovr: 79 },
      { name: 'Raphael Veiga', pos: ['MEI'], ovr: 80 },
      { name: 'Roger Guedes', pos: ['ATA','PE'], ovr: 80 },
    ]},
  { id: 'corinthians2017', club: 'Corinthians', year: 2017, label: 'Corinthians 2017 (Heptacampeonato)', coach: 'Fabio Carille',
    colors: { p: '#000000', s: '#ffffff' },
    players: [
      { name: 'Cassio', pos: ['GOL'], ovr: 90 },
      { name: 'Fagner', pos: ['LD'], ovr: 85 },
      { name: 'Pablo', pos: ['ZAG'], ovr: 82 },
      { name: 'Balbuena', pos: ['ZAG'], ovr: 84 },
      { name: 'Guilherme Arana', pos: ['LE'], ovr: 83 },
      { name: 'Ralf', pos: ['VOL'], ovr: 84 },
      { name: 'Maycon', pos: ['VOL'], ovr: 85 },
      { name: 'Jadson', pos: ['MEI'], ovr: 89 },
      { name: 'Marlone', pos: ['MEI'], ovr: 82 },
      { name: 'Jo', pos: ['ATA'], ovr: 87 },
      { name: 'Romero', pos: ['PD','ATA'], ovr: 82 },
      { name: 'Malcom', pos: ['PD','ATA'], ovr: 84 },
      { name: 'Marquinhos Gabriel', pos: ['PD'], ovr: 80 },
      { name: 'Rodriguinho', pos: ['MEI'], ovr: 84 },
      { name: 'Kazim', pos: ['ATA'], ovr: 73 },
      { name: 'Leo Santos', pos: ['ZAG'], ovr: 78 },
      { name: 'Camacho', pos: ['MEI'], ovr: 74 },
      { name: 'Mendoza', pos: ['PD'], ovr: 74 },
      { name: 'Carlos', pos: ['LD'], ovr: 71 },
      { name: 'Jo (reserva)', pos: ['ATA'], ovr: 75 },
    ]},
  { id: 'palmeiras2018', club: 'Palmeiras', year: 2018, label: 'Palmeiras 2018 (80 pontos recorde)', coach: 'Luiz Felipe Scolari',
    colors: { p: '#006437', s: '#ffffff' },
    players: [
      { name: 'Weverton', pos: ['GOL'], ovr: 89 },
      { name: 'Marcos Rocha', pos: ['LD'], ovr: 84 },
      { name: 'Gustavo Gomez', pos: ['ZAG'], ovr: 88 },
      { name: 'Luan', pos: ['ZAG'], ovr: 83 },
      { name: 'Diogo Barbosa', pos: ['LE'], ovr: 82 },
      { name: 'Felipe Melo', pos: ['VOL'], ovr: 88 },
      { name: 'Bruno Henrique', pos: ['VOL'], ovr: 84 },
      { name: 'Ze Rafael', pos: ['VOL','MEI'], ovr: 83 },
      { name: 'Hyoran', pos: ['MEI','PD'], ovr: 80 },
      { name: 'Dudu', pos: ['PD','ATA'], ovr: 92 },
      { name: 'Borja', pos: ['ATA'], ovr: 81 },
      { name: 'Lucas Lima', pos: ['MEI'], ovr: 82 },
      { name: 'Willian', pos: ['ATA','PE'], ovr: 82 },
      { name: 'Deyverson', pos: ['ATA'], ovr: 80 },
      { name: 'Moises', pos: ['VOL','LE'], ovr: 79 },
      { name: 'Mayke', pos: ['LD'], ovr: 80 },
      { name: 'Edu Dracena', pos: ['ZAG'], ovr: 82 },
      { name: 'Thiago Santos', pos: ['VOL'], ovr: 78 },
      { name: 'Rafael Marques', pos: ['ATA'], ovr: 76 },
      { name: 'Raphael Veiga', pos: ['MEI'], ovr: 80 },
    ]},
  { id: 'athletico-pr2019', club: 'Athletico-PR', year: 2019, label: 'Athletico-PR 2019 (Copa do Brasil)', coach: 'Tiago Nunes',
    colors: { p: '#c8102e', s: '#000000' },
    players: [
      { name: 'Santos', pos: ['GOL'], ovr: 82 },
      { name: 'Marcio Azevedo', pos: ['LD'], ovr: 79 },
      { name: 'Pedro Henrique', pos: ['ZAG'], ovr: 80 },
      { name: 'Thiago Heleno', pos: ['ZAG'], ovr: 82 },
      { name: 'Leo Pereira', pos: ['LE'], ovr: 80 },
      { name: 'Christian', pos: ['VOL'], ovr: 83 },
      { name: 'Matheus Fernandes', pos: ['VOL'], ovr: 82 },
      { name: 'Bruno Guimaraes', pos: ['VOL','MEI'], ovr: 86 },
      { name: 'Nikao', pos: ['MEI','PD'], ovr: 88 },
      { name: 'Rony', pos: ['PD','ATA'], ovr: 86 },
      { name: 'Marco Ruben', pos: ['ATA'], ovr: 81 },
      { name: 'Jonathan', pos: ['GOL'], ovr: 75 },
      { name: 'Robson Bambu', pos: ['ZAG'], ovr: 79 },
      { name: 'Abner', pos: ['LE'], ovr: 77 },
      { name: 'Lucho Gonzalez', pos: ['MEI'], ovr: 83 },
      { name: 'Marcelo Cirino', pos: ['PE'], ovr: 81 },
      { name: 'Wellington', pos: ['VOL'], ovr: 79 },
      { name: 'Jonathan Rios', pos: ['LD'], ovr: 78 },
      { name: 'Vitinho', pos: ['PD'], ovr: 80 },
      { name: 'Marcinho', pos: ['LD'], ovr: 76 },
    ]},
  { id: 'flamengo2019', club: 'Flamengo', year: 2019, label: 'Flamengo 2019 (Bicampeonato + Libertadores)', coach: 'Jorge Jesus',
    colors: { p: '#c8102e', s: '#000000' },
    players: [
      { name: 'Diego Alves', pos: ['GOL'], ovr: 87 },
      { name: 'Rafinha', pos: ['LD'], ovr: 86 },
      { name: 'Rodrigo Caio', pos: ['ZAG'], ovr: 86 },
      { name: 'Pablo Mari', pos: ['ZAG'], ovr: 85 },
      { name: 'Filipe Luis', pos: ['LE'], ovr: 91 },
      { name: 'Willian Arao', pos: ['VOL'], ovr: 88 },
      { name: 'Gerson', pos: ['MEI','VOL'], ovr: 90 },
      { name: 'Everton Ribeiro', pos: ['MEI','PD'], ovr: 91 },
      { name: 'Arrascaeta', pos: ['MEI'], ovr: 92 },
      { name: 'Bruno Henrique', pos: ['PE','ATA'], ovr: 90 },
      { name: 'Gabigol', pos: ['ATA'], ovr: 97 },
      { name: 'Pedro', pos: ['ATA'], ovr: 88 },
      { name: 'Diego', pos: ['MEI'], ovr: 84 },
      { name: 'Cuellar', pos: ['VOL'], ovr: 85 },
      { name: 'Rodinei', pos: ['LD'], ovr: 82 },
      { name: 'Reinier', pos: ['MEI'], ovr: 82 },
      { name: 'Michael', pos: ['ATA','PD'], ovr: 82 },
      { name: 'Thiago Maia', pos: ['VOL'], ovr: 83 },
      { name: 'Lincoln', pos: ['ATA'], ovr: 79 },
      { name: 'Leo Ortiz', pos: ['ZAG'], ovr: 80 },
    ]},
  { id: 'flamengo2020', club: 'Flamengo', year: 2020, label: 'Flamengo 2020 (Bicampeonato)', coach: 'Rogerio Ceni',
    colors: { p: '#c8102e', s: '#000000' },
    players: [
      { name: 'Diego Alves', pos: ['GOL'], ovr: 86 },
      { name: 'Rafinha', pos: ['LD'], ovr: 84 },
      { name: 'Rodrigo Caio', pos: ['ZAG'], ovr: 87 },
      { name: 'Leo Pereira', pos: ['ZAG'], ovr: 84 },
      { name: 'Filipe Luis', pos: ['LE'], ovr: 89 },
      { name: 'Willian Arao', pos: ['VOL'], ovr: 88 },
      { name: 'Gerson', pos: ['MEI','VOL'], ovr: 90 },
      { name: 'Everton Ribeiro', pos: ['MEI','PD'], ovr: 91 },
      { name: 'Arrascaeta', pos: ['MEI'], ovr: 91 },
      { name: 'Bruno Henrique', pos: ['PE','ATA'], ovr: 89 },
      { name: 'Gabigol', pos: ['ATA'], ovr: 96 },
      { name: 'Pedro', pos: ['ATA'], ovr: 90 },
      { name: 'Thiago Maia', pos: ['VOL'], ovr: 84 },
      { name: 'Michael', pos: ['ATA','PD'], ovr: 83 },
      { name: 'Rodinei', pos: ['LD'], ovr: 82 },
      { name: 'Diego', pos: ['MEI'], ovr: 82 },
      { name: 'Vitinho', pos: ['PD'], ovr: 81 },
      { name: 'Hugo Souza', pos: ['GOL'], ovr: 76 },
      { name: 'Rene', pos: ['LE'], ovr: 82 },
      { name: 'Leo Ortiz', pos: ['ZAG'], ovr: 80 },
    ]},
  { id: 'atletico-mg2021', club: 'Atletico-MG', year: 2021, label: 'Atletico-MG 2021 (Brasileiro + Copa do Brasil)', coach: 'Cuca',
    colors: { p: '#000000', s: '#ffffff' },
    players: [
      { name: 'Everson', pos: ['GOL'], ovr: 88 },
      { name: 'Marcos Rocha', pos: ['LD'], ovr: 83 },
      { name: 'Rever', pos: ['ZAG'], ovr: 82 },
      { name: 'Nathan Silva', pos: ['ZAG'], ovr: 85 },
      { name: 'Guilherme Arana', pos: ['LE'], ovr: 88 },
      { name: 'Allan', pos: ['VOL','MEI'], ovr: 86 },
      { name: 'Jair', pos: ['VOL'], ovr: 83 },
      { name: 'Zaracho', pos: ['MEI'], ovr: 87 },
      { name: 'Nacho Fernandez', pos: ['MEI'], ovr: 90 },
      { name: 'Keno', pos: ['ATA','PE'], ovr: 85 },
      { name: 'Hulk', pos: ['ATA'], ovr: 94 },
      { name: 'Vargas', pos: ['MEI','PE'], ovr: 84 },
      { name: 'Savarino', pos: ['PE'], ovr: 82 },
      { name: 'Eduardo Sasha', pos: ['ATA'], ovr: 82 },
      { name: 'Tardelli', pos: ['ATA'], ovr: 79 },
      { name: 'Alisson', pos: ['ZAG','LD'], ovr: 83 },
      { name: 'Guga', pos: ['LD'], ovr: 80 },
      { name: 'Igor Gomes', pos: ['MEI'], ovr: 78 },
      { name: 'Hyoran', pos: ['MEI'], ovr: 79 },
      { name: 'Rabelo', pos: ['VOL'], ovr: 76 },
    ]},
  { id: 'palmeiras2022', club: 'Palmeiras', year: 2022, label: 'Palmeiras 2022 (81 pontos RECORDE historico)', coach: 'Abel Ferreira',
    colors: { p: '#006437', s: '#ffffff' },
    players: [
      { name: 'Weverton', pos: ['GOL'], ovr: 92 },
      { name: 'Marcos Rocha', pos: ['LD'], ovr: 84 },
      { name: 'Gustavo Gomez', pos: ['ZAG'], ovr: 90 },
      { name: 'Murilo', pos: ['ZAG'], ovr: 87 },
      { name: 'Piquerez', pos: ['LE'], ovr: 89 },
      { name: 'Danilo', pos: ['VOL','MEI'], ovr: 88 },
      { name: 'Ze Rafael', pos: ['VOL'], ovr: 86 },
      { name: 'Atuesta', pos: ['VOL'], ovr: 81 },
      { name: 'Raphael Veiga', pos: ['MEI','ATA'], ovr: 90 },
      { name: 'Dudu', pos: ['PD','ATA'], ovr: 88 },
      { name: 'Flaco Lopez', pos: ['ATA'], ovr: 86 },
      { name: 'Rony', pos: ['PE','ATA'], ovr: 85 },
      { name: 'Endrick', pos: ['ATA'], ovr: 91 },
      { name: 'Mayke', pos: ['LD'], ovr: 81 },
      { name: 'Gabriel Menino', pos: ['VOL'], ovr: 82 },
      { name: 'Luan', pos: ['ZAG'], ovr: 80 },
      { name: 'Vanderlan', pos: ['LE'], ovr: 78 },
      { name: 'Pedro Geromel', pos: ['ZAG'], ovr: 79 },
      { name: 'Jose Manuel Lopez', pos: ['ATA'], ovr: 75 },
      { name: 'Jhon Jhon', pos: ['MEI'], ovr: 79 },
    ]},
  { id: 'athletico-pr2022', club: 'Athletico-PR', year: 2022, label: 'Athletico-PR 2022 (Finalista Libertadores)', coach: 'Luiz Felipe Scolari',
    colors: { p: '#c8102e', s: '#000000' },
    players: [
      { name: 'Bento', pos: ['GOL'], ovr: 87 },
      { name: 'Orejuela', pos: ['LD'], ovr: 80 },
      { name: 'Pedro Henrique', pos: ['ZAG'], ovr: 83 },
      { name: 'Thiago Heleno', pos: ['ZAG'], ovr: 82 },
      { name: 'Abner', pos: ['LE'], ovr: 83 },
      { name: 'Christian', pos: ['VOL'], ovr: 84 },
      { name: 'Matheus Fernandes', pos: ['VOL'], ovr: 83 },
      { name: 'Erick', pos: ['VOL'], ovr: 82 },
      { name: 'Fernandinho', pos: ['VOL','MEI'], ovr: 90 },
      { name: 'David Terans', pos: ['MEI'], ovr: 86 },
      { name: 'Canobbio', pos: ['PD','MEI'], ovr: 84 },
      { name: 'Romulo', pos: ['ATA'], ovr: 83 },
      { name: 'Pablo', pos: ['ATA'], ovr: 82 },
      { name: 'Vitor Roque', pos: ['ATA'], ovr: 87 },
      { name: 'Vitinho', pos: ['PD'], ovr: 82 },
      { name: 'Ze Ivaldo', pos: ['ZAG'], ovr: 82 },
      { name: 'Anderson', pos: ['GOL'], ovr: 79 },
      { name: 'Matheus Felipe', pos: ['ZAG'], ovr: 81 },
      { name: 'Pedrinho', pos: ['LE'], ovr: 81 },
      { name: 'Khellven', pos: ['LD'], ovr: 79 },
    ]},
  { id: 'palmeiras2023', club: 'Palmeiras', year: 2023, label: 'Palmeiras 2023 (Tricampeonato com Abel)', coach: 'Abel Ferreira',
    colors: { p: '#006437', s: '#ffffff' },
    players: [
      { name: 'Weverton', pos: ['GOL'], ovr: 91 },
      { name: 'Marcos Rocha', pos: ['LD'], ovr: 83 },
      { name: 'Gustavo Gomez', pos: ['ZAG'], ovr: 91 },
      { name: 'Murilo', pos: ['ZAG'], ovr: 88 },
      { name: 'Piquerez', pos: ['LE'], ovr: 89 },
      { name: 'Danilo', pos: ['VOL','MEI'], ovr: 88 },
      { name: 'Ze Rafael', pos: ['VOL'], ovr: 85 },
      { name: 'Gabriel Menino', pos: ['VOL'], ovr: 83 },
      { name: 'Raphael Veiga', pos: ['MEI','ATA'], ovr: 92 },
      { name: 'Estevao', pos: ['PD','MEI'], ovr: 89 },
      { name: 'Flaco Lopez', pos: ['ATA'], ovr: 90 },
      { name: 'Dudu', pos: ['PD','ATA'], ovr: 87 },
      { name: 'Rony', pos: ['PE','ATA'], ovr: 84 },
      { name: 'Endrick', pos: ['ATA'], ovr: 93 },
      { name: 'Mayke', pos: ['LD'], ovr: 80 },
      { name: 'Vanderlan', pos: ['LE'], ovr: 79 },
      { name: 'Atuesta', pos: ['VOL'], ovr: 80 },
      { name: 'Jhon Jhon', pos: ['MEI'], ovr: 82 },
      { name: 'Artur', pos: ['PD'], ovr: 78 },
      { name: 'Lopes', pos: ['ATA'], ovr: 75 },
    ]},
  { id: 'botafogo2024', club: 'Botafogo', year: 2024, label: 'Botafogo 2024 (Tricampeonato + Libertadores)', coach: 'Artur Jorge',
    colors: { p: '#000000', s: '#ffffff' },
    players: [
      { name: 'John', pos: ['GOL'], ovr: 87 },
      { name: 'Vitinho', pos: ['LD'], ovr: 84 },
      { name: 'Alexander Barboza', pos: ['ZAG'], ovr: 87 },
      { name: 'Adryelson', pos: ['ZAG'], ovr: 85 },
      { name: 'Cuiabano', pos: ['LE'], ovr: 83 },
      { name: 'Marlon Freitas', pos: ['VOL'], ovr: 88 },
      { name: 'Gregore', pos: ['VOL'], ovr: 83 },
      { name: 'Thiago Almada', pos: ['MEI'], ovr: 93 },
      { name: 'Savarino', pos: ['MEI','PE'], ovr: 87 },
      { name: 'Luiz Henrique', pos: ['PE','ATA'], ovr: 90 },
      { name: 'Igor Jesus', pos: ['ATA'], ovr: 93 },
      { name: 'Matheus Martins', pos: ['ATA'], ovr: 84 },
      { name: 'Eduardo Sasha', pos: ['ATA'], ovr: 82 },
      { name: 'Tiquinho Soares', pos: ['ATA'], ovr: 86 },
      { name: 'Alex Telles', pos: ['LE'], ovr: 84 },
      { name: 'Artur', pos: ['PD'], ovr: 81 },
      { name: 'Gabriel Pires', pos: ['VOL'], ovr: 79 },
      { name: 'Gatito Fernandez', pos: ['GOL'], ovr: 82 },
      { name: 'Rafael', pos: ['LD'], ovr: 80 },
      { name: 'Yarlen', pos: ['ATA'], ovr: 80 },
    ]},
  { id: 'santos2015', club: 'Santos', year: 2015, label: 'Santos 2015 (Paulistao + Vice Copa BR)', coach: 'Dorival Junior',
    colors: { p: '#000000', s: '#ffffff' },
    players: [
      { name: 'Vanderlei', pos: ['GOL'], ovr: 84 },
      { name: 'Victor Ferraz', pos: ['LD'], ovr: 80 },
      { name: 'David Braz', pos: ['ZAG'], ovr: 83 },
      { name: 'Gustavo Henrique', pos: ['ZAG'], ovr: 82 },
      { name: 'Zeca', pos: ['LE'], ovr: 80 },
      { name: 'Renato', pos: ['VOL'], ovr: 82 },
      { name: 'Thiago Maia', pos: ['VOL'], ovr: 85 },
      { name: 'Lucas Lima', pos: ['MEI'], ovr: 87 },
      { name: 'Marquinhos Gabriel', pos: ['PD','ATA'], ovr: 82 },
      { name: 'Ricardo Oliveira', pos: ['ATA'], ovr: 90 },
      { name: 'Gabigol', pos: ['ATA','PD'], ovr: 85 },
      { name: 'Vladimir', pos: ['GOL'], ovr: 79 },
      { name: 'Daniel Guedes', pos: ['LD'], ovr: 75 },
      { name: 'Luiz Felipe', pos: ['ZAG'], ovr: 79 },
      { name: 'Werley', pos: ['ZAG'], ovr: 76 },
      { name: 'Geuvânio', pos: ['PE','ATA'], ovr: 80 },
      { name: 'Robinho', pos: ['ATA','PE'], ovr: 81 },
      { name: 'Elano', pos: ['MEI'], ovr: 79 },
      { name: 'Leo Cittadini', pos: ['MEI'], ovr: 77 },
      { name: 'Alison', pos: ['VOL'], ovr: 77 },
    ]},
  { id: 'santos2020', club: 'Santos', year: 2020, label: 'Santos 2020 (Vici-Campeão da Libertadores)', coach: 'Cuca',
    colors: { p: '#000000', s: '#ffffff' },
    players: [
      { name: 'John', pos: ['GOL'], ovr: 85 },
      { name: 'Para', pos: ['LD'], ovr: 81 },
      { name: 'Lucas Verissimo', pos: ['ZAG'], ovr: 87 },
      { name: 'Luan Peres', pos: ['ZAG'], ovr: 85 },
      { name: 'Felipe Jonatan', pos: ['LE'], ovr: 82 },
      { name: 'Alison', pos: ['VOL'], ovr: 82 },
      { name: 'Diego Pituca', pos: ['MEI','VOL'], ovr: 84 },
      { name: 'Sandry', pos: ['MEI'], ovr: 81 },
      { name: 'Soteldo', pos: ['PE','MEI'], ovr: 87 },
      { name: 'Marinho', pos: ['ATA','PD'], ovr: 89 },
      { name: 'Kaio Jorge', pos: ['ATA'], ovr: 85 },
      { name: 'Joao Paulo', pos: ['GOL','PD'], ovr: 85 },
      { name: 'Luiz Felile', pos: ['ZAG'], ovr: 77 },
      { name: 'Lucas Braga', pos: ['PE','ATA'], ovr: 83 },
      { name: 'Jean Mota', pos: ['MEI','MD'], ovr: 79 },
      { name: 'Madson', pos: ['LD'], ovr: 78 },
      { name: 'Arthur Gomes', pos: ['PD','MD'], ovr: 79 },
      { name: 'Vinicius Balieiro', pos: ['MEI'], ovr: 76 },
      { name: 'Carlos Sanchez', pos: ['MEI','MD'], ovr: 83 },
      { name: 'Marcos Leonardo', pos: ['ATA'], ovr: 77 },
    ]},
  { id: 'botafogo2023', club: 'Botafogo', year: 2023, label: 'Botafogo 2023 (Deixou escapar)', coach: 'Luis Castro',
    colors: { p: '#000000', s: '#ffffff' },
    players: [
      { name: 'Lucas Perri', pos: ['GOL'], ovr: 85 },
      { name: 'Saravia', pos: ['LD'], ovr: 82 },
      { name: 'Adryelson', pos: ['ZAG'], ovr: 83 },
      { name: 'Victor Cuesta', pos: ['ZAG'], ovr: 82 },
      { name: 'Marcal', pos: ['LE'], ovr: 80 },
      { name: 'Eduardo', pos: ['VOL'], ovr: 83 },
      { name: 'Marlon Freitas', pos: ['VOL'], ovr: 84 },
      { name: 'Tche Tche', pos: ['MEI','VOL'], ovr: 83 },
      { name: 'Gustavo Sauer', pos: ['PD'], ovr: 83 },
      { name: 'Tiquinho Soares', pos: ['ATA'], ovr: 89 },
      { name: 'Jeffinho', pos: ['PE','ATA'], ovr: 84 },
      { name: 'Diego Hernandez', pos: ['MEI'], ovr: 80 },
      { name: 'Hugo', pos: ['GOL'], ovr: 78 },
      { name: 'Rafael', pos: ['LD'], ovr: 79 },
      { name: 'Kayque', pos: ['VOL'], ovr: 80 },
      { name: 'Oscar Romero', pos: ['MEI'], ovr: 82 },
      { name: 'Diego Costa', pos: ['ATA'], ovr: 79 },
      { name: 'Patrick de Paula', pos: ['VOL'], ovr: 82 },
      { name: 'Victor Sa', pos: ['ATA'], ovr: 82 },
      { name: 'Niko Kuhnel', pos: ['MEI'], ovr: 76 },
    ]},
];

