const TEAMS = [
  { id: 'bahia1959', club: 'Bahia', year: 1959, label: 'Bahia 1959 (1o Campeonato Nacional)', coach: 'Carlos Volante',
    colors: { p: '#003399', s: '#ffffff' },
    players: [
      { name: 'Nadinho', pos: ['GOL'], ovr: 85 },
      { name: 'Leone', pos: ['LD','ZAG'], ovr: 82 },
      { name: 'Henrique', pos: ['ZAG'], ovr: 84 },
      { name: 'Nenzinho', pos: ['LE','ZAG'], ovr: 81 },
      { name: 'Hermínio', pos: ['ZAG'], ovr: 78 },
      { name: 'Flávio', pos: ['VOL','MC'], ovr: 83 },
      { name: 'Vicente', pos: ['VOL','MC'], ovr: 84 },
      { name: 'Mário', pos: ['MEI','MC'], ovr: 80 },
      { name: 'Léo Briglia', pos: ['ATA'], ovr: 88 },
      { name: 'Alencar', pos: ['ATA'], ovr: 85 },
      { name: 'Marito', pos: ['PD','MD'], ovr: 86 },
      { name: 'Florisvaldo', pos: ['LD','ZAG'], ovr: 76 },
      { name: 'Bacamarte', pos: ['ZAG'], ovr: 75 },
      { name: 'Beto', pos: ['MC','VOL'], ovr: 81 },
      { name: 'Bombeiro', pos: ['MC','MD'], ovr: 78 },
      { name: 'Ari', pos: ['MEI','MD'], ovr: 77 },
      { name: 'Biriba', pos: ['PE','ME'], ovr: 84 },
      { name: 'Carioca', pos: ['ATA','PD'], ovr: 76 },
      { name: 'Careca', pos: ['ATA'], ovr: 75 },
      { name: 'Jair', pos: ['GOL'], ovr: 74 },
    ]},
  { id: 'santos1961', club: 'Santos', year: 1961, label: 'Santos 1961 (Taca Brasil)', coach: 'Lula',
    colors: { p: '#000000', s: '#ffffff' },
    players: [
      { name: 'Gylmar', pos: ['GOL'], ovr: 86 },
      { name: 'Lima', pos: ['LD','VOL'], ovr: 82 },
      { name: 'Mauro', pos: ['ZAG'], ovr: 85 },
      { name: 'Calvet', pos: ['ZAG'], ovr: 81 },
      { name: 'Dalmo', pos: ['LE','ZAG'], ovr: 80 },
      { name: 'Zito', pos: ['VOL','MEI'], ovr: 88 },
      { name: 'Mengalvio', pos: ['VOL','MEI'], ovr: 84 },
      { name: 'Dorval', pos: ['PD','ATA'], ovr: 83 },
      { name: 'Coutinho', pos: ['GOL'], ovr: 90 },
      { name: 'Pele', pos: ['ATA','MEI'], ovr: 99 },
      { name: 'Pepe', pos: ['PE','ATA'], ovr: 89 },
      { name: 'Laercio', pos: ['GOL'], ovr: 76 },
      { name: 'Fioti', pos: ['LD'], ovr: 75 },
      { name: 'Formiga', pos: ['ZAG','VOL'], ovr: 78 },
      { name: 'Getulio', pos: ['LE'], ovr: 74 },
      { name: 'Pagao', pos: ['GOL'], ovr: 80 },
      { name: 'Tite', pos: ['PE'], ovr: 77 },
      { name: 'Sormani', pos: ['PD'], ovr: 76 },
      { name: 'Brandao', pos: ['VOL'], ovr: 73 },
      { name: 'Nene', pos: ['MEI'], ovr: 75 },
    ]},
  { id: 'santos1962', club: 'Santos', year: 1962, label: 'Santos 1962 (Libertadores + Mundial + Taca Brasil)', coach: 'Lula',
    colors: { p: '#000000', s: '#ffffff' },
    players: [
      { name: 'Gylmar', pos: ['GOL'], ovr: 90 },
      { name: 'Lima', pos: ['LD','VOL'], ovr: 84 },
      { name: 'Mauro', pos: ['ZAG'], ovr: 87 },
      { name: 'Calvet', pos: ['ZAG'], ovr: 83 },
      { name: 'Dalmo', pos: ['LE'], ovr: 81 },
      { name: 'Zito', pos: ['VOL','MEI'], ovr: 91 },
      { name: 'Mengalvio', pos: ['VOL','MEI'], ovr: 86 },
      { name: 'Dorval', pos: ['PD','ATA'], ovr: 85 },
      { name: 'Coutinho', pos: ['GOL'], ovr: 92 },
      { name: 'Pele', pos: ['ATA','MEI'], ovr: 99 },
      { name: 'Pepe', pos: ['PE','ATA'], ovr: 91 },
      { name: 'Laercio', pos: ['GOL'], ovr: 76 },
      { name: 'Ismael', pos: ['LD','ZAG'], ovr: 76 },
      { name: 'Formiga', pos: ['ZAG','VOL'], ovr: 77 },
      { name: 'Decio Brito', pos: ['LE'], ovr: 74 },
      { name: 'Tite', pos: ['PE','ME'], ovr: 76 },
      { name: 'Pagao', pos: ['GOL'], ovr: 80 },
      { name: 'Toninho Guerreiro', pos: ['GOL'], ovr: 77 },
      { name: 'Oswaldo', pos: ['PD','ATA'], ovr: 74 },
      { name: 'Bibe', pos: ['MEI'], ovr: 73 },
    ]},
  { id: 'botafogo1968', club: 'Botafogo', year: 1968, label: 'Botafogo 1968 (Taca Brasil)', coach: 'Zagallo',
    colors: { p: '#000000', s: '#ffffff' },
    players: [
      { name: 'Cao', pos: ['GOL'], ovr: 79 },
      { name: 'Moreira', pos: ['LD'], ovr: 79 },
      { name: 'Ze Carlos', pos: ['ZAG'], ovr: 82 },
      { name: 'Leonidas', pos: ['ZAG'], ovr: 80 },
      { name: 'Waltencir', pos: ['LE'], ovr: 81 },
      { name: 'Carlos Roberto', pos: ['VOL'], ovr: 83 },
      { name: 'Gerson', pos: ['MEI','VOL'], ovr: 93 },
      { name: 'Rogerio', pos: ['PD','MD'], ovr: 82 },
      { name: 'Roberto', pos: ['GOL'], ovr: 84 },
      { name: 'Jairzinho', pos: ['ATA','PD'], ovr: 93 },
      { name: 'Paulo Cezar Caju', pos: ['PE','MEI'], ovr: 88 },
      { name: 'Ubirajara Motta', pos: ['GOL'], ovr: 76 },
      { name: 'Chiquinho Pastor', pos: ['ZAG'], ovr: 75 },
      { name: 'Dimas', pos: ['ZAG','LE'], ovr: 74 },
      { name: 'Nei Conceicao', pos: ['VOL','MEI'], ovr: 78 },
      { name: 'Zequinha', pos: ['PD'], ovr: 77 },
      { name: 'Ferretti', pos: ['GOL'], ovr: 80 },
      { name: 'Humberto', pos: ['GOL'], ovr: 74 },
      { name: 'Afonsinho', pos: ['MEI','ME'], ovr: 78 },
      { name: 'Torino', pos: ['PE','ATA'], ovr: 75 },
    ]},
  { id: 'fluminense1970', club: 'Fluminense', year: 1970, label: 'Fluminense 1970 (Taça de Prata)', coach: 'Paulo Amaral',
    colors: { p: '#7A1921', s: '#006633' },
    players: [
      { name: 'Felix', pos: ['GOL'], ovr: 84 },
      { name: 'Oliveira', pos: ['LD'], ovr: 78 },
      { name: 'Galhardo', pos: ['ZAG'], ovr: 79 },
      { name: 'Assis', pos: ['ZAG'], ovr: 80 },
      { name: 'Marco Antonio', pos: ['LE'], ovr: 84 },
      { name: 'Denilson', pos: ['VOL','ZAG'], ovr: 83 },
      { name: 'Didi', pos: ['VOL','MEI'], ovr: 77 },
      { name: 'Samarone', pos: ['MEI'], ovr: 82 },
      { name: 'Cafuringa', pos: ['PD','MD'], ovr: 81 },
      { name: 'Flavio Minuano', pos: ['GOL'], ovr: 83 },
      { name: 'Lula', pos: ['PE','ME'], ovr: 81 },
      { name: 'Jorge Vitorio', pos: ['GOL'], ovr: 73 },
      { name: 'Toninho', pos: ['LD'], ovr: 74 },
      { name: 'Silveira', pos: ['ZAG','VOL'], ovr: 77 },
      { name: 'Lulinha', pos: ['MEI','MD'], ovr: 72 },
      { name: 'Claudio Garcia', pos: ['PD','MEI'], ovr: 76 },
      { name: 'Wilton', pos: ['PD'], ovr: 73 },
      { name: 'Mickey', pos: ['GOL'], ovr: 81 },
      { name: 'Gilson Nunes', pos: ['PE'], ovr: 75 },
      { name: 'Jair', pos: ['GOL'], ovr: 71 },
    ]},
  { id: 'atletico-mg1971', club: 'Atletico-MG', year: 1971, label: 'Atletico-MG 1971 (Campeao Brasileiro)', coach: 'Tele Santana',
    colors: { p: '#000000', s: '#ffffff' },
    players: [
      { name: 'Renato', pos: ['GOL'], ovr: 82 },
      { name: 'Humberto Monteiro', pos: ['LD'], ovr: 79 },
      { name: 'Grapete', pos: ['ZAG'], ovr: 81 },
      { name: 'Vantuir', pos: ['ZAG'], ovr: 82 },
      { name: 'Oldair', pos: ['LE','ZAG'], ovr: 81 },
      { name: 'Vanderlei Paiva', pos: ['VOL'], ovr: 83 },
      { name: 'Ronaldo Drumond', pos: ['MEI','PD'], ovr: 80 },
      { name: 'Humberto Ramos', pos: ['MEI'], ovr: 81 },
      { name: 'Lola', pos: ['ATA','PD'], ovr: 81 },
      { name: 'Dario', pos: ['GOL'], ovr: 86 },
      { name: 'Tião', pos: ['PE','ME'], ovr: 79 },
      { name: 'Careca', pos: ['GOL'], ovr: 72 },
      { name: 'Zica', pos: ['LD'], ovr: 73 },
      { name: 'Bibi', pos: ['LE'], ovr: 74 },
      { name: 'Nadir', pos: ['ZAG'], ovr: 74 },
      { name: 'Danilo', pos: ['VOL'], ovr: 75 },
      { name: 'Spencer', pos: ['MEI','ME'], ovr: 74 },
      { name: 'Caldeira', pos: ['PE'], ovr: 76 },
      { name: 'Guara', pos: ['GOL'], ovr: 73 },
      { name: 'Romeu', pos: ['ATA'], ovr: 72 },
    ]},
  { id: 'palmeiras1972', club: 'Palmeiras', year: 1972, label: 'Palmeiras 1972 (Academia)', coach: 'Osvaldo Brandao',
    colors: { p: '#006437', s: '#ffffff' },
    players: [
      { name: 'Ademir da Guia', pos: ['MC','MEI'], ovr: 94 },
      { name: 'Leivinha', pos: ['MEI','ATA'], ovr: 91 },
      { name: 'Luís Pereira', pos: ['ZAG'], ovr: 91 },
      { name: 'Emerson Leão', pos: ['GOL'], ovr: 90 },
      { name: 'Dudu', pos: ['VOL','MC'], ovr: 89 },
      { name: 'César Maluco', pos: ['ATA'], ovr: 89 },
      { name: 'Eurico', pos: ['LD'], ovr: 86 },
      { name: 'Alfredo Mostarda', pos: ['ZAG'], ovr: 86 },
      { name: 'Zeca', pos: ['LE'], ovr: 85 },
      { name: 'Edu Bala', pos: ['PD','MD'], ovr: 85 },
      { name: 'Nei', pos: ['PE','ME'], ovr: 85 },
      { name: 'Ronaldo', pos: ['ATA','PD'], ovr: 83 },
      { name: 'Madurga', pos: ['MC','MEI'], ovr: 83 },
      { name: 'Polaco', pos: ['ZAG','LE'], ovr: 82 },
      { name: 'Fedato', pos: ['ATA'], ovr: 81 },
      { name: 'Pio', pos: ['PE','ATA'], ovr: 81 },
      { name: 'João Carlos', pos: ['LD','ZAG'], ovr: 80 },
      { name: 'Bernard', pos: ['GOL'], ovr: 79 },
      { name: 'Marinho', pos: ['VOL','MC'], ovr: 79 },
      { name: 'Celso', pos: ['MC'], ovr: 78 },
    ]},
  { id: 'palmeiras1973', club: 'Palmeiras', year: 1973, label: 'Palmeiras 1973 (Bicampeonato Academia)', coach: 'Osvaldo Brandao',
    colors: { p: '#006437', s: '#ffffff' },
    players: [
      { name: 'Ademir da Guia', pos: ['MC','MEI'], ovr: 94 },
      { name: 'Luís Pereira', pos: ['ZAG'], ovr: 92 },
      { name: 'Leivinha', pos: ['MEI','ATA'], ovr: 91 },
      { name: 'Emerson Leão', pos: ['GOL'], ovr: 91 },
      { name: 'Dudu', pos: ['VOL','MC'], ovr: 89 },
      { name: 'César Maluco', pos: ['ATA'], ovr: 88 },
      { name: 'Alfredo Mostarda', pos: ['ZAG'], ovr: 87 },
      { name: 'Eurico', pos: ['LD'], ovr: 86 },
      { name: 'Zeca', pos: ['LE'], ovr: 85 },
      { name: 'Edu Bala', pos: ['PD','MD'], ovr: 85 },
      { name: 'Nei', pos: ['PE','ME'], ovr: 84 },
      { name: 'Ronaldo', pos: ['ATA','PD'], ovr: 83 },
      { name: 'Fedato', pos: ['ATA'], ovr: 82 },
      { name: 'Polaco', pos: ['ZAG','LE'], ovr: 82 },
      { name: 'Pio', pos: ['PE','ATA'], ovr: 82 },
      { name: 'Toninho Vanusa', pos: ['MC','MEI'], ovr: 81 },
      { name: 'De Rosis', pos: ['VOL','MC'], ovr: 80 },
      { name: 'João Carlos', pos: ['LD','ZAG'], ovr: 80 },
      { name: 'Bernard', pos: ['GOL'], ovr: 79 },
      { name: 'Édson', pos: ['MC','ME'], ovr: 78 },
    ]},
  { id: 'vasco1974', club: 'Vasco', year: 1974, label: 'Vasco 1974 (Campeao Brasileiro)', coach: 'Mario Travaglini',
    colors: { p: '#000000', s: '#ffffff' },
    players: [
      { name: 'Roberto Dinamite', pos: ['ATA','MEI'], ovr: 93 },
      { name: 'Andrada', pos: ['GOL'], ovr: 89 },
      { name: 'Zanata', pos: ['MC','MEI'], ovr: 88 },
      { name: 'Alcir', pos: ['VOL','MC'], ovr: 87 },
      { name: 'Miguel', pos: ['ZAG'], ovr: 87 },
      { name: 'Fidélis', pos: ['LD'], ovr: 86 },
      { name: 'Alfinete', pos: ['LE','LD'], ovr: 86 },
      { name: 'Moisés', pos: ['ZAG'], ovr: 86 },
      { name: 'Jorginho Carvoeiro', pos: ['PD','MD'], ovr: 85 },
      { name: 'Luiz Carlos', pos: ['PE','ME'], ovr: 85 },
      { name: 'Ademir', pos: ['MEI','MC'], ovr: 85 },
      { name: 'Joel Santana', pos: ['ZAG','LD'], ovr: 83 },
      { name: 'Peres', pos: ['MC','MEI'], ovr: 83 },
      { name: 'Paulo César', pos: ['LE'], ovr: 82 },
      { name: 'Mazarópi', pos: ['GOL'], ovr: 81 },
      { name: 'Fred', pos: ['VOL','MC'], ovr: 81 },
      { name: 'Amarildo', pos: ['ATA'], ovr: 80 },
      { name: 'Jaílson', pos: ['PD','ATA'], ovr: 80 },
      { name: 'Gaúcho', pos: ['ZAG'], ovr: 79 },
      { name: 'Galdino', pos: ['PE','ME'], ovr: 79 },
    ]},
  { id: 'internacional1975', club: 'Internacional', year: 1975, label: 'Internacional 1975 (Campeao Brasileiro)', coach: 'Rubens Minelli',
    colors: { p: '#D2122E', s: '#ffffff' },
    players: [
      { name: 'Falcão', pos: ['VOL','MC'], ovr: 95 },
      { name: 'Figueiroa', pos: ['ZAG'], ovr: 95 },
      { name: 'Carpegiani', pos: ['MC','MEI'], ovr: 91 },
      { name: 'Manga', pos: ['GOL'], ovr: 90 },
      { name: 'Lula', pos: ['PE','ME'], ovr: 88 },
      { name: 'Valdomiro', pos: ['PD','MD'], ovr: 88 },
      { name: 'Flávio Minuano', pos: ['ATA'], ovr: 88 },
      { name: 'Caçapava', pos: ['VOL','MC'], ovr: 87 },
      { name: 'Vacaria', pos: ['LE'], ovr: 86 },
      { name: 'Hermínio', pos: ['ZAG'], ovr: 85 },
      { name: 'Valdir', pos: ['LD'], ovr: 85 },
      { name: 'Batista', pos: ['VOL','MC'], ovr: 84 },
      { name: 'Jair', pos: ['MEI','MC'], ovr: 83 },
      { name: 'Cláudio Duarte', pos: ['LD','ZAG'], ovr: 83 },
      { name: 'Ramon', pos: ['ATA'], ovr: 82 },
      { name: 'Chico Spina', pos: ['PD','ATA'], ovr: 81 },
      { name: 'Schneider', pos: ['GOL'], ovr: 80 },
      { name: 'Borjão', pos: ['ATA'], ovr: 80 },
      { name: 'Escurinho', pos: ['ATA','MEI'], ovr: 80 },
      { name: 'Edinho', pos: ['LE'], ovr: 78 },
    ]},
  { id: 'corinthians1977', club: 'Corinthians', year: 1977, label: 'Corinthians 1977', coach: 'Oswaldo Brandao',
    colors: { p: '#000000', s: '#ffffff' },
    players: [
      { name: 'Tobias', pos: ['GOL'], ovr: 84 },
      { name: 'Ze Maria', pos: ['LD'], ovr: 88 },
      { name: 'Amaral', pos: ['ZAG'], ovr: 83 },
      { name: 'Moises', pos: ['ZAG'], ovr: 81 },
      { name: 'Wladimir', pos: ['LE'], ovr: 86 },
      { name: 'Russo', pos: ['VOL','MC'], ovr: 82 },
      { name: 'Basilio', pos: ['MEI','ATA'], ovr: 87 },
      { name: 'Vaguinho', pos: ['PD','MD'], ovr: 84 },
      { name: 'Geraldao', pos: ['ATA'], ovr: 83 },
      { name: 'Palinha', pos: ['ATA','MEI'], ovr: 86 },
      { name: 'Romeu', pos: ['PE','ME'], ovr: 82 },
      { name: 'Jairo', pos: ['GOL'], ovr: 78 },
      { name: 'Ruco', pos: ['VOL','MC'], ovr: 81 },
      { name: 'Luciano', pos: ['MC','VOL'], ovr: 79 },
      { name: 'Givanildo Oliveira', pos: ['VOL','MC'], ovr: 78 },
      { name: 'Adaozinho', pos: ['ZAG','LD'], ovr: 77 },
      { name: 'Claudio Mineiro', pos: ['LE','ZAG'], ovr: 77 },
      { name: 'Lance', pos: ['MEI','ATA'], ovr: 76 },
      { name: 'Edu Bala', pos: ['PD','MD'], ovr: 76 },
      { name: 'Suprema', pos: ['ATA'], ovr: 73 },
    ]},
  { id: 'guarani1978', club: 'Guarani', year: 1978, label: 'Guarani 1978 (Campeao Brasileiro)', coach: 'Carlos Alberto Silva',
    colors: { p: '#006437', s: '#ffffff' },
    players: [
      { name: 'Careca', pos: ['ATA'], ovr: 92 },
      { name: 'Zenon', pos: ['MEI','MC'], ovr: 91 },
      { name: 'Renato', pos: ['MC','MEI'], ovr: 89 },
      { name: 'Neneca', pos: ['GOL'], ovr: 88 },
      { name: 'Gomes', pos: ['ZAG'], ovr: 87 },
      { name: 'Capitão', pos: ['PD','MD'], ovr: 86 },
      { name: 'Bozó', pos: ['PE','ME'], ovr: 86 },
      { name: 'Miranda', pos: ['LE'], ovr: 85 },
      { name: 'Mauro', pos: ['LD'], ovr: 85 },
      { name: 'Zé Carlos', pos: ['VOL','MC'], ovr: 85 },
      { name: 'Edson', pos: ['ZAG'], ovr: 85 },
      { name: 'Manguinha', pos: ['VOL','MC'], ovr: 83 },
      { name: 'Silvinho', pos: ['PE','ATA'], ovr: 82 },
      { name: 'Macedo', pos: ['ATA'], ovr: 81 },
      { name: 'João de Deus', pos: ['GOL'], ovr: 80 },
      { name: 'Adriano', pos: ['MC','MEI'], ovr: 80 },
      { name: 'Alexandre', pos: ['LD','ZAG'], ovr: 79 },
      { name: 'Almeida', pos: ['LE'], ovr: 79 },
      { name: 'Gersinho', pos: ['PD'], ovr: 78 },
      { name: 'Cidão', pos: ['ZAG'], ovr: 78 },
    ]},
  { id: 'internacional1979', club: 'Internacional', year: 1979, label: 'Internacional 1979 (Invicto)', coach: 'Enio Andrade',
    colors: { p: '#D2122E', s: '#ffffff' },
    players: [
      { name: 'Falcão', pos: ['VOL','MC'], ovr: 97 },
      { name: 'Jair', pos: ['MEI','MC'], ovr: 91 },
      { name: 'Batista', pos: ['VOL','MC'], ovr: 90 },
      { name: 'Valdomiro', pos: ['PD','MD'], ovr: 89 },
      { name: 'Benítez', pos: ['GOL'], ovr: 89 },
      { name: 'Mauro Galvão', pos: ['ZAG','VOL'], ovr: 88 },
      { name: 'Mário Sérgio', pos: ['PE','ME'], ovr: 88 },
      { name: 'Bira', pos: ['ATA'], ovr: 87 },
      { name: 'Mauro Pastor', pos: ['ZAG'], ovr: 86 },
      { name: 'Cláudio Mineiro', pos: ['LE'], ovr: 85 },
      { name: 'Cláudio Duarte', pos: ['LD'], ovr: 85 },
      { name: 'Tonho', pos: ['MC','MEI'], ovr: 83 },
      { name: 'Chico Spina', pos: ['PD','ATA'], ovr: 83 },
      { name: 'Adilson', pos: ['ATA'], ovr: 82 },
      { name: 'Beretta', pos: ['LD','ZAG'], ovr: 81 },
      { name: 'Hermínio', pos: ['ZAG'], ovr: 81 },
      { name: 'João Carlos', pos: ['LE'], ovr: 80 },
      { name: 'Bagatini', pos: ['GOL'], ovr: 79 },
      { name: 'Valdir Lima', pos: ['MC'], ovr: 79 },
      { name: 'Silvinho', pos: ['PE'], ovr: 78 },
    ]},
  { id: 'flamengo1980', club: 'Flamengo', year: 1980, label: 'Flamengo 1980 (Campeao Brasileiro)', coach: 'Claudio Coutinho',
    colors: { p: '#C8102E', s: '#000000' },
    players: [
      { name: 'Zico', pos: ['MEI','MC'], ovr: 97 },
      { name: 'Júnior', pos: ['LE','MC'], ovr: 93 },
      { name: 'Carpegiani', pos: ['MC','MEI'], ovr: 90 },
      { name: 'Nunes', pos: ['ATA'], ovr: 89 },
      { name: 'Tita', pos: ['PD','MEI'], ovr: 89 },
      { name: 'Raul Plassmann', pos: ['GOL'], ovr: 88 },
      { name: 'Marinho', pos: ['ZAG'], ovr: 87 },
      { name: 'Andrade', pos: ['VOL','MC'], ovr: 87 },
      { name: 'Toninho', pos: ['LD'], ovr: 86 },
      { name: 'Júlio César Uri Geller', pos: ['PE','ME'], ovr: 86 },
      { name: 'Rondinelli', pos: ['ZAG'], ovr: 86 },
      { name: 'Manguito', pos: ['ZAG'], ovr: 84 },
      { name: 'Adílio', pos: ['MC','MEI'], ovr: 84 },
      { name: 'Cláudio Adão', pos: ['ATA'], ovr: 83 },
      { name: 'Reinaldo', pos: ['PE','ATA'], ovr: 82 },
      { name: 'Carlos Alberto', pos: ['LD'], ovr: 81 },
      { name: 'Cantarele', pos: ['GOL'], ovr: 81 },
      { name: 'Vítor', pos: ['VOL'], ovr: 80 },
      { name: 'Anselmo', pos: ['ATA'], ovr: 79 },
      { name: 'Lico', pos: ['PE','MEI'], ovr: 78 },
    ]},
  { id: 'flamengo1981', club: 'Flamengo', year: 1981, label: 'Flamengo 1981 (Mundial)', coach: 'Paulo Cesar Carpegiani',
    colors: { p: '#C8102E', s: '#000000' },
    players: [
      { name: 'Zico', pos: ['MEI','MC'], ovr: 98 },
      { name: 'Júnior', pos: ['LE','MC'], ovr: 94 },
      { name: 'Leandro', pos: ['LD','ZAG'], ovr: 92 },
      { name: 'Nunes', pos: ['ATA'], ovr: 90 },
      { name: 'Adílio', pos: ['MC','MEI'], ovr: 89 },
      { name: 'Tita', pos: ['PD','MEI'], ovr: 89 },
      { name: 'Raul Plassmann', pos: ['GOL'], ovr: 88 },
      { name: 'Mozer', pos: ['ZAG'], ovr: 88 },
      { name: 'Andrade', pos: ['VOL','MC'], ovr: 88 },
      { name: 'Marinho', pos: ['ZAG'], ovr: 87 },
      { name: 'Lico', pos: ['PE','MEI'], ovr: 86 },
      { name: 'Baroninho', pos: ['PE','ME'], ovr: 84 },
      { name: 'Chiquinho', pos: ['ATA'], ovr: 83 },
      { name: 'Cantarele', pos: ['GOL'], ovr: 81 },
      { name: 'Rondinelli', pos: ['ZAG'], ovr: 81 },
      { name: 'Nei Dias', pos: ['LD','LE'], ovr: 80 },
      { name: 'Vítor', pos: ['VOL'], ovr: 80 },
      { name: 'Anselmo', pos: ['ATA'], ovr: 80 },
      { name: 'Popoca', pos: ['MEI'], ovr: 79 },
      { name: 'Figueiredo', pos: ['ZAG'], ovr: 78 },
    ]},
  { id: 'flamengo1982', club: 'Flamengo', year: 1982, label: 'Flamengo 1982 (Bicampeao Brasileiro)', coach: 'Paulo Cesar Carpegiani',
    colors: { p: '#C8102E', s: '#000000' },
    players: [
      { name: 'Zico', pos: ['MEI','MC'], ovr: 98 },
      { name: 'Júnior', pos: ['LE','MC'], ovr: 94 },
      { name: 'Leandro', pos: ['LD','ZAG'], ovr: 93 },
      { name: 'Mozer', pos: ['ZAG'], ovr: 89 },
      { name: 'Nunes', pos: ['ATA'], ovr: 89 },
      { name: 'Adílio', pos: ['MC','MEI'], ovr: 89 },
      { name: 'Tita', pos: ['PD','MEI'], ovr: 89 },
      { name: 'Raul Plassmann', pos: ['GOL'], ovr: 88 },
      { name: 'Andrade', pos: ['VOL','MC'], ovr: 88 },
      { name: 'Marinho', pos: ['ZAG'], ovr: 86 },
      { name: 'Lico', pos: ['PE','ME'], ovr: 86 },
      { name: 'Vítor', pos: ['VOL','MC'], ovr: 82 },
      { name: 'Cantarele', pos: ['GOL'], ovr: 81 },
      { name: 'Figueiredo', pos: ['ZAG'], ovr: 81 },
      { name: 'Popoca', pos: ['MEI','MC'], ovr: 81 },
      { name: 'Chiquinho', pos: ['ATA'], ovr: 80 },
      { name: 'Antunes', pos: ['LD'], ovr: 79 },
      { name: 'Reinaldo', pos: ['PE'], ovr: 79 },
      { name: 'Anselmo', pos: ['ATA'], ovr: 79 },
      { name: 'Wilsinho', pos: ['PD','PE'], ovr: 78 },
    ]},
  { id: 'fluminense1984', club: 'Fluminense', year: 1984, label: 'Fluminense 1984 (Campeao Brasileiro)', coach: 'Carlos Alberto Parreira',
    colors: { p: '#7A1921', s: '#006633' },
    players: [
      { name: 'Romerito', pos: ['MEI','ATA'], ovr: 92 },
      { name: 'Assis', pos: ['MEI','ATA'], ovr: 90 },
      { name: 'Paulo Víctor', pos: ['GOL'], ovr: 88 },
      { name: 'Ricardo Gomes', pos: ['ZAG'], ovr: 88 },
      { name: 'Washington', pos: ['ATA'], ovr: 88 },
      { name: 'Delei', pos: ['MC','VOL'], ovr: 87 },
      { name: 'Branco', pos: ['LE'], ovr: 87 },
      { name: 'Tato', pos: ['PE','ME'], ovr: 86 },
      { name: 'Jandir', pos: ['VOL','MC'], ovr: 86 },
      { name: 'Duílio', pos: ['ZAG','VOL'], ovr: 85 },
      { name: 'Aldo', pos: ['LD'], ovr: 85 },
      { name: 'Wilsinho', pos: ['PD','MD'], ovr: 83 },
      { name: 'Vica', pos: ['ZAG'], ovr: 83 },
      { name: 'Renê', pos: ['MC','VOL'], ovr: 82 },
      { name: 'Paulinho', pos: ['ATA'], ovr: 81 },
      { name: 'Leomir', pos: ['MC','MD'], ovr: 81 },
      { name: 'Beto', pos: ['LD'], ovr: 80 },
      { name: 'Renato', pos: ['LE'], ovr: 80 },
      { name: 'Galvão', pos: ['GOL'], ovr: 79 },
      { name: 'Edson', pos: ['PE','ME'], ovr: 78 },
    ]},
  { id: 'coritiba1985', club: 'Coritiba', year: 1985, label: 'Coritiba 1985 (Campeao Brasileiro)', coach: 'Enio Andrade',
    colors: { p: '#006437', s: '#ffffff' },
    players: [
      { name: 'Lela', pos: ['PD','ATA'], ovr: 89 },
      { name: 'Rafael', pos: ['GOL'], ovr: 88 },
      { name: 'Toby', pos: ['MEI','MC'], ovr: 87 },
      { name: 'Gomes', pos: ['ZAG'], ovr: 86 },
      { name: 'Marildo', pos: ['MC','VOL'], ovr: 85 },
      { name: 'Índio', pos: ['ATA'], ovr: 85 },
      { name: 'Heraldo', pos: ['ZAG'], ovr: 85 },
      { name: 'André', pos: ['LD'], ovr: 84 },
      { name: 'Dida', pos: ['LE'], ovr: 84 },
      { name: 'Almir', pos: ['VOL','MC'], ovr: 84 },
      { name: 'Édson', pos: ['PE','ME'], ovr: 84 },
      { name: 'Marco Aurélio', pos: ['MC','MEI'], ovr: 83 },
      { name: 'Vavá', pos: ['ZAG'], ovr: 82 },
      { name: 'Paulinho', pos: ['PD','ATA'], ovr: 82 },
      { name: 'Lulinha', pos: ['MC'], ovr: 81 },
      { name: 'Jairo', pos: ['GOL'], ovr: 80 },
      { name: 'Gardel', pos: ['VOL'], ovr: 80 },
      { name: 'Caxias', pos: ['ZAG'], ovr: 79 },
      { name: 'Vicente', pos: ['LE'], ovr: 78 },
      { name: 'Hélio', pos: ['ATA'], ovr: 78 },
    ]},
  { id: 'sao-paulo1986', club: 'Sao Paulo', year: 1986, label: 'São Paulo 1986 (Campeão Brasileiro)', coach: 'Pepe',
    colors: { p: '#C8102E', s: '#ffffff' },
    players: [
      { name: 'Careca', pos: ['ATA'], ovr: 95 },
      { name: 'Müller', pos: ['ATA','PD'], ovr: 91 },
      { name: 'Darío Pereyra', pos: ['ZAG','VOL'], ovr: 90 },
      { name: 'Gilmar Rinaldi', pos: ['GOL'], ovr: 88 },
      { name: 'Silas', pos: ['MC','MEI'], ovr: 88 },
      { name: 'Oscar', pos: ['ZAG'], ovr: 87 },
      { name: 'Nelsinho', pos: ['LE'], ovr: 87 },
      { name: 'Bernardo', pos: ['VOL','MC'], ovr: 86 },
      { name: 'Pita', pos: ['MEI','MC'], ovr: 86 },
      { name: 'Zé Teodoro', pos: ['LD'], ovr: 85 },
      { name: 'Sidnei', pos: ['PD','MD'], ovr: 84 },
      { name: 'Wagner Basílio', pos: ['ZAG'], ovr: 83 },
      { name: 'Fonseca', pos: ['LD','ZAG'], ovr: 83 },
      { name: 'Ronaldão', pos: ['ZAG','LE'], ovr: 82 },
      { name: 'Vizolli', pos: ['VOL'], ovr: 82 },
      { name: 'Pianelli', pos: ['MEI','PE'], ovr: 81 },
      { name: 'Lange', pos: ['ATA'], ovr: 81 },
      { name: 'Abelha', pos: ['GOL'], ovr: 80 },
      { name: 'Manu', pos: ['MC','ME'], ovr: 79 },
      { name: 'Quarenta', pos: ['LE'], ovr: 78 },
    ]},
  { id: 'sport1987', club: 'Sport', year: 1987, label: 'Sport 1987 (Campeão Brasileiro)', coach: 'Emerson Leao',
    colors: { p: '#C8102E', s: '#000000' },
    players: [
      { name: 'Ribamar', pos: ['MEI','MC'], ovr: 88 },
      { name: 'Flávio', pos: ['GOL'], ovr: 87 },
      { name: 'Neco', pos: ['ATA','MEI'], ovr: 86 },
      { name: 'Estevam', pos: ['ZAG'], ovr: 86 },
      { name: 'Marco Antônio', pos: ['ZAG'], ovr: 85 },
      { name: 'Betão', pos: ['LD'], ovr: 85 },
      { name: 'Zé do Carmo', pos: ['VOL','MC'], ovr: 85 },
      { name: 'Robertinho', pos: ['PD'], ovr: 84 },
      { name: 'Zinho', pos: ['PE','ME'], ovr: 84 },
      { name: 'Macaxeira', pos: ['LE'], ovr: 83 },
      { name: 'Rogério', pos: ['VOL','MC'], ovr: 83 },
      { name: 'Augusto', pos: ['ATA'], ovr: 82 },
      { name: 'Cláudio', pos: ['MC'], ovr: 81 },
      { name: 'Adriano', pos: ['ZAG'], ovr: 81 },
      { name: 'Givaldo', pos: ['LD'], ovr: 80 },
      { name: 'Dedé', pos: ['LE'], ovr: 80 },
      { name: 'Isaías', pos: ['ATA'], ovr: 79 },
      { name: 'Maceió', pos: ['PD','MD'], ovr: 79 },
      { name: 'Moza', pos: ['GOL'], ovr: 78 },
      { name: 'Joécio', pos: ['VOL'], ovr: 78 },
    ]},
  { id: 'bahia1988', club: 'Bahia', year: 1988, label: 'Bahia 1988 (Bicampeão Brasileiro)', coach: 'Evaristo de Macedo',
    colors: { p: '#003399', s: '#C8102E' },
    players: [
      { name: 'Bobô', pos: ['MEI','MC'], ovr: 91 },
      { name: 'Ronaldo', pos: ['GOL'], ovr: 89 },
      { name: 'Charles Fabian', pos: ['ATA'], ovr: 88 },
      { name: 'Zé Carlos', pos: ['MC','MEI'], ovr: 87 },
      { name: 'Claudir', pos: ['ZAG'], ovr: 86 },
      { name: 'João Marcelo', pos: ['ZAG'], ovr: 86 },
      { name: 'Paulo Rodrigues', pos: ['VOL','MC'], ovr: 86 },
      { name: 'Marquinhos', pos: ['PD','MD'], ovr: 85 },
      { name: 'Tarantini', pos: ['LD'], ovr: 85 },
      { name: 'Paulo César', pos: ['LE'], ovr: 85 },
      { name: 'Sandro', pos: ['PE','ME'], ovr: 84 },
      { name: 'Gil Sergipano', pos: ['VOL','ZAG'], ovr: 84 },
      { name: 'Osmar', pos: ['ATA'], ovr: 83 },
      { name: 'Deda', pos: ['MEI','MD'], ovr: 82 },
      { name: 'Newmar', pos: ['ZAG'], ovr: 81 },
      { name: 'Edinho', pos: ['LD'], ovr: 81 },
      { name: 'Mailson', pos: ['LE'], ovr: 80 },
      { name: 'Sidmar', pos: ['GOL'], ovr: 80 },
      { name: 'Renato', pos: ['PD'], ovr: 79 },
      { name: 'Sales', pos: ['MC','MD'], ovr: 78 },
    ]},
  { id: 'vasco1989', club: 'Vasco', year: 1989, label: 'Vasco 1989 (Campeão Brasileiro)', coach: 'Nelsinho Rosa',
    colors: { p: '#000000', s: '#ffffff' },
    players: [
      { name: 'Acácio', pos: ['GOL'], ovr: 85 },
      { name: 'Luís Carlos Winck', pos: ['LD'], ovr: 84 },
      { name: 'Quiñonez', pos: ['ZAG'], ovr: 83 },
      { name: 'Marco Aurélio', pos: ['ZAG'], ovr: 82 },
      { name: 'Célio Silva', pos: ['ZAG'], ovr: 80 },
      { name: 'Mazinho', pos: ['LE','VOL'], ovr: 87 },
      { name: 'Zé do Carmo', pos: ['VOL','MC'], ovr: 84 },
      { name: 'Andrade', pos: ['VOL'], ovr: 83 },
      { name: 'Marco Antônio Boiadeiro', pos: ['MC'], ovr: 83 },
      { name: 'Bismarck', pos: ['MEI'], ovr: 86 },
      { name: 'Bebeto', pos: ['ATA'], ovr: 90 },
      { name: 'Tita', pos: ['MEI','ATA'], ovr: 85 },
      { name: 'William', pos: ['MEI','MD'], ovr: 82 },
      { name: 'Sorato', pos: ['ATA'], ovr: 83 },
      { name: 'Tato', pos: ['PE','ME'], ovr: 80 },
      { name: 'Ayupe', pos: ['LD'], ovr: 74 },
      { name: 'Leonardo Siqueira', pos: ['ZAG'], ovr: 76 },
      { name: 'Cássio', pos: ['LE'], ovr: 74 },
      { name: 'França', pos: ['VOL'], ovr: 75 },
      { name: 'Reginaldo', pos: ['GOL'], ovr: 75 },
    ]},
  { id: 'corinthians1990', club: 'Corinthians', year: 1990, label: 'Corinthians 1990 (Primeiro Titulo)', coach: 'Nelsinho Baptista',
    colors: { p: '#000000', s: '#ffffff' },
    players: [
      { name: 'Neto', pos: ['MEI','MC'], ovr: 92 },
      { name: 'Ronaldo Giovanelli', pos: ['GOL'], ovr: 89 },
      { name: 'Márcio Bittencourt', pos: ['VOL','MC'], ovr: 87 },
      { name: 'Tupãzinho', pos: ['MC','MEI'], ovr: 87 },
      { name: 'Marcelo Djian', pos: ['ZAG'], ovr: 86 },
      { name: 'Wilson Mano', pos: ['VOL','LD'], ovr: 86 },
      { name: 'Giba', pos: ['LD'], ovr: 85 },
      { name: 'Jacenir', pos: ['LE'], ovr: 85 },
      { name: 'Fabinho', pos: ['PD','MD'], ovr: 85 },
      { name: 'Mauro', pos: ['ZAG'], ovr: 84 },
      { name: 'Guinei', pos: ['ZAG'], ovr: 84 },
      { name: 'Dinei', pos: ['ATA'], ovr: 84 },
      { name: 'Mauro II', pos: ['PE','ME'], ovr: 83 },
      { name: 'Ezequiel', pos: ['VOL'], ovr: 83 },
      { name: 'Paulo Sérgio', pos: ['ATA','PE'], ovr: 82 },
      { name: 'Jairo', pos: ['ATA'], ovr: 81 },
      { name: 'Marcos Roberto', pos: ['LE'], ovr: 80 },
      { name: 'Wilson', pos: ['GOL'], ovr: 80 },
      { name: 'Dama', pos: ['ZAG'], ovr: 79 },
      { name: 'Toninho', pos: ['MC','ME'], ovr: 78 },
    ]},
  { id: 'sao-paulo1991', club: 'Sao Paulo', year: 1991, label: 'São Paulo 1991 (Campeão Brasileiro)', coach: 'Tele Santana',
    colors: { p: '#C8102E', s: '#ffffff' },
    players: [
      { name: 'Raí', pos: ['MEI','MC'], ovr: 94 },
      { name: 'Müller', pos: ['ATA','PD'], ovr: 92 },
      { name: 'Zetti', pos: ['GOL'], ovr: 91 },
      { name: 'Ricardo Rocha', pos: ['ZAG'], ovr: 91 },
      { name: 'Leonardo', pos: ['LE','MC'], ovr: 90 },
      { name: 'Cafu', pos: ['LD','PD'], ovr: 90 },
      { name: 'Ronaldão', pos: ['ZAG','VOL'], ovr: 87 },
      { name: 'Bernardo', pos: ['VOL','MC'], ovr: 86 },
      { name: 'Macedo', pos: ['ATA','PD'], ovr: 86 },
      { name: 'Antônio Carlos', pos: ['ZAG'], ovr: 85 },
      { name: 'Elivélton', pos: ['PE','ME'], ovr: 85 },
      { name: 'Flávio', pos: ['VOL','MC'], ovr: 84 },
      { name: 'Ivan', pos: ['LE'], ovr: 83 },
      { name: 'Vizolli', pos: ['VOL'], ovr: 83 },
      { name: 'Rinaldo', pos: ['PE'], ovr: 82 },
      { name: 'Baiano', pos: ['ATA'], ovr: 82 },
      { name: 'Marcos Adriano', pos: ['GOL'], ovr: 81 },
      { name: 'Cláudio', pos: ['LD'], ovr: 80 },
      { name: 'Amélio', pos: ['ZAG'], ovr: 79 },
      { name: 'Suélio', pos: ['MC'], ovr: 78 },
    ]},
  { id: 'flamengo1992', club: 'Flamengo', year: 1992, label: 'Flamengo 1992 (Campeão Brasileiro)', coach: 'Carlinhos',
    colors: { p: '#C8102E', s: '#000000' },
    players: [
      { name: 'Júnior', pos: ['MC','LE'], ovr: 93 },
      { name: 'Gilmar', pos: ['GOL'], ovr: 88 },
      { name: 'Zinho', pos: ['ME','MC'], ovr: 88 },
      { name: 'Gaúcho', pos: ['ATA'], ovr: 87 },
      { name: 'Wilson Gottardo', pos: ['ZAG'], ovr: 87 },
      { name: 'Djalminha', pos: ['MEI','ME'], ovr: 86 },
      { name: 'Piá', pos: ['LE'], ovr: 86 },
      { name: 'Charles', pos: ['LD'], ovr: 85 },
      { name: 'Júnior Baiano', pos: ['ZAG'], ovr: 85 },
      { name: 'Uidemar', pos: ['VOL','MC'], ovr: 85 },
      { name: 'Nélio', pos: ['PE','MEI'], ovr: 85 },
      { name: 'Marcelinho Carioca', pos: ['MEI','PD'], ovr: 84 },
      { name: 'Rogério', pos: ['ZAG'], ovr: 83 },
      { name: 'Marquinhos', pos: ['MC','VOL'], ovr: 83 },
      { name: 'Paulo Nunes', pos: ['PD','ATA'], ovr: 83 },
      { name: 'Fabinho', pos: ['VOL'], ovr: 82 },
      { name: 'Totó', pos: ['ATA'], ovr: 81 },
      { name: 'Gelson', pos: ['ZAG'], ovr: 80 },
      { name: 'Adriano', pos: ['GOL'], ovr: 79 },
      { name: 'Luís Antônio', pos: ['LE'], ovr: 78 },
    ]},
  { id: 'palmeiras1993', club: 'Palmeiras', year: 1993, label: 'Palmeiras 1993 (Campeão Brasileiro)', coach: 'Vanderlei Luxemburgo',
    colors: { p: '#006437', s: '#ffffff' },
    players: [
      { name: 'Edmundo', pos: ['PD','ATA'], ovr: 93 },
      { name: 'Roberto Carlos', pos: ['LE'], ovr: 92 },
      { name: 'Evair', pos: ['ATA'], ovr: 92 },
      { name: 'César Sampaio', pos: ['VOL','MC'], ovr: 91 },
      { name: 'Zinho', pos: ['ME','MC'], ovr: 90 },
      { name: 'Antônio Carlos', pos: ['ZAG'], ovr: 89 },
      { name: 'Sérgio', pos: ['GOL'], ovr: 87 },
      { name: 'Mazinho', pos: ['MC','LD'], ovr: 87 },
      { name: 'Edílson', pos: ['PE','ATA'], ovr: 87 },
      { name: 'Cléber', pos: ['ZAG'], ovr: 86 },
      { name: 'Cláudio', pos: ['LD'], ovr: 86 },
      { name: 'Daniel Frasson', pos: ['VOL','MC'], ovr: 84 },
      { name: 'Tonhão', pos: ['ZAG'], ovr: 83 },
      { name: 'Sorato', pos: ['ATA'], ovr: 83 },
      { name: 'Maurílio', pos: ['PD','LD'], ovr: 82 },
      { name: 'Amaral', pos: ['VOL'], ovr: 82 },
      { name: 'Jean Carlo', pos: ['PE','ME'], ovr: 81 },
      { name: 'Velloso', pos: ['GOL'], ovr: 80 },
      { name: 'Ricardo', pos: ['LE'], ovr: 79 },
      { name: 'Juary', pos: ['MC','MD'], ovr: 78 },
    ]},
  { id: 'palmeiras1994', club: 'Palmeiras', year: 1994, label: 'Palmeiras 1994 (Bicampeão Brasileiro)', coach: 'Vanderlei Luxemburgo',
    colors: { p: '#006437', s: '#ffffff' },
    players: [
      { name: 'Rivaldo', pos: ['MEI','MC'], ovr: 94 },
      { name: 'Edmundo', pos: ['PD','ATA'], ovr: 93 },
      { name: 'Roberto Carlos', pos: ['LE'], ovr: 93 },
      { name: 'Evair', pos: ['ATA'], ovr: 92 },
      { name: 'César Sampaio', pos: ['VOL','MC'], ovr: 91 },
      { name: 'Zinho', pos: ['ME','MC'], ovr: 90 },
      { name: 'Cléber', pos: ['ZAG'], ovr: 89 },
      { name: 'Antônio Carlos', pos: ['ZAG'], ovr: 88 },
      { name: 'Velloso', pos: ['GOL'], ovr: 88 },
      { name: 'Flávio Conceição', pos: ['MC','VOL'], ovr: 87 },
      { name: 'Mazinho', pos: ['MC','LD'], ovr: 86 },
      { name: 'Cláudio', pos: ['LD'], ovr: 85 },
      { name: 'Amaral', pos: ['VOL'], ovr: 85 },
      { name: 'Maurílio', pos: ['PD','ATA'], ovr: 83 },
      { name: 'Tonhão', pos: ['ZAG'], ovr: 83 },
      { name: 'Sorato', pos: ['ATA'], ovr: 82 },
      { name: 'Wagner', pos: ['LE'], ovr: 81 },
      { name: 'Sérgio', pos: ['GOL'], ovr: 80 },
      { name: 'Macula', pos: ['MC'], ovr: 79 },
      { name: 'Chiquinho', pos: ['PE'], ovr: 78 },
    ]},
  { id: 'botafogo1995', club: 'Botafogo', year: 1995, label: 'Botafogo 1995', coach: 'Paulo Autuori',
    colors: { p: '#000000', s: '#ffffff' },
    players: [
      { name: 'Wagner', pos: ['GOL'], ovr: 81 },
      { name: 'Wilson Goiano', pos: ['LD'], ovr: 77 },
      { name: 'Wilson Gottardo', pos: ['ZAG'], ovr: 80 },
      { name: 'Goncalves', pos: ['ZAG'], ovr: 79 },
      { name: 'Andre Silva', pos: ['LE'], ovr: 76 },
      { name: 'Leandro Avila', pos: ['VOL'], ovr: 78 },
      { name: 'Jamir', pos: ['VOL','MEI'], ovr: 78 },
      { name: 'Beto', pos: ['MEI','VOL'], ovr: 77 },
      { name: 'Sergio Manoel', pos: ['MEI','PD'], ovr: 80 },
      { name: 'Donizete', pos: ['ATA'], ovr: 81 },
      { name: 'Tulio Maravilha', pos: ['ATA'], ovr: 89 },
      { name: 'Moises', pos: ['LE'], ovr: 72 },
      { name: 'Iranildo', pos: ['MEI'], ovr: 75 },
      { name: 'Marcelo Alves', pos: ['MEI','MD'], ovr: 72 },
      { name: 'Narcizio', pos: ['ATA'], ovr: 71 },
      { name: 'Rui', pos: ['ATA'], ovr: 71 },
      { name: 'Marcio', pos: ['LD'], ovr: 71 },
      { name: 'Claudinho', pos: ['ZAG'], ovr: 70 },
      { name: 'Jorginho', pos: ['MEI'], ovr: 71 },
      { name: 'Alan', pos: ['PE','ME'], ovr: 70 },
    ]},
  { id: 'gremio1996', club: 'Gremio', year: 1996, label: 'Gremio 1996', coach: 'Luiz Felipe Scolari',
    colors: { p: '#1c3f94', s: '#000000' },
    players: [
      { name: 'Danrlei', pos: ['GOL'], ovr: 82 },
      { name: 'Arce', pos: ['LD','PD'], ovr: 81 },
      { name: 'Rivarola', pos: ['ZAG'], ovr: 79 },
      { name: 'Mauro Galvao', pos: ['ZAG'], ovr: 82 },
      { name: 'Roger', pos: ['LE'], ovr: 79 },
      { name: 'Dinho', pos: ['VOL','MEI'], ovr: 79 },
      { name: 'Luis Carlos Goiano', pos: ['VOL'], ovr: 78 },
      { name: 'Emerson', pos: ['MEI','VOL'], ovr: 82 },
      { name: 'Carlos Miguel', pos: ['MEI','ME'], ovr: 79 },
      { name: 'Paulo Nunes', pos: ['ATA'], ovr: 87 },
      { name: 'Ze Alcino', pos: ['PE'], ovr: 78 },
      { name: 'Adilson', pos: ['ZAG'], ovr: 75 },
      { name: 'Luciano', pos: ['ZAG'], ovr: 73 },
      { name: 'Ailton', pos: ['ATA'], ovr: 76 },
      { name: 'Ze Afonso', pos: ['ATA'], ovr: 72 },
      { name: 'Arilson', pos: ['MEI'], ovr: 73 },
      { name: 'Helio', pos: ['LD'], ovr: 71 },
      { name: 'Marcelo', pos: ['PE','ME'], ovr: 71 },
      { name: 'Marcio', pos: ['GOL'], ovr: 70 },
      { name: 'Jose Wilson', pos: ['ATA'], ovr: 70 },
    ]},
  { id: 'vasco1997', club: 'Vasco', year: 1997, label: 'Vasco 1997 (Brasileiro)', coach: 'Antonio Lopes',
    colors: { p: '#000000', s: '#ffffff' },
    players: [
      { name: 'Carlos Germano', pos: ['GOL'], ovr: 82 },
      { name: 'Valber', pos: ['LD'], ovr: 78 },
      { name: 'Odvan', pos: ['ZAG'], ovr: 79 },
      { name: 'Mauro Galvao', pos: ['ZAG'], ovr: 81 },
      { name: 'Felipe', pos: ['LE'], ovr: 80 },
      { name: 'Luisinho', pos: ['VOL','MEI'], ovr: 79 },
      { name: 'Nasa', pos: ['VOL','MEI'], ovr: 78 },
      { name: 'Juninho Pernambucano', pos: ['MEI','PD'], ovr: 85 },
      { name: 'Ramon', pos: ['MEI','PD'], ovr: 81 },
      { name: 'Edmundo', pos: ['ATA'], ovr: 95 },
      { name: 'Evair', pos: ['PE','ATA'], ovr: 85 },
      { name: 'Marica', pos: ['LD'], ovr: 73 },
      { name: 'Alex Pinho', pos: ['ZAG'], ovr: 72 },
      { name: 'Pedrinho', pos: ['MEI','MD'], ovr: 77 },
      { name: 'Mauricinho', pos: ['MEI'], ovr: 72 },
      { name: 'Donizete', pos: ['ATA'], ovr: 79 },
      { name: 'Brener', pos: ['ATA'], ovr: 73 },
      { name: 'Luizao', pos: ['ATA'], ovr: 80 },
      { name: 'Gil', pos: ['ZAG'], ovr: 71 },
      { name: 'Sandro', pos: ['MEI','ME'], ovr: 70 },
    ]},
  { id: 'vasco1998', club: 'Vasco', year: 1998, label: 'Vasco 1998 (Libertadores)', coach: 'Antonio Lopes',
    colors: { p: '#000000', s: '#ffffff' },
    players: [
      { name: 'Carlos Germano', pos: ['GOL'], ovr: 83 },
      { name: 'Vagner', pos: ['LD'], ovr: 79 },
      { name: 'Mauro Galvao', pos: ['ZAG'], ovr: 82 },
      { name: 'Odvan', pos: ['ZAG'], ovr: 80 },
      { name: 'Felipe', pos: ['LE'], ovr: 81 },
      { name: 'Luisinho', pos: ['VOL','MEI'], ovr: 80 },
      { name: 'Nasa', pos: ['VOL','MEI'], ovr: 79 },
      { name: 'Juninho Pernambucano', pos: ['MEI','PD'], ovr: 87 },
      { name: 'Pedrinho', pos: ['MEI'], ovr: 80 },
      { name: 'Edmundo', pos: ['ATA'], ovr: 91 },
      { name: 'Luizao', pos: ['ATA'], ovr: 87 },
      { name: 'Donizete', pos: ['ATA'], ovr: 84 },
      { name: 'Evair', pos: ['PE','ATA'], ovr: 83 },
      { name: 'Ramon', pos: ['MEI','PD'], ovr: 82 },
      { name: 'Cesar Prates', pos: ['LD'], ovr: 77 },
      { name: 'Alex Pinho', pos: ['ZAG'], ovr: 73 },
      { name: 'Paulo', pos: ['VOL'], ovr: 72 },
      { name: 'Valdir', pos: ['LD'], ovr: 71 },
      { name: 'Lima', pos: ['MEI','MD'], ovr: 71 },
      { name: 'Clayton', pos: ['ATA'], ovr: 72 },
    ]},
  { id: 'corinthians1998', club: 'Corinthians', year: 1998, label: 'Corinthians 1998 (Bicampeao)', coach: 'Vanderlei Luxemburgo',
    colors: { p: '#000000', s: '#ffffff' },
    players: [
      { name: 'Nei', pos: ['GOL'], ovr: 77 },
      { name: 'Dida', pos: ['GOL'], ovr: 86 },
      { name: 'Indio', pos: ['LD'], ovr: 80 },
      { name: 'Batata', pos: ['ZAG'], ovr: 79 },
      { name: 'Marcio Costa', pos: ['ZAG'], ovr: 78 },
      { name: 'Gamarra', pos: ['ZAG'], ovr: 92 },
      { name: 'Sylvinho', pos: ['LE','PE'], ovr: 85 },
      { name: 'Vampeta', pos: ['VOL'], ovr: 88 },
      { name: 'Rincon', pos: ['MEI'], ovr: 87 },
      { name: 'Ricardinho', pos: ['MEI','ME'], ovr: 88 },
      { name: 'Marcelinho Carioca', pos: ['MEI'], ovr: 91 },
      { name: 'Edilson', pos: ['ATA','MEI'], ovr: 90 },
      { name: 'Dinei', pos: ['ATA'], ovr: 78 },
      { name: 'Didi', pos: ['ATA'], ovr: 75 },
      { name: 'Amaral', pos: ['VOL'], ovr: 76 },
      { name: 'Cris', pos: ['ZAG','LE'], ovr: 74 },
      { name: 'Adilson', pos: ['ZAG'], ovr: 73 },
      { name: 'Kleber', pos: ['LE'], ovr: 78 },
      { name: 'Mirandinha', pos: ['ATA'], ovr: 74 },
      { name: 'Gilmar Fuba', pos: ['VOL'], ovr: 76 },
    ]},
  { id: 'corinthians1999', club: 'Corinthians', year: 1999, label: 'Corinthians 1999 (Tricampeao)', coach: 'Oswaldo de Oliveira',
    colors: { p: '#000000', s: '#ffffff' },
    players: [
      { name: 'Dida', pos: ['GOL'], ovr: 88 },
      { name: 'Indio', pos: ['LD'], ovr: 80 },
      { name: 'Joao Carlos', pos: ['ZAG'], ovr: 79 },
      { name: 'Marcio Costa', pos: ['ZAG'], ovr: 79 },
      { name: 'Kleber', pos: ['LE'], ovr: 79 },
      { name: 'Vampeta', pos: ['VOL'], ovr: 89 },
      { name: 'Rincon', pos: ['MEI','MD'], ovr: 87 },
      { name: 'Ricardinho', pos: ['MEI'], ovr: 88 },
      { name: 'Marcelinho Carioca', pos: ['MEI','ME'], ovr: 92 },
      { name: 'Edilson', pos: ['ATA','MEI'], ovr: 89 },
      { name: 'Luizao', pos: ['ATA'], ovr: 87 },
      { name: 'Dinei', pos: ['ATA'], ovr: 79 },
      { name: 'Marcos Senna', pos: ['VOL'], ovr: 81 },
      { name: 'Sylvinho', pos: ['LE','PE'], ovr: 86 },
      { name: 'Adilson', pos: ['ZAG'], ovr: 74 },
      { name: 'Gilmar', pos: ['VOL'], ovr: 75 },
      { name: 'Edu', pos: ['MEI'], ovr: 75 },
      { name: 'Fabinho', pos: ['ZAG'], ovr: 73 },
      { name: 'Luis Carlos', pos: ['PD','MD'], ovr: 72 },
      { name: 'Anderson', pos: ['ATA'], ovr: 71 },
    ]},
  { id: 'vasco2000', club: 'Vasco', year: 2000, label: 'Vasco 2000 (Brasileiro + Mercosul)', coach: 'Oswaldo de Oliveira',
    colors: { p: '#000000', s: '#ffffff' },
    players: [
      { name: 'Carlos Germano', pos: ['GOL'], ovr: 82 },
      { name: 'Valber', pos: ['LD'], ovr: 77 },
      { name: 'Anderson Polga', pos: ['ZAG'], ovr: 80 },
      { name: 'Odvan', pos: ['ZAG'], ovr: 78 },
      { name: 'Felipe', pos: ['LE'], ovr: 79 },
      { name: 'Ramon', pos: ['MEI','PD'], ovr: 82 },
      { name: 'Juninho Paulista', pos: ['MEI','MD'], ovr: 84 },
      { name: 'Pedrinho', pos: ['MEI'], ovr: 80 },
      { name: 'Luizao', pos: ['ATA'], ovr: 86 },
      { name: 'Donizete', pos: ['ATA'], ovr: 84 },
      { name: 'Romario', pos: ['ATA'], ovr: 91 },
      { name: 'Sandro', pos: ['GOL'], ovr: 71 },
      { name: 'Valdir', pos: ['LD'], ovr: 73 },
      { name: 'Mauro Galvao', pos: ['ZAG'], ovr: 79 },
      { name: 'Everton', pos: ['ATA'], ovr: 73 },
      { name: 'Nasa', pos: ['VOL'], ovr: 77 },
      { name: 'Nilton', pos: ['VOL'], ovr: 76 },
      { name: 'Paulo Victor', pos: ['MEI','ME'], ovr: 74 },
      { name: 'Alexandre Pires', pos: ['ATA'], ovr: 75 },
      { name: 'Fabio Augusto', pos: ['LD'], ovr: 72 },
    ]},
  { id: 'athletico-pr2001', club: 'Athletico-PR', year: 2001, label: 'Athletico-PR 2001', coach: 'Geninho',
    colors: { p: '#c8102e', s: '#000000' },
    players: [
      { name: 'Flavio', pos: ['GOL'], ovr: 80 },
      { name: 'Alessandro', pos: ['LD'], ovr: 78 },
      { name: 'Rogerio Correa', pos: ['ZAG'], ovr: 78 },
      { name: 'Nem', pos: ['ZAG'], ovr: 79 },
      { name: 'Gustavo', pos: ['ZAG'], ovr: 80 },
      { name: 'Fabiano', pos: ['LE'], ovr: 77 },
      { name: 'Cocito', pos: ['VOL'], ovr: 78 },
      { name: 'Kleberson', pos: ['VOL','MEI'], ovr: 86 },
      { name: 'Adriano', pos: ['MEI'], ovr: 79 },
      { name: 'Kleber', pos: ['ATA'], ovr: 84 },
      { name: 'Alex Mineiro', pos: ['ATA'], ovr: 85 },
      { name: 'Igor', pos: ['LD'], ovr: 73 },
      { name: 'Pires', pos: ['MEI','MD'], ovr: 72 },
      { name: 'Rodriguinho', pos: ['MEI'], ovr: 71 },
      { name: 'Souza', pos: ['ATA'], ovr: 74 },
      { name: 'Ilan', pos: ['ATA'], ovr: 73 },
      { name: 'Adauto', pos: ['ATA'], ovr: 72 },
      { name: 'Marcos', pos: ['ZAG'], ovr: 71 },
      { name: 'Ederson', pos: ['MEI','ME'], ovr: 72 },
      { name: 'Chico', pos: ['LD'], ovr: 71 },
    ]},
  { id: 'santos2002', club: 'Santos', year: 2002, label: 'Santos 2002 (Meninos da Vila)', coach: 'Emerson Leao',
    colors: { p: '#000000', s: '#ffffff' },
    players: [
      { name: 'Fabio Costa', pos: ['GOL'], ovr: 81 },
      { name: 'Maurinho', pos: ['LD'], ovr: 78 },
      { name: 'Andre Luis', pos: ['ZAG'], ovr: 77 },
      { name: 'Alex', pos: ['ZAG'], ovr: 78 },
      { name: 'Leo', pos: ['LE'], ovr: 79 },
      { name: 'Paulo Almeida', pos: ['VOL'], ovr: 77 },
      { name: 'Renato', pos: ['VOL','MEI'], ovr: 78 },
      { name: 'Elano', pos: ['MEI'], ovr: 84 },
      { name: 'Diego', pos: ['MEI','PD'], ovr: 85 },
      { name: 'Robinho', pos: ['ATA','PE'], ovr: 92 },
      { name: 'William', pos: ['PE'], ovr: 76 },
      { name: 'Julio Cesar', pos: ['GOL'], ovr: 73 },
      { name: 'Wellington', pos: ['MEI','MD'], ovr: 72 },
      { name: 'Alexandre', pos: ['ATA'], ovr: 73 },
      { name: 'Robert', pos: ['ATA'], ovr: 74 },
      { name: 'Michel', pos: ['ATA'], ovr: 71 },
      { name: 'Adriano', pos: ['ZAG'], ovr: 73 },
      { name: 'Felipe', pos: ['LD'], ovr: 72 },
      { name: 'Marcos', pos: ['VOL'], ovr: 71 },
      { name: 'Junior', pos: ['MEI'], ovr: 70 },
    ]},
  { id: 'cruzeiro2003', club: 'Cruzeiro', year: 2003, label: 'Cruzeiro 2003 (Triplice Coroa)', coach: 'Vanderlei Luxemburgo',
    colors: { p: '#1c3f94', s: '#ffffff' },
    players: [
      { name: 'Gomes', pos: ['GOL'], ovr: 80 },
      { name: 'Maurinho', pos: ['LD'], ovr: 78 },
      { name: 'Cris', pos: ['ZAG'], ovr: 79 },
      { name: 'Edu Dracena', pos: ['ZAG'], ovr: 82 },
      { name: 'Leandro', pos: ['LE'], ovr: 78 },
      { name: 'Maldonado', pos: ['VOL'], ovr: 79 },
      { name: 'Augusto Recife', pos: ['VOL'], ovr: 77 },
      { name: 'Wendell', pos: ['MEI','ME'], ovr: 78 },
      { name: 'Alex', pos: ['MEI'], ovr: 90 },
      { name: 'Aristizabal', pos: ['ATA'], ovr: 82 },
      { name: 'Mota', pos: ['ATA'], ovr: 79 },
      { name: 'Maicon', pos: ['LD'], ovr: 76 },
      { name: 'Luisao', pos: ['ZAG'], ovr: 79 },
      { name: 'Felipe Melo', pos: ['VOL'], ovr: 78 },
      { name: 'Zinho', pos: ['MEI','MD'], ovr: 73 },
      { name: 'Marcio Nobre', pos: ['ATA'], ovr: 75 },
      { name: 'Deivid', pos: ['ATA'], ovr: 78 },
      { name: 'Alex Alves', pos: ['ATA'], ovr: 74 },
      { name: 'Martinez', pos: ['MEI'], ovr: 73 },
      { name: 'Thiago', pos: ['ZAG'], ovr: 75 },
    ]},
  { id: 'santos2004', club: 'Santos', year: 2004, label: 'Santos 2004 (Bicampeonato + 103 gols)', coach: 'Vanderlei Luxemburgo',
    colors: { p: '#000000', s: '#ffffff' },
    players: [
      { name: 'Mauro', pos: ['GOL'], ovr: 78 },
      { name: 'Flavio', pos: ['LD'], ovr: 75 },
      { name: 'Avaulos', pos: ['ZAG'], ovr: 77 },
      { name: 'Leonardo', pos: ['ZAG'], ovr: 77 },
      { name: 'Leo', pos: ['LE'], ovr: 79 },
      { name: 'Fabinho', pos: ['VOL'], ovr: 77 },
      { name: 'Preto Casagrande', pos: ['VOL','MEI'], ovr: 76 },
      { name: 'Ricardinho', pos: ['MEI','ME'], ovr: 84 },
      { name: 'Elano', pos: ['MEI'], ovr: 85 },
      { name: 'Robinho', pos: ['ATA','PE'], ovr: 91 },
      { name: 'Deivid', pos: ['ATA'], ovr: 84 },
      { name: 'Paulo Cesar', pos: ['LD'], ovr: 73 },
      { name: 'Marcinho', pos: ['MEI','MD'], ovr: 72 },
      { name: 'Basilio', pos: ['ATA'], ovr: 71 },
      { name: 'William', pos: ['ATA','PE'], ovr: 73 },
      { name: 'Adriano', pos: ['ZAG'], ovr: 73 },
      { name: 'Rodrigo', pos: ['LD'], ovr: 71 },
      { name: 'Gabriel', pos: ['ZAG'], ovr: 72 },
      { name: 'Marquinhos', pos: ['VOL'], ovr: 71 },
      { name: 'Adriano Jr', pos: ['ATA'], ovr: 70 },
    ]},
  { id: 'corinthians2005', club: 'Corinthians', year: 2005, label: 'Corinthians 2005', coach: 'Antonio Lopes',
    colors: { p: '#000000', s: '#ffffff' },
    players: [
      { name: 'Fabio Costa', pos: ['GOL'], ovr: 80 },
      { name: 'Marinho', pos: ['LD'], ovr: 76 },
      { name: 'Wendel', pos: ['ZAG'], ovr: 77 },
      { name: 'Betao', pos: ['ZAG'], ovr: 73 },
      { name: 'Gustavo Nery', pos: ['LE'], ovr: 80 },
      { name: 'Coelho', pos: ['ZAG'], ovr: 76 },
      { name: 'Marcelo Mattos', pos: ['VOL'], ovr: 79 },
      { name: 'Bruno Octavio', pos: ['VOL','MEI'], ovr: 76 },
      { name: 'Carlos Alberto', pos: ['MEI'], ovr: 81 },
      { name: 'Tevez', pos: ['ATA'], ovr: 93 },
      { name: 'Nilmar', pos: ['ATA'], ovr: 80 },
      { name: 'Julio Cesar', pos: ['GOL'], ovr: 74 },
      { name: 'Sebastian Dominguez', pos: ['ZAG'], ovr: 76 },
      { name: 'Mascherano', pos: ['VOL'], ovr: 86 },
      { name: 'Roger', pos: ['MEI','ME'], ovr: 78 },
      { name: 'Jo', pos: ['ATA'], ovr: 76 },
      { name: 'Wescley', pos: ['MEI'], ovr: 72 },
      { name: 'Eduardo Ratinho', pos: ['MEI','MD'], ovr: 71 },
      { name: 'Rodrigo', pos: ['LD'], ovr: 71 },
      { name: 'Rosinei', pos: ['MEI'], ovr: 77 },
    ]},
  { id: 'sao-paulo2006', club: 'Sao Paulo', year: 2006, label: 'Sao Paulo 2006', coach: 'Muricy Ramalho',
    colors: { p: '#c8102e', s: '#000000' },
    players: [
      { name: 'Rogerio Ceni', pos: ['GOL'], ovr: 92 },
      { name: 'Ilsinho', pos: ['LD','PD'], ovr: 78 },
      { name: 'Fabao', pos: ['ZAG'], ovr: 81 },
      { name: 'Miranda', pos: ['ZAG'], ovr: 82 },
      { name: 'Junior', pos: ['LE'], ovr: 77 },
      { name: 'Mineiro', pos: ['VOL'], ovr: 81 },
      { name: 'Josue', pos: ['VOL','MEI'], ovr: 80 },
      { name: 'Souza', pos: ['MEI','ME'], ovr: 78 },
      { name: 'Danilo', pos: ['MEI'], ovr: 80 },
      { name: 'Leandro', pos: ['PD','PE'], ovr: 77 },
      { name: 'Aloisio', pos: ['ATA'], ovr: 81 },
      { name: 'Lugano', pos: ['ZAG'], ovr: 82 },
      { name: 'Alex Silva', pos: ['ZAG'], ovr: 73 },
      { name: 'Cicinho', pos: ['LD','PD'], ovr: 79 },
      { name: 'Thiago Ribeiro', pos: ['MEI','MD'], ovr: 75 },
      { name: 'Richarlyson', pos: ['MEI'], ovr: 74 },
      { name: 'Lenilson', pos: ['ATA'], ovr: 73 },
      { name: 'Anderson', pos: ['ATA'], ovr: 72 },
      { name: 'Rodrigo', pos: ['LD'], ovr: 71 },
      { name: 'Edcarlos', pos: ['ZAG'], ovr: 76 },
    ]},
  { id: 'sao-paulo2007', club: 'Sao Paulo', year: 2007, label: 'Sao Paulo 2007 (Bicampeonato)', coach: 'Muricy Ramalho',
    colors: { p: '#c8102e', s: '#000000' },
    players: [
      { name: 'Rogerio Ceni', pos: ['GOL'], ovr: 89 },
      { name: 'Ilsinho', pos: ['LD','PD'], ovr: 78 },
      { name: 'Fabao', pos: ['ZAG'], ovr: 80 },
      { name: 'Miranda', pos: ['ZAG'], ovr: 84 },
      { name: 'Lugano', pos: ['ZAG'], ovr: 84 },
      { name: 'Junior', pos: ['LE'], ovr: 77 },
      { name: 'Mineiro', pos: ['VOL'], ovr: 82 },
      { name: 'Josue', pos: ['VOL','MEI'], ovr: 81 },
      { name: 'Danilo', pos: ['MEI','ME'], ovr: 81 },
      { name: 'Hernanes', pos: ['MEI'], ovr: 86 },
      { name: 'Grafite', pos: ['ATA'], ovr: 85 },
      { name: 'Aloisio', pos: ['ATA'], ovr: 80 },
      { name: 'Borges', pos: ['ATA'], ovr: 79 },
      { name: 'Cicinho', pos: ['LD','PD'], ovr: 79 },
      { name: 'Diego Tardelli', pos: ['ATA'], ovr: 80 },
      { name: 'Alex Silva', pos: ['ZAG'], ovr: 74 },
      { name: 'Souza', pos: ['MEI','MD'], ovr: 79 },
      { name: 'Lucas', pos: ['PD'], ovr: 75 },
      { name: 'Pablo', pos: ['ZAG'], ovr: 73 },
      { name: 'Rodrigo', pos: ['LD'], ovr: 70 },
    ]},
  { id: 'sao-paulo2008', club: 'Sao Paulo', year: 2008, label: 'Sao Paulo 2008 (Tricampeonato)', coach: 'Muricy Ramalho',
    colors: { p: '#c8102e', s: '#000000' },
    players: [
      { name: 'Rogerio Ceni', pos: ['GOL'], ovr: 88 },
      { name: 'Ilsinho', pos: ['LD','PD'], ovr: 77 },
      { name: 'Fabao', pos: ['ZAG'], ovr: 80 },
      { name: 'Miranda', pos: ['ZAG'], ovr: 85 },
      { name: 'Lugano', pos: ['ZAG'], ovr: 84 },
      { name: 'Junior', pos: ['LE'], ovr: 76 },
      { name: 'Mineiro', pos: ['VOL'], ovr: 82 },
      { name: 'Josue', pos: ['VOL','MEI'], ovr: 80 },
      { name: 'Danilo', pos: ['MEI'], ovr: 80 },
      { name: 'Hernanes', pos: ['MEI','ME'], ovr: 88 },
      { name: 'Borges', pos: ['ATA'], ovr: 80 },
      { name: 'Aloisio', pos: ['ATA'], ovr: 79 },
      { name: 'Diego Tardelli', pos: ['ATA'], ovr: 81 },
      { name: 'Grafite', pos: ['ATA'], ovr: 82 },
      { name: 'Alex Silva', pos: ['ZAG'], ovr: 74 },
      { name: 'Eder Luis', pos: ['ATA'], ovr: 74 },
      { name: 'Rafael', pos: ['ZAG'], ovr: 73 },
      { name: 'Jadson', pos: ['MEI'], ovr: 77 },
      { name: 'Junior Cesar', pos: ['LE'], ovr: 72 },
      { name: 'Souza', pos: ['MEI','MD'], ovr: 79 },
    ]},
  { id: 'flamengo2009', club: 'Flamengo', year: 2009, label: 'Flamengo 2009 (Hexacampeonato)', coach: 'Andrade',
    colors: { p: '#c8102e', s: '#000000' },
    players: [
      { name: 'Bruno', pos: ['GOL'], ovr: 87 },
      { name: 'Leo Moura', pos: ['LD','PD'], ovr: 86 },
      { name: 'David Braz', pos: ['ZAG'], ovr: 80 },
      { name: 'Ronaldo Angelim', pos: ['ZAG'], ovr: 82 },
      { name: 'Juan', pos: ['ZAG'], ovr: 84 },
      { name: 'Gonzalez', pos: ['LE'], ovr: 79 },
      { name: 'Airton', pos: ['VOL'], ovr: 79 },
      { name: 'Willians', pos: ['VOL'], ovr: 80 },
      { name: 'Petkovic', pos: ['MEI'], ovr: 85 },
      { name: 'Adriano', pos: ['ATA'], ovr: 91 },
      { name: 'Obina', pos: ['ATA'], ovr: 80 },
      { name: 'Ze Roberto', pos: ['MEI','ATA'], ovr: 80 },
      { name: 'Kleberson', pos: ['VOL','MEI'], ovr: 81 },
      { name: 'Josiel', pos: ['PD','MD'], ovr: 76 },
      { name: 'Everton', pos: ['ATA'], ovr: 78 },
      { name: 'Alvaro', pos: ['ZAG'], ovr: 78 },
      { name: 'Fierro', pos: ['MEI','ME'], ovr: 75 },
      { name: 'Camacho', pos: ['ATA'], ovr: 72 },
      { name: 'Denis Marques', pos: ['ATA'], ovr: 72 },
      { name: 'Bruno Mezenga', pos: ['ATA'], ovr: 73 },
    ]},
  { id: 'santos2010', club: 'Santos', year: 2010, label: 'Santos 2010 (Copa do Brasil)', coach: 'Dorival Junior',
    colors: { p: '#000000', s: '#ffffff' },
    players: [
      { name: 'Rafael', pos: ['GOL'], ovr: 80 },
      { name: 'Danilo', pos: ['LD','PD'], ovr: 83 },
      { name: 'Edu Dracena', pos: ['ZAG'], ovr: 83 },
      { name: 'Durval', pos: ['ZAG'], ovr: 80 },
      { name: 'Leo', pos: ['LE'], ovr: 81 },
      { name: 'Adriano', pos: ['VOL'], ovr: 79 },
      { name: 'Arouca', pos: ['VOL','MEI'], ovr: 83 },
      { name: 'Elano', pos: ['MEI'], ovr: 87 },
      { name: 'Paulo Henrique Ganso', pos: ['MEI','MD'], ovr: 88 },
      { name: 'Robinho', pos: ['PE','ATA'], ovr: 89 },
      { name: 'Neymar', pos: ['ATA','PE'], ovr: 93 },
      { name: 'Andre', pos: ['ATA'], ovr: 82 },
      { name: 'Ze Eduardo', pos: ['ATA'], ovr: 79 },
      { name: 'Alan Kardec', pos: ['ATA'], ovr: 78 },
      { name: 'Alan Patrick', pos: ['MEI'], ovr: 78 },
      { name: 'Alex Sandro', pos: ['LE'], ovr: 78 },
      { name: 'Wesley', pos: ['VOL'], ovr: 79 },
      { name: 'Bruno Rodrigo', pos: ['ZAG'], ovr: 79 },
      { name: 'Felipe', pos: ['GOL'], ovr: 75 },
      { name: 'Para', pos: ['LD'], ovr: 78 },
    ]},
  { id: 'fluminense2010', club: 'Fluminense', year: 2010, label: 'Fluminense 2010 (Tricampeonato)', coach: 'Muricy Ramalho',
    colors: { p: '#7a1e3c', s: '#006437' },
    players: [
      { name: 'Ricardo Berna', pos: ['GOL'], ovr: 79 },
      { name: 'Mariano', pos: ['LD','MD'], ovr: 83 },
      { name: 'Gum', pos: ['ZAG'], ovr: 81 },
      { name: 'Leandro Euzebio', pos: ['ZAG'], ovr: 80 },
      { name: 'Carlinhos', pos: ['LE'], ovr: 79 },
      { name: 'Diguinho', pos: ['VOL','MC'], ovr: 80 },
      { name: 'Deco', pos: ['MC','MEI'], ovr: 85 },
      { name: 'Conca', pos: ['MEI','MC'], ovr: 88 },
      { name: 'Emerson Sheik', pos: ['ATA','PE'], ovr: 79 },
      { name: 'Washington', pos: ['ATA'], ovr: 82 },
      { name: 'Fred', pos: ['ATA'], ovr: 86 },
      { name: 'Fernando Henrique', pos: ['GOL'], ovr: 76 },
      { name: 'Valencia', pos: ['VOL'], ovr: 78 },
      { name: 'Rodrigo Souto', pos: ['VOL','MC'], ovr: 77 },
      { name: 'Julio Cesar', pos: ['LE','ME'], ovr: 76 },
      { name: 'Thiago Neves', pos: ['MEI','PE'], ovr: 76 },
      { name: 'Marquinho', pos: ['ME','MC'], ovr: 76 },
      { name: 'Rodrigueiro', pos: ['MEI','ME'], ovr: 74 },
      { name: 'Alan', pos: ['ATA','PD'], ovr: 74 },
      { name: 'Andre Luis', pos: ['ZAG'], ovr: 73 },
    ]},
  { id: 'santos2011', club: 'Santos', year: 2011, label: 'Santos 2011 (Libertadores)', coach: 'Adilson Batista',
    colors: { p: '#000000', s: '#ffffff' },
    players: [
      { name: 'Rafael', pos: ['GOL'], ovr: 82 },
      { name: 'Danilo', pos: ['LD','PD'], ovr: 85 },
      { name: 'Edu Dracena', pos: ['ZAG'], ovr: 84 },
      { name: 'Durval', pos: ['ZAG'], ovr: 78 },
      { name: 'Leo', pos: ['LE'], ovr: 82 },
      { name: 'Adriano', pos: ['VOL'], ovr: 79 },
      { name: 'Arouca', pos: ['VOL','MEI'], ovr: 84 },
      { name: 'Elano', pos: ['MEI'], ovr: 87 },
      { name: 'Paulo Henrique Ganso', pos: ['MEI','MD'], ovr: 89 },
      { name: 'Neymar', pos: ['ATA','PE'], ovr: 95 },
      { name: 'Ze Eduardo', pos: ['ATA'], ovr: 80 },
      { name: 'Andre', pos: ['ATA'], ovr: 83 },
      { name: 'Robinho', pos: ['PE','ATA'], ovr: 87 },
      { name: 'Alex Sandro', pos: ['LE'], ovr: 80 },
      { name: 'Bruno Rodrigo', pos: ['ZAG'], ovr: 79 },
      { name: 'Jonathan', pos: ['LD'], ovr: 76 },
      { name: 'Alan Kardec', pos: ['ATA'], ovr: 78 },
      { name: 'Maikon Leite', pos: ['ATA','PD'], ovr: 78 },
      { name: 'Felipe', pos: ['GOL'], ovr: 77 },
      { name: 'Marquinhos', pos: ['VOL'], ovr: 78 },
    ]},
  { id: 'corinthians2011', club: 'Corinthians', year: 2011, label: 'Corinthians 2011 (Pentacampeonato)', coach: 'Tite',
    colors: { p: '#000000', s: '#ffffff' },
    players: [
      { name: 'Cassio', pos: ['GOL'], ovr: 87 },
      { name: 'Alessandro', pos: ['LD'], ovr: 80 },
      { name: 'Chicao', pos: ['ZAG'], ovr: 84 },
      { name: 'Leandro Castan', pos: ['ZAG'], ovr: 84 },
      { name: 'Fabio Santos', pos: ['LE'], ovr: 82 },
      { name: 'Ralf', pos: ['VOL'], ovr: 85 },
      { name: 'Paulinho', pos: ['VOL','MEI'], ovr: 88 },
      { name: 'Danilo', pos: ['MEI','PD'], ovr: 85 },
      { name: 'Alex', pos: ['MEI'], ovr: 85 },
      { name: 'Paolo Guerrero', pos: ['ATA'], ovr: 88 },
      { name: 'Emerson Sheik', pos: ['ATA','MEI'], ovr: 85 },
      { name: 'Jorge Henrique', pos: ['PD','ATA'], ovr: 80 },
      { name: 'Liedson', pos: ['ATA'], ovr: 82 },
      { name: 'Willian', pos: ['PD','MEI'], ovr: 84 },
      { name: 'Adriano', pos: ['ATA'], ovr: 80 },
      { name: 'Romarinho', pos: ['ATA'], ovr: 78 },
      { name: 'Paulo Andre', pos: ['ZAG'], ovr: 80 },
      { name: 'Julio Cesar', pos: ['GOL'], ovr: 80 },
      { name: 'Douglas', pos: ['MEI','ME'], ovr: 74 },
      { name: 'Guilherme', pos: ['ATA'], ovr: 73 },
    ]},
  { id: 'fluminense2012', club: 'Fluminense', year: 2012, label: 'Fluminense 2012 (Tetracampeonato)', coach: 'Abel Braga',
    colors: { p: '#7a1e3c', s: '#006437' },
    players: [
      { name: 'Diego Cavalieri', pos: ['GOL'], ovr: 84 },
      { name: 'Bruno', pos: ['LD'], ovr: 81 },
      { name: 'Gum', pos: ['ZAG'], ovr: 85 },
      { name: 'Leandro Euzebio', pos: ['ZAG'], ovr: 82 },
      { name: 'Carlinhos', pos: ['LE'], ovr: 82 },
      { name: 'Edinho', pos: ['VOL','MEI'], ovr: 78 },
      { name: 'Jean', pos: ['VOL'], ovr: 79 },
      { name: 'Deco', pos: ['MEI'], ovr: 87 },
      { name: 'Thiago Neves', pos: ['MEI','MD'], ovr: 88 },
      { name: 'Wellington Nem', pos: ['PD','MEI'], ovr: 83 },
      { name: 'Fred', pos: ['ATA'], ovr: 90 },
      { name: 'Rafael Sobis', pos: ['ATA'], ovr: 82 },
      { name: 'Rafael Moura', pos: ['ATA'], ovr: 79 },
      { name: 'Wagner', pos: ['MEI'], ovr: 76 },
      { name: 'Lanzini', pos: ['MEI','ME'], ovr: 80 },
      { name: 'Michael', pos: ['MEI'], ovr: 74 },
      { name: 'Rodrigo Lindoso', pos: ['VOL'], ovr: 78 },
      { name: 'Samuel', pos: ['ATA'], ovr: 73 },
      { name: 'Martinuccio', pos: ['MEI','MD'], ovr: 74 },
      { name: 'Anderson', pos: ['ZAG'], ovr: 78 },
    ]},
  { id: 'atletico-mg2013', club: 'Atletico-MG', year: 2013, label: 'Atletico-MG 2013 (Libertadores)', coach: 'Cuca',
    colors: { p: '#000000', s: '#ffffff' },
    players: [
      { name: 'Victor', pos: ['GOL'], ovr: 93 },
      { name: 'Marcos Rocha', pos: ['LD'], ovr: 83 },
      { name: 'Rever', pos: ['ZAG'], ovr: 84 },
      { name: 'Leonardo Silva', pos: ['ZAG'], ovr: 83 },
      { name: 'Junior Cesar', pos: ['LE'], ovr: 80 },
      { name: 'Richarlyson', pos: ['LE','VOL'], ovr: 82 },
      { name: 'Pierre', pos: ['VOL'], ovr: 85 },
      { name: 'Josue', pos: ['VOL','MEI'], ovr: 82 },
      { name: 'Ronaldinho Gaucho', pos: ['MEI'], ovr: 91 },
      { name: 'Diego Tardelli', pos: ['MEI','ATA'], ovr: 89 },
      { name: 'Bernard', pos: ['PD','MEI'], ovr: 88 },
      { name: 'Jo', pos: ['ATA'], ovr: 86 },
      { name: 'Guilherme', pos: ['ATA'], ovr: 81 },
      { name: 'Luan', pos: ['ATA','PE'], ovr: 82 },
      { name: 'Alecsandro', pos: ['ATA'], ovr: 79 },
      { name: 'Michel', pos: ['LD'], ovr: 80 },
      { name: 'Jemerson', pos: ['ZAG'], ovr: 80 },
      { name: 'Rafael Carioca', pos: ['VOL'], ovr: 79 },
      { name: 'Leandro Donizete', pos: ['MEI','VOL'], ovr: 83 },
      { name: 'Douglas Santos', pos: ['LE'], ovr: 77 },
    ]},
  { id: 'cruzeiro2013', club: 'Cruzeiro', year: 2013, label: 'Cruzeiro 2013 (Brasileiro)', coach: 'Marcelo Oliveira',
    colors: { p: '#1c3f94', s: '#ffffff' },
    players: [
      { name: 'Fabio', pos: ['GOL'], ovr: 87 },
      { name: 'Ceara', pos: ['LD'], ovr: 82 },
      { name: 'Bruno Rodrigo', pos: ['ZAG'], ovr: 81 },
      { name: 'Dede', pos: ['ZAG'], ovr: 88 },
      { name: 'Egidio', pos: ['LE'], ovr: 80 },
      { name: 'Lucas Silva', pos: ['VOL'], ovr: 83 },
      { name: 'Nilton', pos: ['VOL'], ovr: 84 },
      { name: 'Everton Ribeiro', pos: ['MEI','PD'], ovr: 91 },
      { name: 'Ricardo Goulart', pos: ['MEI','ATA'], ovr: 88 },
      { name: 'Borges', pos: ['ATA'], ovr: 81 },
      { name: 'Marcelo Moreno', pos: ['ATA'], ovr: 83 },
      { name: 'Mayke', pos: ['LD'], ovr: 78 },
      { name: 'Leo', pos: ['ZAG'], ovr: 79 },
      { name: 'Willian', pos: ['ATA','PE'], ovr: 84 },
      { name: 'Julio Baptista', pos: ['MEI','ME'], ovr: 79 },
      { name: 'Diego Souza', pos: ['MEI'], ovr: 80 },
      { name: 'Dagoberto', pos: ['ATA'], ovr: 75 },
      { name: 'Rafael', pos: ['GOL'], ovr: 75 },
      { name: 'Cris', pos: ['ZAG'], ovr: 78 },
      { name: 'Samudio', pos: ['LE'], ovr: 73 },
    ]},
  { id: 'cruzeiro2014', club: 'Cruzeiro', year: 2014, label: 'Cruzeiro 2014 (Tetracampeonato)', coach: 'Marcelo Oliveira',
    colors: { p: '#1c3f94', s: '#ffffff' },
    players: [
      { name: 'Fabio', pos: ['GOL'], ovr: 87 },
      { name: 'Ceara', pos: ['LD'], ovr: 82 },
      { name: 'Dede', pos: ['ZAG'], ovr: 90 },
      { name: 'Bruno Rodrigo', pos: ['ZAG'], ovr: 81 },
      { name: 'Egidio', pos: ['LE'], ovr: 81 },
      { name: 'Lucas Silva', pos: ['VOL'], ovr: 84 },
      { name: 'Henrique', pos: ['VOL'], ovr: 81 },
      { name: 'Nilton', pos: ['VOL'], ovr: 83 },
      { name: 'Everton Ribeiro', pos: ['MEI','PD'], ovr: 90 },
      { name: 'Ricardo Goulart', pos: ['MEI','ATA'], ovr: 89 },
      { name: 'Marcelo Moreno', pos: ['ATA'], ovr: 85 },
      { name: 'Willian', pos: ['ATA','PE'], ovr: 83 },
      { name: 'Borges', pos: ['ATA'], ovr: 79 },
      { name: 'Dagoberto', pos: ['ATA'], ovr: 74 },
      { name: 'Luan', pos: ['ATA'], ovr: 76 },
      { name: 'Mayke', pos: ['LD'], ovr: 80 },
      { name: 'Leo', pos: ['ZAG'], ovr: 80 },
      { name: 'Elisson', pos: ['GOL'], ovr: 73 },
      { name: 'Manoel', pos: ['ZAG'], ovr: 78 },
      { name: 'Bruno Ramires', pos: ['VOL'], ovr: 79 },
    ]},
  { id: 'corinthians2015', club: 'Corinthians', year: 2015, label: 'Corinthians 2015 (Hexacampeonato)', coach: 'Tite',
    colors: { p: '#000000', s: '#ffffff' },
    players: [
      { name: 'Cassio', pos: ['GOL'], ovr: 89 },
      { name: 'Fagner', pos: ['LD'], ovr: 82 },
      { name: 'Gil Baiano', pos: ['ZAG'], ovr: 87 },
      { name: 'Edu Dracena', pos: ['ZAG'], ovr: 84 },
      { name: 'Guilherme Arana', pos: ['LE'], ovr: 83 },
      { name: 'Ralf', pos: ['VOL'], ovr: 85 },
      { name: 'Elias', pos: ['VOL','MEI'], ovr: 84 },
      { name: 'Renato Augusto', pos: ['MEI','MD'], ovr: 86 },
      { name: 'Jadson', pos: ['MEI'], ovr: 88 },
      { name: 'Roberto Firmino', pos: ['ATA','MEI'], ovr: 85 },
      { name: 'Malcom', pos: ['PD','ATA'], ovr: 82 },
      { name: 'Alessandro', pos: ['LD'], ovr: 78 },
      { name: 'Chicao', pos: ['ZAG'], ovr: 82 },
      { name: 'Rodriguinho', pos: ['MEI','ME'], ovr: 83 },
      { name: 'Willian Arao', pos: ['VOL'], ovr: 80 },
      { name: 'Petros', pos: ['VOL'], ovr: 77 },
      { name: 'Lucca', pos: ['ATA'], ovr: 73 },
      { name: 'Luciano', pos: ['ATA'], ovr: 79 },
      { name: 'Danilo Avelar', pos: ['LE'], ovr: 77 },
      { name: 'Uendel', pos: ['LE'], ovr: 78 },
    ]},
  { id: 'palmeiras2016', club: 'Palmeiras', year: 2016, label: 'Palmeiras 2016', coach: 'Cuca',
    colors: { p: '#006437', s: '#ffffff' },
    players: [
      { name: 'Fernando Prass', pos: ['GOL'], ovr: 84 },
      { name: 'Marcos Rocha', pos: ['LD'], ovr: 82 },
      { name: 'Edu Dracena', pos: ['ZAG'], ovr: 83 },
      { name: 'Mina', pos: ['ZAG'], ovr: 84 },
      { name: 'Egidio', pos: ['LE'], ovr: 81 },
      { name: 'Arouca', pos: ['VOL'], ovr: 83 },
      { name: 'Felipe Melo', pos: ['VOL'], ovr: 87 },
      { name: 'Thiago Santos', pos: ['VOL'], ovr: 79 },
      { name: 'Allione', pos: ['MEI','PD'], ovr: 82 },
      { name: 'Dudu', pos: ['PD','ATA'], ovr: 88 },
      { name: 'Gabriel Jesus', pos: ['ATA'], ovr: 91 },
      { name: 'Cleiton Xavier', pos: ['MEI'], ovr: 79 },
      { name: 'Tche Tche', pos: ['MEI','VOL'], ovr: 80 },
      { name: 'Rafael Marques', pos: ['ATA'], ovr: 77 },
      { name: 'Willian', pos: ['ATA','PE'], ovr: 78 },
      { name: 'Mauricio Ramos', pos: ['ZAG'], ovr: 76 },
      { name: 'Jean', pos: ['LD'], ovr: 78 },
      { name: 'Thiago Martins', pos: ['ZAG'], ovr: 79 },
      { name: 'Raphael Veiga', pos: ['MEI','MD'], ovr: 80 },
      { name: 'Roger Guedes', pos: ['ATA','PE'], ovr: 80 },
    ]},
  { id: 'corinthians2017', club: 'Corinthians', year: 2017, label: 'Corinthians 2017 (Heptacampeonato)', coach: 'Fabio Carille',
    colors: { p: '#000000', s: '#ffffff' },
    players: [
      { name: 'Cassio', pos: ['GOL'], ovr: 90 },
      { name: 'Fagner', pos: ['LD'], ovr: 85 },
      { name: 'Pablo', pos: ['ZAG'], ovr: 82 },
      { name: 'Balbuena', pos: ['ZAG'], ovr: 84 },
      { name: 'Guilherme Arana', pos: ['LE'], ovr: 83 },
      { name: 'Ralf', pos: ['VOL'], ovr: 84 },
      { name: 'Maycon', pos: ['VOL'], ovr: 85 },
      { name: 'Jadson', pos: ['MEI'], ovr: 89 },
      { name: 'Marlone', pos: ['MEI','ME'], ovr: 82 },
      { name: 'Jo', pos: ['ATA'], ovr: 87 },
      { name: 'Romero', pos: ['PD','ATA'], ovr: 82 },
      { name: 'Malcom', pos: ['PD','ATA'], ovr: 84 },
      { name: 'Marquinhos Gabriel', pos: ['PD'], ovr: 80 },
      { name: 'Rodriguinho', pos: ['MEI'], ovr: 84 },
      { name: 'Kazim', pos: ['ATA'], ovr: 73 },
      { name: 'Leo Santos', pos: ['ZAG'], ovr: 78 },
      { name: 'Camacho', pos: ['MEI','MD'], ovr: 74 },
      { name: 'Mendoza', pos: ['PD','MD'], ovr: 74 },
      { name: 'Carlos', pos: ['LD'], ovr: 71 },
      { name: 'Jo (reserva)', pos: ['ATA'], ovr: 75 },
    ]},
  { id: 'palmeiras2018', club: 'Palmeiras', year: 2018, label: 'Palmeiras 2018 (80 pontos recorde)', coach: 'Luiz Felipe Scolari',
    colors: { p: '#006437', s: '#ffffff' },
    players: [
      { name: 'Weverton', pos: ['GOL'], ovr: 89 },
      { name: 'Marcos Rocha', pos: ['LD'], ovr: 84 },
      { name: 'Gustavo Gomez', pos: ['ZAG'], ovr: 88 },
      { name: 'Luan', pos: ['ZAG'], ovr: 83 },
      { name: 'Diogo Barbosa', pos: ['LE'], ovr: 82 },
      { name: 'Felipe Melo', pos: ['VOL'], ovr: 88 },
      { name: 'Bruno Henrique', pos: ['VOL'], ovr: 84 },
      { name: 'Ze Rafael', pos: ['VOL','MEI'], ovr: 83 },
      { name: 'Hyoran', pos: ['MEI','PD'], ovr: 80 },
      { name: 'Dudu', pos: ['PD','ATA'], ovr: 92 },
      { name: 'Borja', pos: ['ATA'], ovr: 81 },
      { name: 'Lucas Lima', pos: ['MEI'], ovr: 82 },
      { name: 'Willian', pos: ['ATA','PE'], ovr: 82 },
      { name: 'Deyverson', pos: ['ATA'], ovr: 80 },
      { name: 'Moises', pos: ['VOL','LE'], ovr: 79 },
      { name: 'Mayke', pos: ['LD'], ovr: 80 },
      { name: 'Edu Dracena', pos: ['ZAG'], ovr: 82 },
      { name: 'Thiago Santos', pos: ['VOL'], ovr: 78 },
      { name: 'Rafael Marques', pos: ['ATA'], ovr: 76 },
      { name: 'Raphael Veiga', pos: ['MEI','ME'], ovr: 80 },
    ]},
  { id: 'athletico-pr2019', club: 'Athletico-PR', year: 2019, label: 'Athletico-PR 2019 (Copa do Brasil)', coach: 'Tiago Nunes',
    colors: { p: '#c8102e', s: '#000000' },
    players: [
      { name: 'Santos', pos: ['GOL'], ovr: 82 },
      { name: 'Marcio Azevedo', pos: ['LD'], ovr: 79 },
      { name: 'Pedro Henrique', pos: ['ZAG'], ovr: 80 },
      { name: 'Thiago Heleno', pos: ['ZAG'], ovr: 82 },
      { name: 'Leo Pereira', pos: ['LE'], ovr: 80 },
      { name: 'Christian', pos: ['VOL'], ovr: 83 },
      { name: 'Matheus Fernandes', pos: ['VOL'], ovr: 82 },
      { name: 'Bruno Guimaraes', pos: ['VOL','MEI'], ovr: 86 },
      { name: 'Nikao', pos: ['MEI','PD'], ovr: 88 },
      { name: 'Rony', pos: ['PD','ATA'], ovr: 86 },
      { name: 'Marco Ruben', pos: ['ATA'], ovr: 81 },
      { name: 'Jonathan', pos: ['GOL'], ovr: 75 },
      { name: 'Robson Bambu', pos: ['ZAG'], ovr: 79 },
      { name: 'Abner', pos: ['LE'], ovr: 77 },
      { name: 'Lucho Gonzalez', pos: ['MEI'], ovr: 83 },
      { name: 'Marcelo Cirino', pos: ['PE','ME'], ovr: 81 },
      { name: 'Wellington', pos: ['VOL'], ovr: 79 },
      { name: 'Jonathan Rios', pos: ['LD'], ovr: 78 },
      { name: 'Vitinho', pos: ['PD'], ovr: 80 },
      { name: 'Marcinho', pos: ['LD'], ovr: 76 },
    ]},
  { id: 'flamengo2019', club: 'Flamengo', year: 2019, label: 'Flamengo 2019 (Bicampeonato + Libertadores)', coach: 'Jorge Jesus',
    colors: { p: '#c8102e', s: '#000000' },
    players: [
      { name: 'Diego Alves', pos: ['GOL'], ovr: 87 },
      { name: 'Rafinha', pos: ['LD'], ovr: 86 },
      { name: 'Rodrigo Caio', pos: ['ZAG'], ovr: 86 },
      { name: 'Pablo Mari', pos: ['ZAG'], ovr: 85 },
      { name: 'Filipe Luis', pos: ['LE'], ovr: 91 },
      { name: 'Willian Arao', pos: ['VOL'], ovr: 88 },
      { name: 'Gerson', pos: ['MEI','VOL'], ovr: 90 },
      { name: 'Everton Ribeiro', pos: ['MEI','PD'], ovr: 91 },
      { name: 'Arrascaeta', pos: ['MEI','MD'], ovr: 92 },
      { name: 'Bruno Henrique', pos: ['PE','ATA'], ovr: 90 },
      { name: 'Gabigol', pos: ['ATA'], ovr: 97 },
      { name: 'Pedro', pos: ['ATA'], ovr: 88 },
      { name: 'Diego', pos: ['MEI'], ovr: 84 },
      { name: 'Cuellar', pos: ['VOL'], ovr: 85 },
      { name: 'Rodinei', pos: ['LD'], ovr: 82 },
      { name: 'Reinier', pos: ['MEI','ME'], ovr: 82 },
      { name: 'Michael', pos: ['ATA','PD'], ovr: 82 },
      { name: 'Thiago Maia', pos: ['VOL'], ovr: 83 },
      { name: 'Lincoln', pos: ['ATA'], ovr: 79 },
      { name: 'Leo Ortiz', pos: ['ZAG'], ovr: 80 },
    ]},
  { id: 'flamengo2020', club: 'Flamengo', year: 2020, label: 'Flamengo 2020 (Bicampeonato)', coach: 'Rogerio Ceni',
    colors: { p: '#c8102e', s: '#000000' },
    players: [
      { name: 'Diego Alves', pos: ['GOL'], ovr: 86 },
      { name: 'Rafinha', pos: ['LD'], ovr: 84 },
      { name: 'Rodrigo Caio', pos: ['ZAG'], ovr: 87 },
      { name: 'Leo Pereira', pos: ['ZAG'], ovr: 84 },
      { name: 'Filipe Luis', pos: ['LE'], ovr: 89 },
      { name: 'Willian Arao', pos: ['VOL'], ovr: 88 },
      { name: 'Gerson', pos: ['MEI','VOL'], ovr: 90 },
      { name: 'Everton Ribeiro', pos: ['MEI','PD'], ovr: 91 },
      { name: 'Arrascaeta', pos: ['MEI'], ovr: 91 },
      { name: 'Bruno Henrique', pos: ['PE','ATA'], ovr: 89 },
      { name: 'Gabigol', pos: ['ATA'], ovr: 96 },
      { name: 'Pedro', pos: ['ATA'], ovr: 90 },
      { name: 'Thiago Maia', pos: ['VOL'], ovr: 84 },
      { name: 'Michael', pos: ['ATA','PD'], ovr: 83 },
      { name: 'Rodinei', pos: ['LD'], ovr: 82 },
      { name: 'Diego', pos: ['MEI','MD'], ovr: 82 },
      { name: 'Vitinho', pos: ['PD','MD'], ovr: 81 },
      { name: 'Hugo Souza', pos: ['GOL'], ovr: 76 },
      { name: 'Rene', pos: ['LE'], ovr: 82 },
      { name: 'Leo Ortiz', pos: ['ZAG'], ovr: 80 },
    ]},
  { id: 'atletico-mg2021', club: 'Atletico-MG', year: 2021, label: 'Atletico-MG 2021 (Brasileiro + Copa do Brasil)', coach: 'Cuca',
    colors: { p: '#000000', s: '#ffffff' },
    players: [
      { name: 'Everson', pos: ['GOL'], ovr: 88 },
      { name: 'Marcos Rocha', pos: ['LD'], ovr: 83 },
      { name: 'Rever', pos: ['ZAG'], ovr: 82 },
      { name: 'Nathan Silva', pos: ['ZAG'], ovr: 85 },
      { name: 'Guilherme Arana', pos: ['LE'], ovr: 88 },
      { name: 'Allan', pos: ['VOL','MEI'], ovr: 86 },
      { name: 'Jair', pos: ['VOL'], ovr: 83 },
      { name: 'Zaracho', pos: ['MEI'], ovr: 87 },
      { name: 'Nacho Fernandez', pos: ['MEI','ME'], ovr: 90 },
      { name: 'Keno', pos: ['ATA','PE'], ovr: 85 },
      { name: 'Hulk', pos: ['ATA'], ovr: 94 },
      { name: 'Vargas', pos: ['MEI','PE'], ovr: 84 },
      { name: 'Savarino', pos: ['PE'], ovr: 82 },
      { name: 'Eduardo Sasha', pos: ['ATA'], ovr: 82 },
      { name: 'Tardelli', pos: ['ATA'], ovr: 79 },
      { name: 'Alisson', pos: ['ZAG','LD'], ovr: 83 },
      { name: 'Guga', pos: ['LD'], ovr: 80 },
      { name: 'Igor Gomes', pos: ['MEI'], ovr: 78 },
      { name: 'Hyoran', pos: ['MEI','MD'], ovr: 79 },
      { name: 'Rabelo', pos: ['VOL'], ovr: 76 },
    ]},
  { id: 'palmeiras2022', club: 'Palmeiras', year: 2022, label: 'Palmeiras 2022 (81 pontos RECORDE historico)', coach: 'Abel Ferreira',
    colors: { p: '#006437', s: '#ffffff' },
    players: [
      { name: 'Weverton', pos: ['GOL'], ovr: 92 },
      { name: 'Marcos Rocha', pos: ['LD'], ovr: 84 },
      { name: 'Gustavo Gomez', pos: ['ZAG'], ovr: 90 },
      { name: 'Murilo', pos: ['ZAG'], ovr: 87 },
      { name: 'Piquerez', pos: ['LE'], ovr: 89 },
      { name: 'Danilo', pos: ['VOL','MEI'], ovr: 88 },
      { name: 'Ze Rafael', pos: ['VOL'], ovr: 86 },
      { name: 'Atuesta', pos: ['VOL'], ovr: 81 },
      { name: 'Raphael Veiga', pos: ['MEI','ATA'], ovr: 90 },
      { name: 'Dudu', pos: ['PD','ATA'], ovr: 88 },
      { name: 'Flaco Lopez', pos: ['ATA'], ovr: 86 },
      { name: 'Rony', pos: ['PE','ATA'], ovr: 85 },
      { name: 'Endrick', pos: ['ATA'], ovr: 91 },
      { name: 'Mayke', pos: ['LD'], ovr: 81 },
      { name: 'Gabriel Menino', pos: ['VOL'], ovr: 82 },
      { name: 'Luan', pos: ['ZAG'], ovr: 80 },
      { name: 'Vanderlan', pos: ['LE'], ovr: 78 },
      { name: 'Pedro Geromel', pos: ['ZAG'], ovr: 79 },
      { name: 'Jose Manuel Lopez', pos: ['ATA'], ovr: 75 },
      { name: 'Jhon Jhon', pos: ['MEI'], ovr: 79 },
    ]},
  { id: 'athletico-pr2022', club: 'Athletico-PR', year: 2022, label: 'Athletico-PR 2022 (Finalista Libertadores)', coach: 'Luiz Felipe Scolari',
    colors: { p: '#c8102e', s: '#000000' },
    players: [
      { name: 'Bento', pos: ['GOL'], ovr: 87 },
      { name: 'Orejuela', pos: ['LD'], ovr: 80 },
      { name: 'Pedro Henrique', pos: ['ZAG'], ovr: 83 },
      { name: 'Thiago Heleno', pos: ['ZAG'], ovr: 82 },
      { name: 'Abner', pos: ['LE'], ovr: 83 },
      { name: 'Christian', pos: ['VOL'], ovr: 84 },
      { name: 'Matheus Fernandes', pos: ['VOL'], ovr: 83 },
      { name: 'Erick', pos: ['VOL'], ovr: 82 },
      { name: 'Fernandinho', pos: ['VOL','MEI'], ovr: 90 },
      { name: 'David Terans', pos: ['MEI','ME'], ovr: 86 },
      { name: 'Canobbio', pos: ['PD','MEI'], ovr: 84 },
      { name: 'Romulo', pos: ['ATA'], ovr: 83 },
      { name: 'Pablo', pos: ['ATA'], ovr: 82 },
      { name: 'Vitor Roque', pos: ['ATA'], ovr: 87 },
      { name: 'Vitinho', pos: ['PD'], ovr: 82 },
      { name: 'Ze Ivaldo', pos: ['ZAG'], ovr: 82 },
      { name: 'Anderson', pos: ['GOL'], ovr: 79 },
      { name: 'Matheus Felipe', pos: ['ZAG'], ovr: 81 },
      { name: 'Pedrinho', pos: ['LE'], ovr: 81 },
      { name: 'Khellven', pos: ['LD'], ovr: 79 },
    ]},
  { id: 'palmeiras2023', club: 'Palmeiras', year: 2023, label: 'Palmeiras 2023 (Tricampeonato com Abel)', coach: 'Abel Ferreira',
    colors: { p: '#006437', s: '#ffffff' },
    players: [
      { name: 'Weverton', pos: ['GOL'], ovr: 91 },
      { name: 'Marcos Rocha', pos: ['LD'], ovr: 83 },
      { name: 'Gustavo Gomez', pos: ['ZAG'], ovr: 91 },
      { name: 'Murilo', pos: ['ZAG'], ovr: 88 },
      { name: 'Piquerez', pos: ['LE'], ovr: 89 },
      { name: 'Danilo', pos: ['VOL','MEI'], ovr: 88 },
      { name: 'Ze Rafael', pos: ['VOL'], ovr: 85 },
      { name: 'Gabriel Menino', pos: ['VOL'], ovr: 83 },
      { name: 'Raphael Veiga', pos: ['MEI','ATA'], ovr: 92 },
      { name: 'Estevao', pos: ['PD','MEI'], ovr: 89 },
      { name: 'Flaco Lopez', pos: ['ATA'], ovr: 90 },
      { name: 'Dudu', pos: ['PD','ATA'], ovr: 87 },
      { name: 'Rony', pos: ['PE','ATA'], ovr: 84 },
      { name: 'Endrick', pos: ['ATA'], ovr: 93 },
      { name: 'Mayke', pos: ['LD'], ovr: 80 },
      { name: 'Vanderlan', pos: ['LE'], ovr: 79 },
      { name: 'Atuesta', pos: ['VOL'], ovr: 80 },
      { name: 'Jhon Jhon', pos: ['MEI'], ovr: 82 },
      { name: 'Artur', pos: ['PD','MD'], ovr: 78 },
      { name: 'Lopes', pos: ['ATA'], ovr: 75 },
    ]},
  { id: 'botafogo2024', club: 'Botafogo', year: 2024, label: 'Botafogo 2024 (Brasileirao + Libertadores)', coach: 'Artur Jorge',
    colors: { p: '#000000', s: '#ffffff' },
    players: [
      { name: 'John', pos: ['GOL'], ovr: 83 },
      { name: 'Vitinho', pos: ['LD'], ovr: 79 },
      { name: 'Alexander Barboza', pos: ['ZAG'], ovr: 82 },
      { name: 'Bastos', pos: ['ZAG'], ovr: 81 },
      { name: 'Cuiabano', pos: ['LE'], ovr: 80 },
      { name: 'Marlon Freitas', pos: ['MC','VOL'], ovr: 82 },
      { name: 'Gregore', pos: ['VOL'], ovr: 81 },
      { name: 'Thiago Almada', pos: ['MEI','PE'], ovr: 85 },
      { name: 'Igor Jesus', pos: ['ATA'], ovr: 87 },
      { name: 'Jefferson Savarino', pos: ['PE','MEI'], ovr: 81 },
      { name: 'Luiz Henrique', pos: ['PD','MD'], ovr: 86 },
      { name: 'Gatito Fernandez', pos: ['GOL'], ovr: 76 },
      { name: 'Adryelson', pos: ['ZAG'], ovr: 78 },
      { name: 'Tiquinho Soares', pos: ['ATA'], ovr: 79 },
      { name: 'Danilo Barbosa', pos: ['VOL','MC'], ovr: 78 },
      { name: 'Tche Tche', pos: ['MC','VOL'], ovr: 78 },
      { name: 'Marcal', pos: ['LE'], ovr: 76 },
      { name: 'Mateo Ponte', pos: ['LD'], ovr: 77 },
      { name: 'Junior Santos', pos: ['PD','ATA'], ovr: 76 },
      { name: 'Carlos Alberto', pos: ['PE','ATA'], ovr: 74 },
    ]},
  { id: 'santos2015', club: 'Santos', year: 2015, label: 'Santos 2015 (Paulistao + Vice Copa BR)', coach: 'Dorival Junior',
    colors: { p: '#000000', s: '#ffffff' },
    players: [
      { name: 'Vanderlei', pos: ['GOL'], ovr: 84 },
      { name: 'Victor Ferraz', pos: ['LD'], ovr: 80 },
      { name: 'David Braz', pos: ['ZAG'], ovr: 83 },
      { name: 'Gustavo Henrique', pos: ['ZAG'], ovr: 82 },
      { name: 'Zeca', pos: ['LE'], ovr: 80 },
      { name: 'Renato', pos: ['VOL'], ovr: 82 },
      { name: 'Thiago Maia', pos: ['VOL'], ovr: 85 },
      { name: 'Lucas Lima', pos: ['MEI','MD'], ovr: 87 },
      { name: 'Marquinhos Gabriel', pos: ['PD','ATA'], ovr: 82 },
      { name: 'Ricardo Oliveira', pos: ['ATA'], ovr: 90 },
      { name: 'Gabigol', pos: ['ATA','PD'], ovr: 85 },
      { name: 'Vladimir', pos: ['GOL'], ovr: 79 },
      { name: 'Daniel Guedes', pos: ['LD'], ovr: 75 },
      { name: 'Luiz Felipe', pos: ['ZAG'], ovr: 79 },
      { name: 'Werley', pos: ['ZAG'], ovr: 76 },
      { name: 'Geuvânio', pos: ['PE','ATA'], ovr: 80 },
      { name: 'Robinho', pos: ['ATA','PE'], ovr: 81 },
      { name: 'Elano', pos: ['MEI'], ovr: 79 },
      { name: 'Leo Cittadini', pos: ['MEI','ME'], ovr: 77 },
      { name: 'Alison', pos: ['VOL'], ovr: 77 },
    ]},
  { id: 'santos2020', club: 'Santos', year: 2020, label: 'Santos 2020 (Vice-Campeao da Libertadores)', coach: 'Cuca',
    colors: { p: '#000000', s: '#ffffff' },
    players: [
      { name: 'John', pos: ['GOL'], ovr: 79 },
      { name: 'Para', pos: ['LD','LE'], ovr: 77 },
      { name: 'Lucas Verissimo', pos: ['ZAG'], ovr: 83 },
      { name: 'Luan Peres', pos: ['ZAG','LE'], ovr: 80 },
      { name: 'Felipe Jonatan', pos: ['LE','ME'], ovr: 78 },
      { name: 'Alison', pos: ['VOL'], ovr: 79 },
      { name: 'Diego Pituca', pos: ['MC','VOL'], ovr: 81 },
      { name: 'Marinho', pos: ['PD','MD'], ovr: 85 },
      { name: 'Soteldo', pos: ['PE','MEI'], ovr: 84 },
      { name: 'Lucas Braga', pos: ['PE','LE'], ovr: 77 },
      { name: 'Kaio Jorge', pos: ['ATA'], ovr: 78 },
      { name: 'Joao Paulo', pos: ['GOL'], ovr: 78 },
      { name: 'Laercio', pos: ['ZAG'], ovr: 73 },
      { name: 'Sandry', pos: ['VOL','MC'], ovr: 76 },
      { name: 'Jean Mota', pos: ['MC','MEI'], ovr: 75 },
      { name: 'Madson', pos: ['LD'], ovr: 76 },
      { name: 'Arthur Gomes', pos: ['PE','MD'], ovr: 75 },
      { name: 'Jobson', pos: ['VOL','MC'], ovr: 75 },
      { name: 'Alex Nascimento', pos: ['ZAG'], ovr: 72 },
      { name: 'Marcos Leonardo', pos: ['ATA'], ovr: 72 },
    ]},
  { id: 'botafogo2023', club: 'Botafogo', year: 2023, label: 'Botafogo 2023 (Deixou escapar)', coach: 'Luis Castro',
    colors: { p: '#000000', s: '#ffffff' },
    players: [
      { name: 'Lucas Perri', pos: ['GOL'], ovr: 85 },
      { name: 'Saravia', pos: ['LD'], ovr: 82 },
      { name: 'Adryelson', pos: ['ZAG'], ovr: 83 },
      { name: 'Victor Cuesta', pos: ['ZAG'], ovr: 82 },
      { name: 'Marcal', pos: ['LE'], ovr: 80 },
      { name: 'Eduardo', pos: ['VOL'], ovr: 83 },
      { name: 'Marlon Freitas', pos: ['VOL'], ovr: 84 },
      { name: 'Tche Tche', pos: ['MEI','VOL'], ovr: 83 },
      { name: 'Gustavo Sauer', pos: ['PD'], ovr: 83 },
      { name: 'Tiquinho Soares', pos: ['ATA'], ovr: 89 },
      { name: 'Jeffinho', pos: ['PE','ATA'], ovr: 84 },
      { name: 'Diego Hernandez', pos: ['MEI'], ovr: 80 },
      { name: 'Hugo', pos: ['GOL'], ovr: 78 },
      { name: 'Rafael', pos: ['LD'], ovr: 79 },
      { name: 'Kayque', pos: ['VOL'], ovr: 80 },
      { name: 'Oscar Romero', pos: ['MEI','MD'], ovr: 82 },
      { name: 'Diego Costa', pos: ['ATA'], ovr: 79 },
      { name: 'Patrick de Paula', pos: ['VOL'], ovr: 82 },
      { name: 'Victor Sa', pos: ['ATA'], ovr: 82 },
      { name: 'Niko Kuhnel', pos: ['MEI'], ovr: 76 },
    ]},
];

